<div class="controls">
<?php if (! $this->compact): ?>
    <?= $this->tabs ?>
<?php endif ?>
    <?= $this->render('partials/comment/comments-header.phtml') ?>
</div>

<div class="content multi-commands">
    <h2><?= $this->translate('Commands') ?></h2>
    <?= $this->qlink(
        sprintf($this->translate('Remove %d comments'), $comments->count()),
        $removeAllLink,
        null,
        array(
            'icon'  => 'trash',
            'title' => $this->translate('Remove all selected comments')
        )
    ) ?>
</div>
