<td class="state-col state-<?= $stateName; ?><?= $downtime->is_in_effect ? ' handled' : ''; ?>">
  <?php if ($downtime->start <= time() && ! $downtime->is_in_effect): ?>
      <strong><?= $this->translate('Ends'); ?></strong>
      <p><?= $this->timeUntil($downtime->is_flexible ? $downtime->scheduled_end : $downtime->end, $this->compact) ?></p>
  <?php else: ?>
      <strong><?= $downtime->is_in_effect ? $this->translate('Expires') : $this->translate('Starts'); ?></strong>
      <p><?= $this->timeUntil($downtime->is_in_effect ? $downtime->end : $downtime->start, $this->compact) ?></p>
  <?php endif; ?>
</td>
<td>
  <span class="comment-header">
    <?php if ($isService): ?>
        <?= $this->icon('service', $this->translate('Service')); ?> <?= $this->qlink(
            $downtime->host_display_name . ': ' . $downtime->service_display_name,
            'monitoring/service/show',
            array(
                'host'    => $downtime->host_name,
                'service' => $downtime->service_description
            ),
            array(
                'title' => sprintf(
                    $this->translate('Show detailed information for this downtime scheduled for service %s on host %s'),
                    $downtime->service_display_name,
                    $downtime->host_display_name
                )
            )
        ); ?>
    <?php else: ?>
        <?= $this->icon('host', $this->translate('host')); ?> <?= $this->qlink(
            $downtime->host_display_name,
            'monitoring/host/show',
            array('host' => $downtime->host_name, 'downtime_id' => $downtime->id),
            array(
                'title' => sprintf(
                    $this->translate('Show detailed information for this downtime scheduled for host %s'),
                    $downtime->host_display_name
                )
            )
        ); ?>
    <?php endif ?>

    <?= $this->translate('by') ?>
    <?= $this->escape($downtime->author_name) ?>

    <span class="pull-right">
          <?php if ($downtime->is_flexible): ?>
              <?= $this->icon('magic', $this->translate('This downtime is flexible')); ?>
          <?php endif ?>

          <?php if ($downtime->is_in_effect): ?>
              <?= $this->icon('plug', $this->translate('This downtime is in effect')); ?>
          <?php endif ?>

          <?php if (isset($delDowntimeForm)): // Form is unset if the current user lacks the respective permission ?>
          <?php
          $delDowntimeForm = clone $delDowntimeForm;
          $delDowntimeForm->populate(
              array(
                  'downtime_id' => $downtime->id,
                  'downtime_is_service' => isset($downtime->service_description)
              )
          );
          echo $delDowntimeForm;
          ?>
          <?php endif ?>
    </span>
  </span>
  <?php if (isset ($displayComment) && $displayComment): ?>
    <p class="comment-text">
      <?= $this->escape($downtime->comment) ?>
    </p>
  <?php endif ?>
</td>
