<span class="state">
    <table>
        <caption>Status Summary</caption>
        <thead>
            <th>Hosts</th>
            <th>Services</th>
        </thead>
        <tbody>
<?php if ($this->statusSummary->hosts_up): ?>
            <tr>
                <td>
                    <span class="state up">
                        <a href="<?= $this->href(
                            'monitoring/list/hosts',
                            array('host_state' => 0)
                        ); ?>">
                            <?= $this->statusSummary->hosts_up; ?> UP
                        </a>
<?php if ($this->statusSummary->hosts_up_not_checked): ?>
                        <span class="state up not_checked">
                            <a href="<?= $this->href(
                                'monitoring/list/hosts',
                                array(
                                    'host_state' => 0,
                                    'host_active_checks_enabled' => 0,
                                    'host_passive_checks_enabled' => 0
                                )
                            ); ?>">
                                <?= $this->statusSummary->hosts_up_not_checked; ?> disabled
                            </a>
                        </span>
<?php endif ?>
                    </span>
                </td>
                <td>
                    <?= $this->partial(
                        'tactical/components/parts/servicestatesummarybyhoststate.phtml',
                        array(
                            'hostState'                                 => 0,
                            'services_ok'                               => $this->statusSummary->services_ok_on_up_hosts,
                            'services_ok_not_checked'                   => $this->statusSummary->services_ok_not_checked_on_up_hosts,
                            'services_pending'                          => $this->statusSummary->services_pending_on_up_hosts,
                            'services_pending_not_checked'              => $this->statusSummary->services_pending_not_checked_on_up_hosts,
                            'services_warning_handled_active'           => $this->statusSummary->services_warning_handled_active_on_up_hosts,
                            'services_warning_handled_passive'          => $this->statusSummary->services_warning_handled_passive_on_up_hosts,
                            'services_warning_handled_not_checked'      => $this->statusSummary->services_warning_handled_not_checked_on_up_hosts,
                            'services_warning_unhandled_active'         => $this->statusSummary->services_warning_unhandled_active_on_up_hosts,
                            'services_warning_unhandled_passive'        => $this->statusSummary->services_warning_unhandled_passive_on_up_hosts,
                            'services_warning_unhandled_not_checked'    => $this->statusSummary->services_warning_unhandled_not_checked_on_up_hosts,
                            'services_critical_handled_active'          => $this->statusSummary->services_critical_handled_active_on_up_hosts,
                            'services_critical_handled_passive'         => $this->statusSummary->services_critical_handled_passive_on_up_hosts,
                            'services_critical_handled_not_checked'     => $this->statusSummary->services_critical_handled_not_checked_on_up_hosts,
                            'services_critical_unhandled_active'        => $this->statusSummary->services_critical_unhandled_active_on_up_hosts,
                            'services_critical_unhandled_passive'       => $this->statusSummary->services_critical_unhandled_passive_on_up_hosts,
                            'services_critical_unhandled_not_checked'   => $this->statusSummary->services_critical_unhandled_not_checked_on_up_hosts,
                            'services_unknown_handled_active'           => $this->statusSummary->services_unknown_handled_active_on_up_hosts,
                            'services_unknown_handled_passive'          => $this->statusSummary->services_unknown_handled_passive_on_up_hosts,
                            'services_unknown_handled_not_checked'      => $this->statusSummary->services_unknown_handled_not_checked_on_up_hosts,
                            'services_unknown_unhandled_active'         => $this->statusSummary->services_unknown_unhandled_active_on_up_hosts,
                            'services_unknown_unhandled_passive'        => $this->statusSummary->services_unknown_unhandled_passive_on_up_hosts,
                            'services_unknown_unhandled_not_checked'    => $this->statusSummary->services_unknown_unhandled_not_checked_on_up_hosts
                        )
                    ); ?>
                </td>
            </tr>
<?php endif ?>
<?php if ($this->statusSummary->hosts_pending): ?>
            <tr>
                <td>
                    <span class="state pending">
                        <a href="<?= $this->href(
                            'monitoring/list/hosts',
                            array('host_state' => 99)
                        ); ?>">
                            <?= $this->statusSummary->hosts_pending; ?> PENDING
                        </a>
<?php if ($this->statusSummary->hosts_pending_not_checked): ?>
                        <span class="state pending not_checked">
                            <a href="<?= $this->href(
                                'monitoring/list/hosts',
                                array(
                                    'host_state' => 99,
                                    'host_active_checks_enabled' => 0,
                                    'host_passive_checks_enabled' => 0
                                )
                            ); ?>">
                                <?= $this->statusSummary->hosts_pending_not_checked; ?> disabled
                            </a>
                        </span>
<?php endif ?>
                    </span>
                </td>
                <td>
                    <?= $this->partial(
                        'tactical/components/parts/servicestatesummarybyhoststate.phtml',
                        array(
                            'hostState'                                 => 99,
                            'services_ok'                               => $this->statusSummary->services_ok_on_pending_hosts,
                            'services_ok_not_checked'                   => $this->statusSummary->services_ok_not_checked_on_pending_hosts,
                            'services_pending'                          => $this->statusSummary->services_pending_on_pending_hosts,
                            'services_pending_not_checked'              => $this->statusSummary->services_pending_not_checked_on_pending_hosts,
                            'services_warning_handled_active'           => $this->statusSummary->services_warning_handled_active_on_pending_hosts,
                            'services_warning_handled_passive'          => $this->statusSummary->services_warning_handled_passive_on_pending_hosts,
                            'services_warning_handled_not_checked'      => $this->statusSummary->services_warning_handled_not_checked_on_pending_hosts,
                            'services_warning_unhandled_active'         => $this->statusSummary->services_warning_unhandled_active_on_pending_hosts,
                            'services_warning_unhandled_passive'        => $this->statusSummary->services_warning_unhandled_passive_on_pending_hosts,
                            'services_warning_unhandled_not_checked'    => $this->statusSummary->services_warning_unhandled_not_checked_on_pending_hosts,
                            'services_critical_handled_active'          => $this->statusSummary->services_critical_handled_active_on_pending_hosts,
                            'services_critical_handled_passive'         => $this->statusSummary->services_critical_handled_passive_on_pending_hosts,
                            'services_critical_handled_not_checked'     => $this->statusSummary->services_critical_handled_not_checked_on_pending_hosts,
                            'services_critical_unhandled_active'        => $this->statusSummary->services_critical_unhandled_active_on_pending_hosts,
                            'services_critical_unhandled_passive'       => $this->statusSummary->services_critical_unhandled_passive_on_pending_hosts,
                            'services_critical_unhandled_not_checked'   => $this->statusSummary->services_critical_unhandled_not_checked_on_pending_hosts,
                            'services_unknown_handled_active'           => $this->statusSummary->services_unknown_handled_active_on_pending_hosts,
                            'services_unknown_handled_passive'          => $this->statusSummary->services_unknown_handled_passive_on_pending_hosts,
                            'services_unknown_handled_not_checked'      => $this->statusSummary->services_unknown_handled_not_checked_on_pending_hosts,
                            'services_unknown_unhandled_active'         => $this->statusSummary->services_unknown_unhandled_active_on_pending_hosts,
                            'services_unknown_unhandled_passive'        => $this->statusSummary->services_unknown_unhandled_passive_on_pending_hosts,
                            'services_unknown_unhandled_not_checked'    => $this->statusSummary->services_unknown_unhandled_not_checked_on_pending_hosts
                        )
                    ); ?>
                </td>
            </tr>
<?php endif ?>
<?php if ($this->statusSummary->hosts_down): ?>
            <tr>
                <td>
                    <span class="state down">
                        <a href="<?= $this->href(
                            'monitoring/list/hosts',
                            array('host_state' => 1)
                        ); ?>">
                            <?= $this->statusSummary->hosts_down; ?> DOWN
                        </a>
<?php if ($this->statusSummary->hosts_down_unhandled): ?>
                        <span class="state down unhandled">
                            <a href="<?= $this->href(
                            'monitoring/list/hosts',
                            array('host_state' => 1, 'host_handled' => 0)
                        ); ?>">
                                <?= $this->statusSummary->hosts_down_unhandled; ?> unhandled
                            </a>
<?php if ($this->statusSummary->hosts_down_unhandled_active): ?>
                            <span class="state down unhandled active">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 1,
                                        'host_handled' => 0,
                                        'host_active_checks_enabled' => 1
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_down_unhandled_active; ?> Active
                                </a>
                            </span>
<?php endif ?>
<?php if ($this->statusSummary->hosts_down_unhandled_passive): ?>
                            <span class="state down unhandled passive">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 1,
                                        'host_handled' => 0,
                                        'host_active_checks_enabled' => 0,
                                        'host_passive_checks_enabled' => 1
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_down_unhandled_passive; ?> Passive
                                </a>
                            </span>
<?php endif ?>
<?php if ($this->statusSummary->hosts_down_unhandled_not_checked): ?>
                            <span class="state down unhandled not_checked">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 1,
                                        'host_handled' => 0,
                                        'host_active_checks_enabled' => 0,
                                        'host_passive_checks_enabled' => 0
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_down_unhandled_not_checked; ?> Not checked
                                </a>
                            </span>
<?php endif ?>
                        </span>
<?php endif ?>
<?php if ($this->statusSummary->hosts_down_handled): ?>
                        <span class="state down handled">
                            <a href="<?= $this->href(
                            'monitoring/list/hosts',
                            array('host_state' => 1, 'host_handled' => 1)
                        ); ?>">
                                <?= $this->statusSummary->hosts_down_handled; ?> handled
                            </a>
<?php if ($this->statusSummary->hosts_down_handled_active): ?>
                            <span class="state down handled active">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 1,
                                        'host_handled' => 1,
                                        'host_active_checks_enabled' => 1
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_down_handled_active; ?> Active
                                </a>
                            </span>
<?php endif ?>
<?php if ($this->statusSummary->hosts_down_handled_passive): ?>
                            <span class="state down handled passive">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 1,
                                        'host_handled' => 1,
                                        'host_active_checks_enabled' => 0,
                                        'host_passive_checks_enabled' => 1
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_down_handled_passive; ?> Passive
                                </a>
                            </span>
<?php endif ?>
<?php if ($this->statusSummary->hosts_down_handled_not_checked): ?>
                            <span class="state down handled not_checked">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 1,
                                        'host_handled' => 1,
                                        'host_active_checks_enabled' => 0,
                                        'host_passive_checks_enabled' => 0
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_down_handled_not_checked; ?> Not checked
                                </a>
                            </span>
<?php endif ?>
                        </span>
<?php endif ?>
                    </span>
                </td>
                <td>
                    <?= $this->partial(
                        'tactical/components/parts/servicestatesummarybyhoststate.phtml',
                        array(
                            'hostState'                                 => 1,
                            'services_ok'                               => $this->statusSummary->services_ok_on_down_hosts,
                            'services_ok_not_checked'                   => $this->statusSummary->services_ok_not_checked_on_down_hosts,
                            'services_pending'                          => $this->statusSummary->services_pending_on_down_hosts,
                            'services_pending_not_checked'              => $this->statusSummary->services_pending_not_checked_on_down_hosts,
                            'services_warning_handled_active'           => $this->statusSummary->services_warning_handled_active_on_down_hosts,
                            'services_warning_handled_passive'          => $this->statusSummary->services_warning_handled_passive_on_down_hosts,
                            'services_warning_handled_not_checked'      => $this->statusSummary->services_warning_handled_not_checked_on_down_hosts,
                            'services_warning_unhandled_active'         => $this->statusSummary->services_warning_unhandled_active_on_down_hosts,
                            'services_warning_unhandled_passive'        => $this->statusSummary->services_warning_unhandled_passive_on_down_hosts,
                            'services_warning_unhandled_not_checked'    => $this->statusSummary->services_warning_unhandled_not_checked_on_down_hosts,
                            'services_critical_handled_active'          => $this->statusSummary->services_critical_handled_active_on_down_hosts,
                            'services_critical_handled_passive'         => $this->statusSummary->services_critical_handled_passive_on_down_hosts,
                            'services_critical_handled_not_checked'     => $this->statusSummary->services_critical_handled_not_checked_on_down_hosts,
                            'services_critical_unhandled_active'        => $this->statusSummary->services_critical_unhandled_active_on_down_hosts,
                            'services_critical_unhandled_passive'       => $this->statusSummary->services_critical_unhandled_passive_on_down_hosts,
                            'services_critical_unhandled_not_checked'   => $this->statusSummary->services_critical_unhandled_not_checked_on_down_hosts,
                            'services_unknown_handled_active'           => $this->statusSummary->services_unknown_handled_active_on_down_hosts,
                            'services_unknown_handled_passive'          => $this->statusSummary->services_unknown_handled_passive_on_down_hosts,
                            'services_unknown_handled_not_checked'      => $this->statusSummary->services_unknown_handled_not_checked_on_down_hosts,
                            'services_unknown_unhandled_active'         => $this->statusSummary->services_unknown_unhandled_active_on_down_hosts,
                            'services_unknown_unhandled_passive'        => $this->statusSummary->services_unknown_unhandled_passive_on_down_hosts,
                            'services_unknown_unhandled_not_checked'    => $this->statusSummary->services_unknown_unhandled_not_checked_on_down_hosts
                        )
                    ); ?>
                </td>
            </tr>
<?php endif ?>
<?php if ($this->statusSummary->hosts_unreachable): ?>
            <tr>
                <td>
                    <span class="state unreachable">
                        <a href="<?= $this->href(
                            'monitoring/list/hosts',
                            array('host_state' => 2)
                        ); ?>">
                            <?= $this->statusSummary->hosts_unreachable; ?> UNREACHABLE
                        </a>
<?php if ($this->statusSummary->hosts_unreachable_unhandled): ?>
                        <span class="state unreachable unhandled">
                            <a href="<?= $this->href(
                            'monitoring/list/hosts',
                            array('host_state' => 2, 'host_handled' => 0)
                        ); ?>">
                                <?= $this->statusSummary->hosts_unreachable_unhandled; ?> unhandled
                            </a>
<?php if ($this->statusSummary->hosts_unreachable_unhandled_active): ?>
                            <span class="state unreachable unhandled active">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 2,
                                        'host_handled' => 0,
                                        'host_active_checks_enabled' => 1
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_unreachable_unhandled_active; ?> Active
                                </a>
                            </span>
<?php endif ?>
<?php if ($this->statusSummary->hosts_unreachable_unhandled_passive): ?>
                            <span class="state unreachable unhandled passive">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 2,
                                        'host_handled' => 0,
                                        'host_active_checks_enabled' => 0,
                                        'host_passive_checks_enabled' => 1
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_unreachable_unhandled_passive; ?> Passive
                                </a>
                            </span>
<?php endif ?>
<?php if ($this->statusSummary->hosts_unreachable_unhandled_not_checked): ?>
                            <span class="state unreachable unhandled not_checked">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 2,
                                        'host_handled' => 0,
                                        'host_active_checks_enabled' => 0,
                                        'host_passive_checks_enabled' => 0
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_unreachable_unhandled_not_checked; ?> Not checked
                                </a>
                            </span>
<?php endif ?>
                        </span>
<?php endif ?>
<?php if ($this->statusSummary->hosts_unreachable_handled): ?>
                        <span class="state unreachable handled">
                            <a href="<?= $this->href(
                            'monitoring/list/hosts',
                            array('host_state' => 2, 'host_handled' => 1)
                        ); ?>">
                                <?= $this->statusSummary->hosts_unreachable_handled; ?> handled
                            </a>
<?php if ($this->statusSummary->hosts_unreachable_handled_active): ?>
                            <span class="state unreachable handled active">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 2,
                                        'host_handled' => 1,
                                        'host_active_checks_enabled' => 1
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_unreachable_handled_active; ?> Active
                                </a>
                            </span>
<?php endif ?>
<?php if ($this->statusSummary->hosts_unreachable_handled_passive): ?>
                            <span class="state unreachable handled passive">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 2,
                                        'host_handled' => 1,
                                        'host_active_checks_enabled' => 0,
                                        'host_passive_checks_enabled' => 1
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_unreachable_handled_passive; ?> Passive
                                </a>
                            </span>
<?php endif ?>
<?php if ($this->statusSummary->hosts_unreachable_handled_not_checked): ?>
                            <span class="state unreachable handled not_checked">
                                <a href="<?= $this->href(
                                    'monitoring/list/hosts',
                                    array(
                                        'host_state' => 2,
                                        'host_handled' => 1,
                                        'host_active_checks_enabled' => 0,
                                        'host_passive_checks_enabled' => 0
                                    )
                                ); ?>">
                                    <?= $this->statusSummary->hosts_unreachable_handled_not_checked; ?> Not checked
                                </a>
                            </span>
<?php endif ?>
                        </span>
<?php endif ?>
                    </span>
                </td>
                <td>
                    <?= $this->partial(
                        'tactical/components/parts/servicestatesummarybyhoststate.phtml',
                        array(
                            'hostState'                                 => 2,
                            'services_ok'                               => $this->statusSummary->services_ok_on_unreachable_hosts,
                            'services_ok_not_checked'                   => $this->statusSummary->services_ok_not_checked_on_unreachable_hosts,
                            'services_pending'                          => $this->statusSummary->services_pending_on_unreachable_hosts,
                            'services_pending_not_checked'              => $this->statusSummary->services_pending_not_checked_on_unreachable_hosts,
                            'services_warning_handled_active'           => $this->statusSummary->services_warning_handled_active_on_unreachable_hosts,
                            'services_warning_handled_passive'          => $this->statusSummary->services_warning_handled_passive_on_unreachable_hosts,
                            'services_warning_handled_not_checked'      => $this->statusSummary->services_warning_handled_not_checked_on_unreachable_hosts,
                            'services_warning_unhandled_active'         => $this->statusSummary->services_warning_unhandled_active_on_unreachable_hosts,
                            'services_warning_unhandled_passive'        => $this->statusSummary->services_warning_unhandled_passive_on_unreachable_hosts,
                            'services_warning_unhandled_not_checked'    => $this->statusSummary->services_warning_unhandled_not_checked_on_unreachable_hosts,
                            'services_critical_handled_active'          => $this->statusSummary->services_critical_handled_active_on_unreachable_hosts,
                            'services_critical_handled_passive'         => $this->statusSummary->services_critical_handled_passive_on_unreachable_hosts,
                            'services_critical_handled_not_checked'     => $this->statusSummary->services_critical_handled_not_checked_on_unreachable_hosts,
                            'services_critical_unhandled_active'        => $this->statusSummary->services_critical_unhandled_active_on_unreachable_hosts,
                            'services_critical_unhandled_passive'       => $this->statusSummary->services_critical_unhandled_passive_on_unreachable_hosts,
                            'services_critical_unhandled_not_checked'   => $this->statusSummary->services_critical_unhandled_not_checked_on_unreachable_hosts,
                            'services_unknown_handled_active'           => $this->statusSummary->services_unknown_handled_active_on_unreachable_hosts,
                            'services_unknown_handled_passive'          => $this->statusSummary->services_unknown_handled_passive_on_unreachable_hosts,
                            'services_unknown_handled_not_checked'      => $this->statusSummary->services_unknown_handled_not_checked_on_unreachable_hosts,
                            'services_unknown_unhandled_active'         => $this->statusSummary->services_unknown_unhandled_active_on_unreachable_hosts,
                            'services_unknown_unhandled_passive'        => $this->statusSummary->services_unknown_unhandled_passive_on_unreachable_hosts,
                            'services_unknown_unhandled_not_checked'    => $this->statusSummary->services_unknown_unhandled_not_checked_on_unreachable_hosts
                        )
                    ); ?>
                </td>
            </tr>
<?php endif ?>
        </tbody>
    </table>
</span>
