<?php
use Icinga\Web\Widget\SearchDashboard;
?>

<? if (SearchDashboard::search('dummy')->getPane('search')->hasDashlets()): ?>
    <form action="<?= $this->href('search') ?>" method="get" role="search">
        <input
            type="text" name="q" id="search" class="search" placeholder="<?= $this->translate('Search') ?> &hellip;"
            autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"
        />
    </form>
<? endif; ?>
<nav>
    <h1 id="navigation" class="sr-only"><?= t('Navigation'); ?></h1>
    <?= $menuRenderer; ?>
</nav>