<?php
switch ($comment->type) {
    case 'flapping':
        $icon = 'flapping';
        $title = $this->translate('Flapping');
        $tooltip = $this->translate('Comment was caused by a flapping host or service');
        break;
    case 'comment':
        $icon = 'user';
        $title = $this->translate('User Comment');
        $tooltip = $this->translate('Comment was created by an user');
        break;
    case 'downtime':
        $icon = 'plug';
        $title = $this->translate('Downtime');
        $tooltip = $this->translate('Comment was caused by a downtime');
        break;
    case 'ack':
        $icon = 'ok';
        $title = $this->translate('Acknowledgement');
        $tooltip = $this->translate('Comment was caused by an acknowledgement');
        break;
}
echo $this->icon($icon, $tooltip, array('class' => 'large-icon'));
