<table class="action">
    <?php $i = 0; foreach ($comments as $comment):
        if (++ $i > 5) {
            continue;
        }
        $this->comment = $comment;
    ?>

        <tr class="state invalid">
          <td class="state" style="width: 12em;">
            <?= $this->render('partials/comment/comment-description.phtml'); ?>
          </td>
          <td>
            <?= $this->render('partials/comment/comment-detail.phtml'); ?>
          </td>
        </tr>
    <?php endforeach; ?>
</table>

<p>
    <?= $this->qlink(
        sprintf($this->translate('List all %d comments …'), count($comments)),
        $listAllLink,
        null,
        array(
            'title' => $this->translate('List all'),
            'data-base-target' => "_next"
        )
    ) ?>
</p>
