<?php if ($comment->objecttype === 'service'): ?>
    <?= $this->icon('service', $this->translate('Service')); ?>
    <?= sprintf(
        $this->translate('%s on %s', 'Service running on host'),
        $comment->service_display_name,
        $comment->host_display_name
    ) ?>
<?php else: ?>
    <?= $this->icon('host', $this->translate('Host')); ?>
    <?= $this->link()->host($comment->host_name, $comment->host_display_name); ?>
<?php endif ?>

<br>
<?= $this->icon('comment', $this->translate('Comment')); ?> <?= isset($comment->author)
  ? '[' . $this->escape($comment->author) . '] '
  : '';
?><?= $this->escape($comment->comment); ?>
