<?php if ($comment->objecttype === 'service'): ?>
    <?= $this->icon('service', $this->translate('Service')) ?>
    <?= sprintf(
        '%s: %s',
        $comment->host_display_name,
        $comment->service_display_name
    ) ?>
<?php else: ?>
    <?= $this->icon('host', $this->translate('Host')) ?>
    <?= $this->link()->host($comment->host_name, $comment->host_display_name) ?>
<?php endif ?>
<br>
<?= $this->icon('comment', $this->translate('Comment')) ?>
<?php if (isset($comment->author)): ?>
    [<?= $this->escape($comment->author) ?>]
<?php endif ?>
<?= $this->escape($comment->comment) ?>
