<?php

$objectName = $this->is_service ? 'Services' : 'Hosts';

?><tr class="newsection" data-base-target="_next">
  <th><a href=<?= sprintf($this->translatePlural('%u Comment', '%u Comments', count($comments)), count($comments)) ?></th>
  <td>
    <a href="<?= $this->href('monitoring/command/removecomment', $this->target) ?>"><?=
        $this->icon('cancel')
    ?> <?= $this->translate('Remove Comments') ?></a><br />
    <a href="<?= $this->href('monitoring/command/delaynotifications', $this->target); ?>"><?=
        $this->icon('bell-off-empty')
    ?> <?= $this->translate('Delay Notifications') ?></a><br />
    <a title="<?= $this->translate('Acknowledge all problems on the selected hosts or services') ?>"
        href="<?= $this->href('monitoring/command/acknowledgeproblem') ?>, $this->target); ?>">
        <?= $this->icon('ok') ?> Acknowledge
    </a>
  </td>
  <td><a href=" <?= $this->href(
          'monitoring/list/comments',
          array('comment_internal_id' => '(' . implode('|', $this->comments) . ')')
      );
      ?>"> <?= sprintf($this->translatePlural('%u comment', '%u comments', count($comments)), count($comments)) ?></a>.
  </td>
</tr>
