
<!--<?php echo $this->form->render($this); ?>-->

<form>
<?php foreach($this->form->getElements() as $name => $element):
    if ($element instanceof \Icinga\Web\Form\Element\TriStateCheckbox):
        $element->setDecorators(array('ViewHelper'));
        ?>
        <tr>
                <th>
                    <?= $element->getLabel() ?>
                </th>
                <td>
                    <?= $element->render() ?>
                </td>
        </tr>

    <?php else: ?>
        <tr>
            <td> <?= $element->render() ?></td>
        </tr>
    <?php
        endif;
        endforeach;
    ?>
<form>
