<form
    id="<?= $form->getId() ?>"
    name="<?= $form->getName() ?>"
    enctype="<?= $form->getEnctype() ?>"
    action="<?= $form->getAction() ?>"
    method="post"
>
  <table class="avp newsection">
  <?php foreach($this->form->getElements() as $name => $element):
    if ($element instanceof \Icinga\Web\Form\Element\TriStateCheckbox):
        $element->setDecorators(array('ViewHelper'));
    ?>
    <tr>
      <th><label for="<?= $element->getName() ?>"> <?= $element->getLabel() ?> </label></th>
      <td><?= $element->render() ?></td>
    </tr>
    <?php else: ?>
    <tr>
      <th></th>
      <td><?= $element->render() ?></td>
    </tr>
    <?php endif ?>
  <?php endforeach ?>
  </table>
</form>