<?php for ($i = 0; $i < count($objects) && $i < 5; $i++) {
    $object = $objects[$i]; ?>
    <a data-base-target='_next' href="<?php
    if ($this->is_service) {
        echo $this->href(
            'monitoring/show/service',
            array('host' => $object->host_name, 'service' => $object->service_description)
        );
        echo '">' . $object->host_name . ' ' . $object->service_description . '</a>';
    } else {
        echo $this->href(
            'monitoring/show/host',
            array('host' => $object->host_name)
        );
        echo '">' . $object->host_name . '</a>';
    }?>,
<?php } ?> <?php
    if (count($objects) > 5) {
       echo '<i> ... ' . (count($objects) - 5) . ' more ... </i>';
    }

    if (!$this->is_service) {
        $link = 'monitoring/list/hosts';
        $target = array(
            'host' => $this->hostquery
        );
    } else {
        $link = 'monitoring/list/services';
        $target = array(
            'host'    => $this->hostquery,
            'service' => $this->servicequery
        );
    }
?> <a data-base-target='_next' href='<?= $this->href($link, $this->query); ?>'><b> list all </b></a>