<?php
    /** @var Zend_View_Helper_CommandForm $cf */
    $cf = $this->getHelper('CommandForm');
    $servicequery = isset($this->servicequery) ? $this->servicequery : '';
    $objectName = $this->is_service ? 'Services' : 'Hosts';
?>

<tr>
    <th>
        <?= $objectName ?>
    </th>
    <td>
        You have selected <?= count($objects) . ' ' . $objectName ?> .
    </td>
    <td>
        <a
            href="<?=$this->href(
                'monitoring/command/reschedulenextcheck',
                array(
                    'host'       => $this->target['host'],
                    'service'    => $this->target['service'],
                    'checktime'  => time(),
                    'forcecheck' => '1'
                )
            ); ?>"
        >
            <?= $this->icon('refresh_petrol.png') ?> Recheck
        </a> <br/>
        <a href="<?= $this->href('monitoring/command/reschedulenextcheck', $this->target) ?>">
            <?= $this->icon('reschedule_petrol.png') ?> Reschedule
        </a>
    </td>
</tr>

<tr>
    <th>
        Problems
    </th>
    <td>
        The <?= $objectName ?> have <span> <?= $this->problems ?> </span> problems.
    </td>
    <td>
        <a
            title="Schedule downtimes for all selected hosts"
            href="<?= $this->href('monitoring/command/scheduledowntime', $this->target); ?>"
        >
            <?= $this->icon('in_downtime_petrol.png') ?> Schedule Downtimes
        </a>
    </td>
</tr>


<tr>
    <th>
        Unhandled
    </th>
    <td>
        <span> <?= count($this->unhandled) ?> </span> <?= $objectName ?> are unhandled.
    </td>
    <td>
        <a
            title="Acknowledge all problems on the selected hosts or services"
            href="<?= $this->href('monitoring/command/acknowledgeproblem', $this->target);?>"
            >
            <?= $this->icon('acknowledgement_petrol.png') ?> Acknowledge
        </a>
    </td>
</tr>