<?php

use Icinga\Application\Icinga;
use Icinga\Application\Platform;
use Icinga\Web\Wizard;

$setupTokenPath = rtrim(Icinga::app()->getConfigDir(), '/') . '/setup.token';

?>
<div class="welcome-page">
  <h2><?= t('Welcome to the installation of Icinga Web 2!') ?></h2>
  <!-- TODO: Remove this once we release the first public version -->
  <div style="border:1px solid #777;border-radius:1em;background-color:beige;padding:1em;margin-bottom:1em;display:inline-block;">
    Icinga Web 2 is still in development and not meant for production deployment.
    Watch the <a href="https://dev.icinga.org/projects/icingaweb2/roadmap">development roadmap</a> and
    <a href="https://www.icinga.org/">Icinga website</a> for release schedule updates!
  </div>
  <div class="info">
    <p><?= sprintf(
      t(
        'Icinga Web 2 is the next generation monitoring web interface,'
        . ' framework and CLI tool developed by the %s.'
      ),
      '<a href="https://www.icinga.org/community/team/">' . t('Icinga Project') . '</a>'
    ); ?></p>
    <p><?= t(
      'Responsive and fast, rewritten from scratch supporting multiple backends and'
      . ' providing a CLI tool. Compatible with Icinga Core 2.x and 1.x.'
    ); ?></p>
    <p><?= sprintf(
      t('Check the Icinga website for some %s.', 'setup.welcome.screenshots'),
      '<a href="https://www.icinga.org/icinga/screenshots/icinga-web-2/">'
      . t('insights', 'setup.welcome.screenshots.label') . '</a>'
    ); ?></p>
  </div>
  <p><?= t(
    'This wizard will guide you through the installation of Icinga Web 2. Once completed and successfully'
    . ' finished you are able to log in and to explore all the new and stunning features!'
  ); ?></p>
  <form id="<?= $form->getName(); ?>" name="<?= $form->getName(); ?>" enctype="<?= $form->getEncType(); ?>" method="<?= $form->getMethod(); ?>" action="<?= $form->getAction(); ?>">
    <?= $form->getElement('token'); ?>
    <?= $form->getElement($form->getTokenElementName()); ?>
    <?= $form->getElement($form->getUidElementName()); ?>
    <div class="buttons">
      <?= $form->getElement(Wizard::BTN_NEXT); ?>
    </div>
  </form>
  <div class="note">
    <div class="title">
      <img src="<?= $this->href('img/icons/comment.png'); ?>" alt="<?= t('Note'); ?>">
      <strong>Generating a New Setup Token</strong>
    </div>
    <div>
      <p><?=
        t('To run this wizard a user needs to authenticate using a token which is usually'
        . ' provided to him by an administrator who\'d followed the instructions below.'
      ); ?></p>
      <p><?= t('If you\'ve got the IcingaCLI installed you can do the following:'); ?></p>
      <div class="code">
        <span>sudo icingacli setup createConfigDirectory <?= Platform::getPhpUser(); ?>;</span>
        <span>sudo icingacli setup generateToken;</span>
      </div>
      <p><?= t('In case the IcingaCLI is missing you can create the token manually:'); ?></p>
      <div class="code">
        <span>sudo mkdir -m 2775 <?= dirname($setupTokenPath); ?> && sudo chgrp <?= Platform::getPhpUser(); ?> <?= dirname($setupTokenPath); ?>;</span>
        <span>head -c 12 /dev/urandom | base64 | sudo -u '<?= Platform::getPhpUser(); ?>' tee <?= $setupTokenPath; ?>;</span>
        <span>sudo chmod 0660 <?= $setupTokenPath; ?>;</span>
      </div>
      <p style="font-size: 85%;"><?= sprintf(
        t('Please see the %s for an extensive description on how to access and use this wizard.'),
        '<a href="http://docs.icinga.org/">' . t('Icinga Web 2 documentation') . '</a>' // TODO: Add link to iw2 docs which points to the installation topic
      ); ?></p>
    </div>
  </div>
</div>