<?php

use Icinga\Web\Wizard;
use Icinga\Web\Setup\Requirements;

$requirements = $form->getRequirements();

?>
<table class="requirements">
  <tbody>
<?php foreach ($requirements as $requirement): ?>
    <tr>
      <td><?= $requirement->title; ?></td>
      <td><?= $requirement->description; ?></td>
      <td class="<?= $requirement->state === Requirements::STATE_OK ? 'fulfilled' : (
        $requirement->state === Requirements::STATE_OPTIONAL ? 'not-available' : 'missing'
      ); ?>"><?= $requirement->message; ?></td>
    </tr>
<?php endforeach ?>
  </tbody>
</table>
<form id="<?= $form->getName(); ?>" name="<?= $form->getName(); ?>" enctype="<?= $form->getEncType(); ?>" method="<?= $form->getMethod(); ?>">
  <?= $form->getElement($form->getTokenElementName()); ?>
  <?= $form->getElement($form->getUidElementName()); ?>
  <?= $form->getElement(Wizard::BTN_PREV); ?>
  <?php
    $btn = $form->getElement(Wizard::BTN_NEXT);
    if (false === $requirements->fulfilled()) {
        $btn->setAttrib('disabled', 1);
    }
    echo $btn;
  ?>
</form>