<?php

use Icinga\Web\Wizard;

?>
<div class="module-menu">
  <p><?= t('The following modules are available for installation using a web-based wizard as well. To install a module, just complete it\'s wizard and advance to the summary!'); ?></p>
  <p><?= t('You can freely switch to a module\'s wizard by clicking it\'s name below. The wizard you are currently looking at is written in bold. A small tick is shown on the right once a wizard has been completed.'); ?></p>
  <form name="<?= $form->getName(); ?>" enctype="<?= $form->getEncType(); ?>" method="<?= $form->getMethod(); ?>">
    <?= $form->getElement($form->getTokenElementName()); ?>
    <?= $form->getElement($form->getUidElementName()); ?>
    <ul>
    <?php $allFinished = true; ?>
    <?php foreach ($form->getModules() as $module): ?>
     <?php if ($module->providesSetupWizard()): ?>
      <li>
        <?php $isActive = $module->getName() === $form->getCurrentModule(); ?>
        <button type="submit" name="module" value="<?= $module->getName(); ?>">
          <?= $isActive ? '<strong>' : '' ?><?= $module->getTitle(); ?><?= $isActive ? '</strong>' : '' ?>
        </button>
       <?php if ($module->getSetupWizard()->isFinished()): ?>
        <?= $this->icon('acknowledgement.png', t('Completed', 'setup.modules.wizard.state')); ?>
       <?php else: ?>
        <?php $allFinished = false; ?>
       <?php endif ?>
      </li>
     <?php endif ?>
    <?php endforeach ?>
    </ul>
  </form>
 <?php if ($allFinished): ?>
  <p class="all-completed"><?= t('You\'ve completed all module wizards!'); ?></p>
 <?php else: ?>
  <p style="font-size: 80%;"><?= t('Note that you can skip a specific module by just not completing it\'s wizard.'); ?></p>
 <?php endif ?>
</div>
<div class="module-wizard">
  <?= $form->getCurrentWizard()->getForm()->render(); ?>
</div>
<form name="<?= $form->getName(); ?>" enctype="<?= $form->getEncType(); ?>" method="<?= $form->getMethod(); ?>">
  <?= $form->getElement($form->getTokenElementName()); ?>
  <?= $form->getElement($form->getUidElementName()); ?>
  <div class="buttons">
    <?= $form->getElement(Wizard::BTN_PREV); ?>
    <?= $form->getElement(Wizard::BTN_NEXT); ?>
  </div>
</form>