<?php

use Icinga\Web\Wizard;

?>
<p><?= sprintf(
  t(
    'The wizard is now complete. You can review the changes supposed to be made before issuing the actual installation'
    . ' of %1$s. Make sure that everything is correct (Feel free to navigate back to make any corrections!) so'
    . ' that you can start using %1$s right after the installation has been finished.'
  ),
  $form->getSubjectTitle()
); ?></p>
<div class="summary">
<?php foreach ($form->getSummary() as $pageHtml): ?>
 <?php if ($pageHtml): ?>
  <div class="page">
    <?= $pageHtml; ?>
  </div>
 <?php endif ?>
<?php endforeach ?>
</div>
<form id="<?= $form->getName(); ?>" name="<?= $form->getName(); ?>" enctype="<?= $form->getEncType(); ?>" method="<?= $form->getMethod(); ?>" action="<?= $form->getAction(); ?>">
  <?= $form->getElement($form->getTokenElementName()); ?>
  <?= $form->getElement($form->getUidElementName()); ?>
  <div class="buttons">
    <?= $form->getElement(Wizard::BTN_PREV); ?>
    <?= $form->getElement(Wizard::BTN_NEXT)->setAttrib('class', 'install'); ?>
  </div>
</form>