<?php

use Icinga\Web\Wizard;

$radioElem = $form->getElement('user_type');
$showRadioBoxes = strpos(strtolower(get_class($radioElem)), 'radio') !== false;

?>
<form id="<?= $form->getName(); ?>" name="<?= $form->getName(); ?>" enctype="<?= $form->getEncType(); ?>" method="<?= $form->getMethod(); ?>">
  <?= $form->getElement('description'); ?>
<?php if (($byNameElem = $form->getElement('by_name')) !== null): ?>
  <div>
    <div style="display: inline-block; width: 30.2em;">
      <?= $byNameElem; ?>
    </div>
<?php if ($showRadioBoxes): ?>
    <div style="vertical-align: top; display: inline-block; padding: 0.4em 0.2em 0;">
      <label>
        <input type="radio" name="user_type" value="by_name">
        <?= $radioElem->getMultiOption('by_name'); ?>
      </label>
    </div>
<?php endif ?>
  </div>
<?php endif ?>
<?php if (($existingUserElem = $form->getElement('existing_user')) !== null): ?>
  <div>
    <div style="display: inline-block; width: 30.2em;">
      <?= $existingUserElem; ?>
    </div>
<?php if ($showRadioBoxes): ?>
    <div style="vertical-align: top; display: inline-block; padding: 0.4em 0.2em 0;">
      <label>
        <input type="radio" name="user_type" value="existing_user">
        <?= $radioElem->getMultiOption('existing_user'); ?>
      </label>
    </div>
<?php endif ?>
  </div>
<?php endif ?>
<?php if (($newUserElem = $form->getElement('new_user')) !== null): ?>
  <div>
    <div style="display: inline-block; width: 30.2em;">
      <?= $newUserElem; ?>
      <?= $form->getElement('new_user_password'); ?>
      <?= $form->getElement('new_user_2ndpass'); ?>
    </div>
<?php if ($showRadioBoxes): ?>
    <div style="vertical-align: top; display: inline-block; padding: 0.4em 0.2em 0;">
      <label>
        <input type="radio" name="user_type" value="new_user">
        <?= $radioElem->getMultiOption('new_user'); ?>
      </label>
    </div>
<?php endif ?>
  </div>
<?php endif ?>
<?php if (false === $showRadioBoxes): ?>
  <?= $radioElem; ?>
<?php endif ?>
  <?= $form->getElement($form->getTokenElementName()); ?>
  <?= $form->getElement($form->getUidElementName()); ?>
  <?= $form->getElement(Wizard::BTN_PREV); ?>
  <?= $form->getElement(Wizard::BTN_NEXT); ?>
</form>