<?php

use Icinga\Web\Wizard;

?>
<p><?= t(
  'The wizard is now complete. You can review the changes supposed to be made before issuing the actual installation'
  . ' of Icinga Web 2. Make sure that everything is correct (Feel free to navigate back to make any corrections!) so'
  . ' that you can start using Icinga Web 2 right after the installation has been finished.'
); ?></p>
<div class="summary">
<?php foreach ($form->getSummary() as $pageHtml): ?>
  <div class="page">
    <?= $pageHtml; ?>
  </div>
<?php endforeach ?>
</div>
<form id="<?= $form->getName(); ?>" name="<?= $form->getName(); ?>" enctype="<?= $form->getEncType(); ?>" method="<?= $form->getMethod(); ?>" action="<?= $form->getAction(); ?>">
  <?= $form->getElement($form->getTokenElementName()); ?>
  <?= $form->getElement($form->getUidElementName()); ?>
  <div class="buttons">
    <?= $form->getElement(Wizard::BTN_PREV); ?>
    <?= $form->getElement(Wizard::BTN_NEXT)->setAttrib('class', 'install'); ?>
  </div>
</form>