<?php
$rv = $this->runtimeVariables()->create($this->runtimevariables);
$cp = $this->checkPerformance()->create($this->checkperformance);

if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs ?>
</div>
<?php endif ?>

<div class="content processinfo">

    <div class="boxview">

        <div class="box left">
            <h3 class="tinystatesummary" data-base-target="_next">
                <?php $this->stats = $hoststats ?>
                <?= $this->render('list/components/hostssummary.phtml') ?>
            </h3>

            <table class="avp">
                <tbody>
                <tr>
                    <th> <?= $this->translate('Total') ?> </th>
                    <td> <?= $rv->total_scheduled_hosts ?> </td>
                </tr>
                <tr>
                    <th> <?= $this->translate('Scheduled') ?> </th>
                    <td> <?= $rv->total_scheduled_hosts ?> </td>
                </tr>
                </tbody>
            </table>

            <h3 class="tinystatesummary" data-base-target="_next">
                <?php $this->stats = $servicestats ?>
                <?= $this->render('list/components/servicesummary.phtml') ?>
            </h3>

            <table class="avp">
                <thead>
                <tr>
                    <th></th>
                    <th><?= $this->translate('Amount') ?></th>
                    <th><?= $this->translate('Per Host') ?></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <th> <?= $this->translate('Total') ?> </th>
                        <td> <?= $rv->total_services ?> </td>
                        <td> <?= sprintf('%.2f', $rv->average_services_per_host) ?> </td>
                        <td></td>
                    </tr>
                    <tr>
                        <th> <?= $this->translate('Scheduled') ?> </th>
                        <td> <?= $rv->total_scheduled_services ?> </td>
                        <td> <?= sprintf('%.2f', $rv->average_scheduled_services_per_host) ?> </td>
                        <td></td>
                    </tr>
                </tbody>
            </table>

            <h3><?= $this->translate('Active checks') ?></h3>
            <table class="avp">
                <thead>
                <tr>
                    <th></th>
                    <th><?= $this->translate('Checks') ?></th>
                    <th><?= $this->translate('Latency') ?></th>
                    <th><?= $this->translate('Execution time') ?></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th><?= $this->translate('Host Checks') ?></th>
                    <td><?= $cp->host_active_count; ?></td>
                    <td><?= sprintf('%.3f', $cp->host_active_latency_avg) ?>s</td>
                    <td><?= sprintf('%.3f', $cp->host_active_execution_avg) ?>s</td>
                </tr>
                <tr>
                    <th><?= $this->translate('Service Checks') ?></th>
                    <td><?= $cp->service_active_count; ?></td>
                    <td><?= sprintf('%.3f', $cp->service_active_latency_avg) ?>s</td>
                    <td><?= sprintf('%.3f', $cp->service_active_execution_avg) ?>s</td>
                </tr>
                </tbody>
            </table>

            <h3><?= $this->translate('Passive checks') ?></h3>
            <table class="avp">
                <tbody>
                <tr>
                    <th><?= $this->translate('Host Checks') ?></th>
                    <td><?= $cp->host_passive_count ?></td>
                </tr>
                <tr>
                    <th><?= $this->translate('Service Checks') ?></th>
                    <td><?= $cp->service_passive_count ?></td>
                </tr>
                </tbody>
            </table>
        </div>

    </div>
</div>
