<div id="installer">
  <div class="report">
  <?php $firstLine = true; ?>
  <?php foreach ($report as $entry): ?>
    <?php if ($entry !== ''): ?>
      <?php if (false === $firstLine): ?>
        <div class="line-separator"></div>
      <?php endif ?>
      <?= $entry; ?>
      <?php $firstLine = false; ?>
    <?php endif ?>
  <?php endforeach ?>
  <?php if ($success): ?>
    <p class="success"><?= t('Congratulations! The installation of Icinga Web 2 has been successfully completed.'); ?></p>
  <?php else: ?>
    <p class="failure"><?= t('Sorry! The installation of Icinga Web 2 has failed.'); ?></p>
  <?php endif ?>
  </div>
  <div class="buttons">
  <?php if ($success): ?>
    <a href="<?= $this->href('authentication/login'); ?>" class="button-like login"><?= t('Login to Icinga Web 2'); ?></a>
  <?php else: ?>
    <a href="<?= $this->href(); ?>" class="button-like"><?= t('Back'); ?></a>
  <?php endif ?>
  </div>
</div>