<?php

use Icinga\Web\Navigation\Navigation;

$navigation = new Navigation();

// add warning to links that open in new tabs to improve accessibility, as recommended by WCAG20 G201
$newTabInfo = sprintf('<span class="info-box display-on-hover"> %s </span>', $this->translate('opens in new window'));

foreach ($object->getActionUrls() as $i => $link) {
    $navigation->addItem(
        'Action ' . ($i + 1) . $newTabInfo,
        array(
            'url'       => $link,
            'target'    => '_blank'
        )
    );
}

if (isset($this->actions)) {
    foreach ($this->actions as $id => $action) {
        $navigation->addItem($id, array('url' => $action));
    }
}

if ($navigation->isEmpty()) {
    return;
}

?>
<tr>
    <th><?= $this->translate('Actions'); ?></th>
    <?= $navigation->getRenderer()->setElementTag('td'); ?>
</tr>