<?php if ($object->check_source !== null): ?>
<tr>
    <th>
        <?= $this->translate('Check Source') ?>
    </th>
    <td>
        <p>
            <?php if ($object->is_reachable !== null) {
                if ((bool) $object->is_reachable) {
                    echo $this->icon('circle', $this->translate('Is reachable'), array('class' => 'fg-color-ok'));
                } else {
                    echo $this->icon('circle', $this->translate('Not reachable'), array('class' => 'fg-color-critical'));
                }
            } ?>
            <?= $this->escape($object->check_source) ?>
        <?php if ($object->is_reachable !== null): ?>
            <span class="text-small"><?= (bool) $object->is_reachable ? $this->translate('is reachable') : $this->translate('is not reachable') ?></span>
        <?php endif ?>
        </p>
    </td>
</tr>
<?php endif ?>
