<?php if (isset($object->service_check_timeperiod_alias)): ?>

<tr>
    <th><?= $this->translate('Check Timeperiod') ?></th>
    <td>
        <?= $object->service_check_timeperiod_alias ?>
    </td>
</tr>

<?php endif; ?>

<?php if (isset($object->host_check_timeperiod_alias)): ?>

    <tr>
        <th><?= $this->translate('Check Timeperiod') ?></th>
        <td>
            <?= $object->host_check_timeperiod_alias ?>
        </td>
    </tr>

<?php endif; ?>
