<?php if ($object->check_source !== null): ?>
<tr>
    <th>
        <?= $this->translate('Check Source') ?>
    </th>
    <td>
        <?= $this->escape($object->check_source) ?>
    </td>
</tr>
<?php endif ?>
<?php if ($object->is_reachable !== null): ?>
<tr>
    <th>
        <?= $this->translate('Reachable') ?>
    </th>
    <td>
    <?php if ((bool) $object->is_reachable) {
        echo $this->icon('circle', $this->translate('Is reachable'), array('class' => 'fg-color-ok'));
    } else {
        echo $this->icon('circle', $this->translate('Not reachable'), array('class' => 'fg-color-critical'));
    } ?>
    </td>
</tr>
<?php endif ?>
