<?php

if (empty($object->comments)) return;

$list = array();
foreach ($object->comments as $comment) {
    if ($ticket_pattern) {
        $text = preg_replace(
            $ticket_pattern,
            $ticket_link,
            $this->escape($comment->comment_data)
        );
    } else {
        $text = $this->escape($comment->comment_data);
    }
    $list[] = sprintf(
        '[%s] %s (%s): %s',
        $this->escape($comment->comment_author),
        $this->format()->timeSince($comment->comment_timestamp),
        $comment->comment_type,
        $text
    );
}
?>
<b>Comments:</b><blockquote> <?= implode('<br />', $list) ?></blockquote>

