<div>
    <div class="panel-heading">
        <div class="panel-hostname">
            Custom Variables
        </div>
    </div>

    <hr class="separator" />

    <div class="panel-body">
        <?php if (empty($this->object->customvars)): ?>
        No customvars
        <?php else: ?>
        <dl class="dl-horizontal">
        <?php foreach ($this->object->customvars as $varname => $varvalue): ?>
            <dt><?= $varname; ?></dt>
            <dd><?= $varvalue; ?></dd>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
    </div>
</div>