<tr>
    <th><?= $this->translate('Downtimes') ?></th>
    <td>
        <?php

        /** @var \Icinga\Module\Monitoring\Object\MonitoredObject $object */

        if ($object->getType() === $object::TYPE_HOST) {
            $scheduleDowntimeLink = $this->href(
                'monitoring/host/schedule-downtime',
                array('host' => $object->getName())
            );
        } else {
            $scheduleDowntimeLink = $this->href(
                'monitoring/service/schedule-downtime',
                array('host' => $object->getHost()->getName(), 'service' => $object->getName())
            );
        }
        ?>
        <a href="<?= $scheduleDowntimeLink ?>">
            <?= $this->icon('in_downtime_petrol.png') ?> <?= $this->translate('Schedule downtime') ?>
        </a>
    </td>
</tr>

<?php

foreach ($object->downtimes as $downtime) {
    // Ticket hook sample
    $text = $this->tickets ? preg_replace_callback(
        $this->tickets->getPattern(),
        array($this->tickets, 'createLink'),
        $this->escape($downtime->comment)
    ) : $this->escape($downtime->comment);

    $form = clone $delDowntimeForm;
    $form->populate(array('downtime_id' => $downtime->id));

    if ((bool) $downtime->is_in_effect) {
        $state = 'in downtime since ' . $this->timeSince($downtime->start);
    } else {
        if ((bool) $downtime->is_fixed) {
            $state = 'scheduled ' . $this->timeUntil($downtime->start);
        } else {
            $state = 'scheduled flexible ' . $this->timeUntil($downtime->start);
        }
    }

    ?>

    <tr>
        <th><?= $this->escape($downtime->author) ?></th>
        <td>
            <table>
                <tr>
                    <td style="vertical-align: top;" data-base-target="_self">
                        <?= $form ?> <?= $state ?>
                    </td>
                    <td style="padding-left: .5em;">
                        <?= str_replace(array('\r\n', '\n'), '<br>', $text) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>

<?php }  // endforeach ?>
