<?php

$cf = $this->getHelper('CommandForm');

$data = array('host' => $object->host_name);
if ($object->service_description) {
    $data['service'] = $object->service_description;
}


$list = array();
foreach ($object->downtimes as $downtime) {
    $deleteData = $data;
    $deleteData['downtimeid'] = $downtime->id;

    // TODO: This needs improvement
    if ((int) $downtime->is_in_effect) {
        $state = 'in downtime since ' . $this->timeSince($downtime->start);
    } else {
        if ($downtime->is_fixed) {
            $state = 'scheduled ' . $this->timeUnless($downtime->start);
        } else {
            $state = 'scheduled flexible ' . $this->timeUnless($downtime->start);
        }
    }

    $iconForm = $cf->iconSubmitForm(
        'img/icons/remove_petrol.png',
        'Remove Downtime',
        'link-like',
        'removedowntime',
        $deleteData
    );

    $list[] = sprintf(
        "<br />%s [%s] (%s): %s\n",
        $iconForm,
        $this->escape($downtime->author),
        $state,
        $this->escape($downtime->comment)
    );
}

?>
<tr>
  <th><?= $this->translate('Downtimes') ?></th>
  <td>
    <a href="<?= $this->href('monitoring/command/scheduleDowntime', $data) ?>"><?= $this->icon('in_downtime_petrol.png') ?> <?= $this->translate('Schedule downtime') ?></a>
    <?= implode('', $list) ?>
  </td>
</tr>
