<?php

$o = $this->object;
$cf = $this->getHelper('CommandForm');

$data = array(
    'host'      => $o->host_name,
    'service'   => $o->service_description
);

?>
  <tr class="newsection">
    <th>Passive Checks</th>
    <td data-base-target="_self"><?= $cf->toggleSubmitForm(
        '',
        $o->passive_checks_enabled,
        'startacceptingpassivechecks',
        'stopacceptingpassivechecks',
        $o->passive_checks_enabled_changed === '1',
        $data
    ) ?></td>
  </tr>
  <tr>
    <th>Active Checks</th>
    <td data-base-target="_self"><?= $cf->toggleSubmitForm(
        '',
        $o->active_checks_enabled,
        'enableactivechecks',
        'disableactivechecks',
        $o->active_checks_enabled_changed === '1',
        $data
    ) ?></td>
  </tr>
  <tr>
    <th>Notifications</th>
    <td data-base-target="_self"><?= $cf->toggleSubmitForm(
        '',
        $o->notifications_enabled,
        'enablenotifications',
        'disablenotifications',
        $o->notifications_enabled_changed === '1',
        $data
    ) ?></td>
  </tr>
  <tr>
    <th>Event Handler</th>
    <td data-base-target="_self"><?= $cf->toggleSubmitForm(
        '',
        $o->event_handler_enabled,
        'enableeventhandler',
        'disableeventhandler',
        $o->event_handler_enabled_changed === '1',
        $data
    ) ?></td>
  </tr>
  <tr>
    <th>Flap Detection</th>
    <td data-base-target="_self"><?= $cf->toggleSubmitForm(
        '',
        $o->flap_detection_enabled,
        'enableflapdetection',
        'disableflapdetection',
        $o->flap_detection_enabled_changed === '1',
        $data
     ) ?></td>
  </tr>
  <tr>
    <th>Obsessing</th>
    <td data-base-target="_self"><?= $cf->toggleSubmitForm(
        '',
        $o->obsessing,
        'startobsessing',
        'stopobsessing',
        $o->obsessing_changed === '1',
        $data
    ) ?></td>
  </tr>
