<?php
$hostgroups = array();
foreach ($object->hostgroups as $name => $alias) {
    $hostgroups[] = '<a href="' . $this->href('monitoring/list/hosts', array('hostgroup' => $name)) . '">'
        . $alias
        . '</a>';
}
?>
<div>
    <div class="panel-heading">
        <div class="panel-hostname">
            Hostgroups
        </div>
    </div>

    <hr class="separator" />

    <div class="panel-body">
        <?php if (!count($hostgroups)): ?>
            No Hostgroups
        <?php else: ?>
            <?= implode(', ', $hostgroups); ?>
        <?php endif; ?>
    </div>
</div>
