<?php if (!empty($object->servicegroups)): ?>
<?php
$servicegroups = array();
foreach ($object->servicegroups as $name => $alias) {
    $servicegroups[] = '<a href="' . $this->href('monitoring/list/service', array('servicegroups' => $name)) . '">'
        . $alias
        . '</a>';
}
?>
<div class="panel panel-default">
    <div class="panel-heading">
        {{SERVICEGROUP_ICON}} <span>Servicegroups</span>
    </div>
    <div class="panel-body">
        <?= implode(', ', $servicegroups); ?>
    </div>
</div>
<?php endif; ?>
