<?php
$servicegroups = array();
foreach ($object->servicegroups as $name => $alias) {
    $servicegroups[] = '<a href="' . $this->href('monitoring/list/service', array('servicegroup' => $name)) . '">'
        . $alias
        . '</a>';
}
?>
<div>
    <div class="panel-heading">
        <div class="panel-hostname">
            Servicegroups
        </div>
    </div>

    <hr class="separator" />

    <div class="panel-body">
        <?php if (!count($servicegroups)): ?>
            No Servicegroups
        <?php else: ?>
            <?= implode(', ', $servicegroups); ?>
        <?php endif; ?>
    </div>
</div>
