<div class="controls">
  <h1><?= $docName ?> documentation</h1>
</div>
<div class="content" data-base-target="_next">
  <?php
    $urlHelper = $this->getHelper('Url');
    $view = $this;
  ?>
  <?= $tocRenderer->render(function ($section) use ($urlHelper, $view, $moduleName) {
    // Chapter name is not yet defined
    $path = $urlHelper->url(
      array('moduleName' => $moduleName, 'chapterName' => 'tbd'), 'doc/module/chapter', false, false
    );
    $url = $view->url($path)->setAnchor($section->id);
    return sprintf('<li><a href="%s">%s</a></li>', $url->getAbsoluteUrl(), $section->title);
  }); ?>
</div>
