<div class="controls">
    <?= $tabs ?>
</div>
<div class="content">
    <?= $this->qlink(
        $this->translate('Create a New User Backend') ,
        'config/createuserbackend',
        null,
        array(
            'class'             => 'button-link',
            'data-base-target'  => '_next',
            'icon'              => 'plus',
            'title'             => $this->translate('Create a new user backend')
        )
    ) ?>
    <?= $form ?>
</div>
