<div class="controls">
    <?= $tabs ?>
</div>
<div class="content" data-base-target="_next">
    <?= $this->qlink(
        $this->translate('Create A New User Backend') ,
        'config/createuserbackend',
        null,
        array(
            'class'   => 'button action-link',
            'icon'    => 'plus',
            'title'   => $this->translate('Create a new user backend')
        )
    ) ?>
    <?= $form ?>
</div>
