<div class="controls" data-base-target="_main">
  <?= $tabs; ?>
</div>
<div class="content" data-base-target="_next">
  <h1 tabindex="0" id="authentication-reorder">
    <?= t('Authentication Configuration'); ?>
  </h1>
  <div class="skip-links skip-links-inline">
    <nav>
      <ul>
        <li>
          <a tabindex="0" href="#authentication-reorder-form">
            <?= t('Skip To Authentication Reorder Form'); ?>
          </a>
        </li>
      </ul>
    </nav>
  </div>
  <h2 tabindex="0" id="authentication-new-backend" class="sr-only">
    <?= t('New Authentication Backend'); ?>
  </h2>
  <p>
    <a href="<?= $this->href('/config/createAuthenticationBackend'); ?>">
      <?= $this->icon('plus'); ?><?= $this->translate('Create A New Authentication Backend'); ?>
    </a>
  </p>
  <h2 tabindex="0" id="authentication-reorder" class="sr-only">
    <?= t('Reorder Authentication Backends'); ?>
  </h2>
  <div id="authentication-reorder-form">
    <?= $form; ?>
  </div>
</div>
