 <div id="login">
  <div class="logo">
   <div class="image">
    <img src="<?= $this->baseUrl('img/logo_icinga_big.png') ?>" >
   </div>
  </div>
  <div class="form" data-base-target="layout">
   <h1><?= $this->translate('Icingaweb Login') ?></h1>
   <?php
   /* TODO: remove this as soon as notifications and forms are ready */
   if (isset($this->errorInfo)): ?>
    <div class="error">
    <?= $this->errorInfo ?>
    </div>
   <?php endif ?>
   <?= $this->form ?>
   <div class="footer">Icinga Web 2 &copy; 2013-2014 Icinga Team</div>
  </div>
 </div>
