<!--
    This view provides a workaround to logout from an external authentication provider, in case external
    authentication was configured (the default is to handle authentications internally in Icingaweb2).

    The <a href="http://tools.ietf.org/html/rfc2617">Http Basic and Digest Authentication</a> is not
    designed to handle logout. When the user has provided valid credentials, the client is adviced to include these
    in every further request until the browser was closed. To allow logout and to allow the user to change the
    logged-in user this JavaScript provides a workaround to force a new authentication prompt in most browsers.
-->

<div class="row">
  <br/>
  <div class="md-offset-3 col-md-6 col-sm-6 col-sm-offset-3">
    <div class="alert alert-warning" id="logout-status">
        <b> <?= t('Logging out...'); ?> </b> <br />
        <?= t(
            'If this message does not disappear, it might be necessary to quit the ' .
            'current session manually by clearing the cache, or by closing the current ' .
            'browser session.'
        ); ?>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
    <div class="container" >
        <a class="button btn btn-cta form-control input-sm" href="<?= $this->href('dashboard/index'); ?>"> <?= t('Login'); ?></a>
    </div>
  </div>
</div>

<script type="text/javascript">

    /**
     * When JavaScript is available, trigger an XmlHTTPRequest with the non-existing user 'logout' and abort it
     * before it is able to finish. This will cause the browser to show a new authentication prompt in the next
     * request.
     */
    window.onload = function () {
        function getXMLHttpRequest() {
            var xmlhttp = null;
            try {
                if (window.XMLHttpRequest) {
                    xmlhttp = new XMLHttpRequest();
                } else if (window.ActiveXObject) {
                    xmlhttp = new ActiveXObject('Microsoft.XMLHTTP');
                }
            } catch (e) {}
            return xmlhttp;
        }
        var msg = document.getElementById('logout-status');
        try {
            if (navigator.userAgent.toLowerCase().indexOf('msie') !== -1) {
                document.execCommand('ClearAuthenticationCache');
            } else {
                var xhttp = getXMLHttpRequest();
                xhttp.open('GET', 'arbitrary url', true, 'logout', 'logout');
                xhttp.send('');
                xhttp.abort();
            }
        } catch (e) {
            msg.innerHTML = '<?= t(
                'Logout not possible, it may be necessary to quit the session manually ' .
                'by clearing the cache, or closing the current browser session. Error: '
            );?>' + ': ' + e.getMessage() ;
            msg.setAttribute('class', 'alert alert-danger');
        }
        msg.innerHTML = '<?= t('Logout successful!'); ?>';
        msg.setAttribute('class', 'alert alert-success');
    };
</script>
