<div class="controls">
  <?php if ($object->getType() === $object::TYPE_HOST): ?>
    <?= $this->render('partials/host/object-header.phtml'); ?>
    <?= $this->render('partials/host/servicesummary.phtml'); ?>
  <?php else: ?>
    <?= $this->render('partials/service/object-header.phtml'); ?>
    <hr class="command-separator">
  <?php endif ?>
</div>
<div class="content object-command">
    <?= $form; ?>
</div>