<?php use Icinga\Data\Filter\Filter; ?>

<div class="controls">

   <?php if (! $this->compact): ?>
       <?= $tabs; ?>
   <?php endif ?>

  <?php if (isset($serviceStates)): ?>
    <h2 class="tinystatesummary" <?= $this->compact ? ' data-base-target="col1"' : ''; ?>
    <?= $this->render('list/components/servicesummary.phtml'); ?>
    </h2>
    <?= $this->render('partials/service/objects-header.phtml'); ?>
  <?php else: ?>
    <h2 class="tinystatesummary" <?= $this->compact ? ' data-base-target="col1"' : ''; ?>
      <?= $this->render('list/components/hostssummary.phtml') ?>
    </h2>
    <?= $this->render('partials/host/objects-header.phtml'); ?>
  <?php endif ?>
</div>

<div class="content objects-command">
    <hr class="command-separator">
    <?= $form; ?>
</div>
