<?php use Icinga\Data\Filter\Filter; ?>

<div class="controls">
  <?php if (! $this->compact): ?>
    <?= $this->tabs; ?>
  <?php endif ?>
  <?php if ($object->getType() === $object::TYPE_HOST): ?>
    <?= $this->render('partials/host/object-header.phtml'); ?>
    <?php
    $this->baseFilter = Filter::where('host', $object->host_name);
    $this->stats = $object->stats;
    echo $this->render('list/components/servicesummary.phtml');
    ?>
  <?php else: ?>
    <?= $this->render('partials/service/object-header.phtml'); ?>
    <hr class="command-separator">
  <?php endif ?>
</div>
<div class="content object-command">
    <?= $form; ?>
</div>
