<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <i class="icon-cancel" aria-hidden="true"></i>
        </button>
    </div>
    <div class="modal-body">
        <nav class="primary-nav">
            <ul class="nav nav-level-1">
                <li class="nav-item">
                    <i class="icon-database"></i>
                    <span class="label">Monitoring</span>
                </li>
                <li class="nav-item">
                    <i class="icon-database"></i>
                    <span class="label">Monitoring</span>
                </li>
            </ul>
        </nav>
        <div class="content">
            <p>Woohoo, you're reading this text in a modal!</p>
        </div>
    </div>
    <div class="modal-footer">
        <div class="left">
            <input type="search">
        </div>
        <div class="right">
            <button type="button" class="btn btn-secondary close" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
        </div>
    </div>
</div>
