<div class="controls">
    <?php if (! $this->compact): ?>
        <?= $this->tabs ?>
    <?php endif ?>
</div>

<?php if ($this->tabeleView): ?>
    <?php if ($this->dashlets !== null): ?>
        <div class="content">
            <?= $this->dashlets ?>
        </div>
    <?php else: ?>
        <div class="content">
            <h1><?= $this->translate('Thank you for using Icinga Web 2!'); ?></h1>
            <p><?= $this->escape($this->translate(sprintf('Currently there is no %s on your Icinga infrastructure.', $this->tabs->getActiveName()))); ?></p>
        </div>
    <?php endif; ?>
<?php elseif ($this->dashboard): ?>
    <?php if ($this->dashboard->hasPanes()): ?>
        <?php if ($this->dashboard->getPane($this->tabs->getActiveName())->hasDashlets()): ?>
            <div class="dashboard content">
            <?= $this->dashboard ?>
            </div>
        <?php else: ?>
            <h1><?= $this->translate('Thank you for using Icinga Web 2!') ?></h1>
            <?= $this->translate('No dashlets added to dashboard.'); ?>
        <?php endif; ?>
    <?php else: ?>
        <h1><?= $this->translate('Thank you for using Icinga Web 2!'); ?></h1>
        <p><?= $this->translate('Currently there is no available dashboards in this home.'); ?><p>
    <?php endif; ?>
<?php endif; ?>
