<div class="controls">
<?= $this->tabs ?>
</div>
<?php if ($this->dashboard): ?>
    <div class="dashboard content">
    <?= $this->dashboard ?>
    </div>
<?php else: ?>
    <div class="content">
        <h1><?= $this->escape($this->translate('Welcome to Icinga Web!')) ?></h1>
        <p><?= sprintf(
             $this->escape($this->translate('Currently there is no dashlet available. This might change once you enabled some of the available %s.')),
            $this->qlink($this->translate('modules'), 'config/modules')
        ) ?></p>
    </div>
<?php endif ?>