<?php
use Icinga\Web\Url;

$this->modules->limit(10);
$modules = $this->modules->paginate();

?>
<div>
<?= $this->tabs->render($this); ?>
</div>

<div>
<h3>Installed Modules</h3>

<?php if (isset($this->messageBox)): ?>
  <?= $this->messageBox->render() ?>
<?php endif ?>

<?= $this->paginationControl($modules, null, null, array(
    'preserve' => $this->preserve
));
?>
<table>
  <tbody>
  <? foreach ($modules as $module): ?>
    <?php
    $enableUrl = Url::fromPath('config/moduleenable/',array('name' => $module->name))->getAbsoluteUrl();
    $disableUrl = Url::fromPath('config/moduledisable/',array('name' => $module->name))->getAbsoluteUrl();
    ?>
    <tr>
      <td>
      <? if ($module->enabled): ?>
        <i class="icinga-icon-success"></i>
        <a href="<?= $disableUrl ?>" data-icinga-target="main"><?= $this->escape($module->name); ?></a>
      <? else: ?>
        <i class="icinga-icon-remove"></i>
        <a href="<?= $enableUrl ?>" data-icinga-target="main"><?= $this->escape($module->name); ?></a>
      <? endif ?>
      (<?=
        $module->enabled ? ($module->loaded ? 'enabled' : 'failed') : 'disabled' ?>)
      </td>
    </tr>
  <? endforeach ?>
  </tbody>
</table>
</div>
