<table>
  <thead>
    <tr style="text-align:left">
      <th width="70%">Module</th>
      <th width="15%">Type</th>
      <th width="15%">Active</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach($this->modules as $module): ?>
    <tr>
      <td><?= $module["name"]; ?></td>
      <td><?= $module["type"]; ?></td>
      <td><?= $module["active"]; ?></td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
