<h4>
    <i class="icinga-icon-edit"></i>
    Edit Resource "<?= $this->escape($this->name); ?>"
</h4>

<?php if ($this->errorMessage || $this->form->getErrorMessages()): ?>
<div class="alert alert-danger">
  <?= $this->escape($this->errorMessage); ?>
  <?php foreach ($this->form->getErrorMessages() as $error): ?>
  <?= $this->escape($error); ?><br/>
  <?php endforeach; ?>
</div>
<?php endif; ?>

<?= $this->form ?>