<?= $this->tabs->render($this); ?>

<?php if (isset($this->name)): ?>
    <h4>{{EDIT_ICON}} Edit Instance Configuration for "<?= $this->escape($this->name) ?>"</h4>
<?php else: ?>
    <h4>{{CREATE_ICON}} Configure New Icinga Instance</h4>
<?php endif; ?>

<?php if ($this->error): ?>
    <div class="alert alert-danger">
        <?= $this->escape($this->error); ?>
    </div>
<?php endif; ?>

<?= $this->form; ?>