<div class="controls">
  <?= $tabs; ?>
  <h1><?= $this->translate('Monitoring Backends') ?></h1>
</div>

<div class="content" data-base-target="_next">
  <p>
    <a href="<?= $this->href('/monitoring/config/createbackend'); ?>">
      <?= $this->icon('plus'); ?> <?= $this->translate('Create New Monitoring Backend'); ?>
    </a>
  </p>
  <table class="action">
    <thead>
      <th><?= $this->translate('Monitoring Backend'); ?></th>
      <th style="width: 5em"><?= $this->translate('Remove'); ?></th>
    </thead>
    <tbody>
    <?php foreach ($this->backendsConfig as $backendName => $config): ?>
      <tr>
        <td>
          <?= $this->qlink(
            $backendName,
            '/monitoring/config/editbackend',
            array('backend' => $backendName),
            array(
                'icon'  => 'edit',
                'title' => sprintf($this->translate('Edit monitoring backend %s'), $backendName)
            )
          ); ?>
          <small>(<?= sprintf(
            $this->translate('Type: %s'),
            $this->escape($config->type === 'ido' ? 'IDO' : ucfirst($config->type))
          ); ?>)</small>
        </td>
        <td>
          <?= $this->qlink(
            '',
            '/monitoring/config/removebackend',
            array('backend' => $backendName),
            array(
                'icon'  => 'trash',
                'title' => sprintf($this->translate('Remove monitoring backend %s'), $backendName)
            )
          ); ?>
        </td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>
  <h1><?= $this->translate('Monitoring Instances') ?></h1>
  <p>
    <a href="<?= $this->href('/monitoring/config/createinstance'); ?>">
      <?= $this->icon('plus'); ?> <?= $this->translate('Create New Instance'); ?>
    </a>
  </p>
  <table class="action">
    <thead>
      <th><?= $this->translate('Instance'); ?></th>
      <th style="width: 5em"><?= $this->translate('Remove'); ?></th>
    </thead>
    <tbody>
    <?php foreach ($this->instancesConfig as $instanceName => $config): ?>
      <tr>
        <td>
          <?= $this->qlink(
            $instanceName,
            '/monitoring/config/editinstance',
            array('instance' => $instanceName),
            array(
                'icon'  => 'edit',
                'title' => sprintf($this->translate('Edit monitoring instance %s'), $instanceName)
            )
          ); ?>
          <small>(<?= sprintf(
            $this->translate('Type: %s'),
            $config->host !== null ? $this->translate('Remote') : $this->translate('Local')
          ); ?>)</small>
        </td>
        <td>
          <?= $this->qlink(
            '',
            '/monitoring/config/removeinstance',
            array('instance' => $instanceName),
            array(
                'icon'  => 'trash',
                'title' => sprintf($this->translate('Remove monitoring instance %s'), $instanceName)
            )
          ); ?>
        </td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>
</div>
