<?php use Icinga\Web\Url;  ?>
<?= $this->tabs->render($this); ?>

<h3>Backends</h3>

<div>
  <a href="<?= Url::fromPath('/monitoring/config/createbackend')->getAbsoluteUrl();?>">
      Create New Backend
  </a>
</div>
<br/>

<?php foreach ($this->backends as $backendName => $config): ?>
<div>
  <?php $removeUrl = Url::fromPath('/monitoring/config/removebackend', array('backend' => $backendName)); ?>
  <?php $editUrl = Url::fromPath('/monitoring/config/editbackend', array('backend' => $backendName)); ?>
  <b><?= $this->escape($backendName); ?></b>
  <small>(Type: <?= $this->escape($config['type']); ?>)</small>
  <?php if ($config['disabled']): ?>
    - <b>Disabled</b>
  <?php endif; ?>
  <div>
    <a href="<?= $removeUrl; ?>">Remove This Backend</a><br/>
    <a href="<?= $editUrl; ?>">Edit This Backend</a>
  </div>
</div>
<br/>
<?php endforeach; ?>

<br/>

<h3>Monitoring Instances</h3>

<div>
  <a href="<?= Url::fromPath('/monitoring/config/createinstance')->getAbsoluteUrl();?>">
      Create New Instance
  </a>
</div>

<br/>
<?php foreach ($this->instances as $instanceName => $config): ?>
  <?php $removeUrl = Url::fromPath('/monitoring/config/removeinstance', array('instance' => $instanceName)); ?>
  <?php $editUrl = Url::fromPath('/monitoring/config/editinstance', array('instance' => $instanceName)); ?>
<div>
  <b><?= $this->escape($instanceName); ?></b>
  <small>(Type: <?= isset($config['host']) ? 'Remote' : 'Local'; ?>)</small>

  <div>
    <a href="<?= $removeUrl; ?>">Remove This Instance</a><br/>
    <a href="<?= $editUrl; ?>">Edit This Instance</a>
  </div>
</div>
<br/>
<?php endforeach; ?>

