<div class="alert alert-error">
    <h4><i><i class="icinga-icon-error"></i> </i> Saving &quot;<?= $this->escape($this->file); ?>&quot; failed</h4>
    <br/>
    <p>
        Your <?= $this->escape($this->file); ?> configuration couldn't be stored (error: "<?= $this->exceptionMessage; ?>").<br/>
        This could have one or more of the following reasons:
    </p>
    <ul>
        <li>You don't have file-system permissions to write to the <?= $this->escape($this->file); ?> file</li>
        <li>Something went wrong while writing the file</li>
        <li>There's an application error preventing you from persisting the configuration</li>
    </ul>
</div>

<p>
    Details can be seen in your application log (if you don't have access to this file, call your administrator in this case).
    <br/>
    In case you can access the configuration file (config/<?= $this->escape($this->file); ?>) by yourself, you can open it and
    insert the config manually:

</p>
<p>
<pre>
        <code>
<?= $this->escape($this->iniConfigurationString); ?>
        </code>
    </pre>
</p>