<?php if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs; ?>
</div>
<?php endif ?>
<div class="content" data-base-target="_next">
<?php if ($items->isEmpty()): ?>
    <?= $this->translate('There are currently no navigation items being shared'); ?>
<?php else: ?>
    <table class="action alternating">
        <thead>
            <th><?= $this->translate('Shared Navigation'); ?></th>
            <th style="width: 10em"><?= $this->translate('Owner'); ?></th>
            <th style="width: 5em"><?= $this->translate('Unshare'); ?></th>
        </thead>
        <tbody>
        <?php foreach ($items as $name => $item): ?>
            <tr>
                <td><?= $this->qlink(
                    $name,
                    'navigation/edit',
                    array('name' => $name),
                    array(
                        'title' => sprintf($this->translate('Edit shared navigation item %s'), $name)
                    )
                ); ?></td>
                <td><?= $this->escape($item->owner); ?></td>
                <td data-base-target="_self"><?= $removeForm->setDefault('name', $name); ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
</div>