<div class="controls">
    <?= $this->tabs->render($this) ?>
    <div style="margin-top: 1em"></div>
    <?=  $this->logData ?>
</div>

<div class="content">
    <table class="action">
        <tbody>
            <?php foreach ($this->logData as $value): ?>
                <?php $datetime = new Datetime($value->datetime); ?>
                <tr class="state">
                    <td style="width: 6em; text-align: center">
                        <?= $this->escape($datetime->format('d.m. H:i')) ?><br />
                        <?= $this->escape($value->loglevel) ?>
                    </td>
                    <td>
                        <?= $this->escape($value->message) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>