<div class="controls">
<?= $this->tabs ?>
<div style="margin: 1em">
<?=  $this->sortControl->render($this); ?>
</div>
<?=  $this->paginationControl($comments, null, null, array('preserve' => $this->preserve)); ?>
</div>

<div class="content">
<table class="action comments">
<tbody>
<?php

$cf = $this->getHelper('CommandForm');

foreach ($comments as $comment):

    $objectType = (int) $comment->comment_objecttype_id === 1 ? 'host' : 'service';

?>
<tr>
  <td style="width: 5em; text-align: center;">
    <?php
    switch ($comment->comment_type) {
        case 'flapping':
            $icon = 'flapping';
            $tooltip = 'Comment was caused by a flapping host or service.';
            break;
        case 'comment':
            $icon = 'user';
            $tooltip = 'Comment was created by an user.';
            break;
        case 'downtime':
            $icon = 'down';
            $tooltip = 'Comment was caused by a downtime.';
        case 'ack':
            $icon = 'acknowledgement';
            $tooltip = 'Comment was caused by an acknowledgement.';
    }
    ?>
    <?= $this->icon($icon . '.png', $tooltip) ?><br />
    <?= $this->timeSince($comment->comment_timestamp) ?>
    </td>
    <td>
    <?php if ($objectType === 'service'): ?><?= $this->icon('service.png', 'Service comment') ?> <?= $this->qlink(
        $comment->service_name,
        'monitoring/show/service',
        array(
            'host'    => $comment->host_name,
            'service' => $comment->service_name,
        )
    ) ?> on<?php else: ?><?= $this->icon('host.png', 'Host comment') ?> <?php endif ?> <?= $this->qlink(
        $comment->host_name,
        'monitoring/show/host',
        array(
            'host'    => $comment->host_name
        )
    ) ?> by <strong><?= $this->escape($comment->comment_author) ?></strong><br />
      <p><?= $this->escape($comment->comment_data) ?></p>
        <?php if ($comment->comment_is_persistent): ?>Comment is persistent<br /><?php endif ?>
        <b>Expires: </b> <?=
            ($comment->comment_expiration_timestamp) ?
                $this->timeUnless($comment->comment_expiration_timestamp) :
                'Never'
        ?>
    </td>
    <td style="width: 2em">
<?php

    $data = array(
      'commentid' => $comment->comment_id,
      'host'      => $comment->host_name
    );

    if ($objectType === 'service') {
        $data['service'] = $comment->service_name;
    }

    echo $cf->iconSubmitForm(
        'img/icons/remove.png',
        'Remove comment',
        'link-like',
        'removecomment',
        $data
    );

?>
    </td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

</div>
