<?php if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <div class="dontprint">
     <?= $this->render('list/components/selectioninfo.phtml'); ?>
  </div>
  <div class="tinystatesummary">
     <?= count($comments) ?> <?= $this->translate('Comments') ?>:
  </div>
  <?= $this->sortBox; ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content">
<?php

if (count($comments) === 0) {
    echo $this->translate('No comments found matching the filter') . '</div>';
    return;
}
?>
  <table data-base-target="_next"
         class="action comments multiselect"
         data-icinga-multiselect-url="/icingaweb2/monitoring/comments/show"
         data-icinga-multiselect-data="comment_id">
    <tbody>
    <?php foreach ($comments as $comment):
        $this->comment = $comment; ?>

      <tr class="state invalid">
        <td class="state" style="width: 12em;">
          <?= $this->render('partials/comment/comment-description.phtml'); ?>
        </td>
        <td>
        <?php if ($comment->objecttype === 'service'): ?>
          <?= $this->icon('service', $this->translate('Service')); ?>

          <?= $this->qlink(
            sprintf(
                $this->translate('%s on %s', 'Service running on host'),
                $comment->service_display_name,
                $comment->host_display_name
            ),
            'monitoring/comment/show',
            array('comment_id' => $comment->id),
            array('title' => sprintf(
                $this->translate('Show detailed information for comment on %s for %s'),
                $comment->service_display_name,
                $comment->host_display_name
          ))) ?>
        <?php else: ?>
          <?= $this->icon('host', $this->translate('Host')); ?>

          <?= $this->qlink(
            $comment->host_display_name,
            'monitoring/comment/show',
            array('comment_id' => $comment->id),
            array('title' => sprintf(
                $this->translate('Show detailed information for comment on %s'),
                $comment->host_display_name
          ))) ?>
        <?php endif ?>
          <br>
          <?= $this->icon('comment', $this->translate('Comment')); ?> <?= isset($comment->author)
            ? '[' . $this->escape($comment->author) . '] '
            : '';
          ?><?= $this->escape($comment->comment); ?>
          <br>
          <?= $comment->persistent
            ? $this->translate('This comment is persistent.')
            : $this->translate('This comment is not persistent.');
          ?>
          <br>
          <?= $comment->expiration ? sprintf(
              $this->translate('This comment expires %s.'),
              $this->timeUntil($comment->expiration)
          ) : $this->translate('This comment does not expire.'); ?>
        </td>
        <?php if (isset($delCommentForm)): // Form is unset if the current user lacks the respective permission ?>
        <td style="width: 2em" data-base-target="self">
          <?php
          $delCommentForm = clone $delCommentForm;
          $delCommentForm->populate(
              array(
                  'comment_id' => $comment->id,
                  'comment_is_service' => isset($comment->service_description)
              )
          );
          echo $delCommentForm;
          ?>
        </td>
        <?php endif ?>
      </tr>
<?php endforeach ?>
    </tbody>
  </table>
</div>
