<?php
$viewHelper = $this->getHelper('MonitoringState');
$contactHelper = $this->getHelper('ContactFlags');
?>
<div class="controls">
    <?= $this->tabs ?>
    <div style="margin: 1em">
        <?= $this->sortControl->render($this); ?>
    </div>
    <?= $this->paginationControl($contacts, null, null, array('preserve' => $this->preserve)); ?>
</div>

<div data-base-target="_next" class="content contacts">
    <?php
    if (count($contacts) === 0) {
        echo t('No contacts matching the filter');
    }
    foreach ($contacts as $contact):
        $periodLink = $this->href('monitoring/show/contacts', array('contact' => $contact->contact_name)); ?>
        <div style="background-color: lightgray; padding: 0.5em; border-radius: 0.5em; overflow: hidden; margin: 0.125em; float: left;">
            <img src="<?= $this->href('/static/gravatar', array('email' => $contact->contact_email )) ?>"
                 style="width: 60px; border: 4px solid white; border-radius: 8px; margin-right: 8px; float: left;" />
            <a href="<?= $this->href(
                'monitoring/show/contact',
                array('contact' => $contact->contact_name)
            ) ?>"><strong><?= $contact->contact_name ?></strong></a> (<?= $contact->contact_alias ?>)
            <?php
            foreach (array(
                'eMail: <a href="mailto:%1$s">%1$s</a>' => $contact->contact_email,
                'Pager: %s'                             => $contact->contact_pager,
                'Service notification period: %s'       => $contact->contact_notify_service_timeperiod,
                'Host notification period: %s'          => $contact->contact_notify_host_timeperiod
            ) as $format => $value):
                if ($value): ?>
                    <br />
                    <?php
                    printf($format, htmlspecialchars($value));
                endif;
            endforeach;
            ?>
            <div class="clearfix"></div>
        </div>
    <?php endforeach; ?>
</div>
