<?php if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <?= $this->sortBox; ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div data-base-target="_next" class="content contacts">
<?php

if (count($contacts) === 0) {
    echo $this->translate('No contacts found matching the filter') . '</div>';
    return;
}
?>
<?php foreach ($contacts as $contact): ?>
        <div class="contact">
            <?= $this->img('/static/gravatar', array('email' => $contact->contact_email)); ?>
            <strong><?= $this->qlink(
                $contact->contact_name,
                'monitoring/show/contact',
                array('contact_name' => $contact->contact_name),
                array('title' => sprintf(
                    $this->translate('Show detailed information about %s'),
                    $contact->contact_alias
                ))
            ); ?></strong> (<?= $contact->contact_alias; ?>)
            <div>
                <?= $this->translate('Email'); ?>: <a href="mailto:<?= $contact->contact_email; ?>" title="<?= sprintf($this->translate('Send a mail to %s'), $contact->contact_alias); ?>" aria-label="<?= sprintf($this->translate('Send a mail to %s'), $contact->contact_alias); ?>">
                    <?= $this->escape($contact->contact_email); ?>
                </a>
            </div>
            <?php if ($contact->contact_pager): ?>
            <div>
                <?= $this->translate('Pager') ?>:
                <?= $this->escape($contact->contact_pager) ?>
            </div>
            <?php endif; ?>
            <div style="clear: both;"></div>
            <div class="notification-periods">
                <?php if ($contact->contact_notify_service_timeperiod): ?>
                <div>
                    <?= $this->translate('Service notification period') ?>:
                    <?= $this->escape($contact->contact_notify_service_timeperiod) ?>
                </div>
                <?php endif; ?>
                <?php if ($contact->contact_notify_host_timeperiod): ?>
                <div>
                    <?= $this->translate('Host notification period') ?>:
                    <?= $this->escape($contact->contact_notify_host_timeperiod) ?>
                </div>
                <?php endif; ?>
            </div>
        </div>
    <?php
    endforeach;
    if (true): /* The following piece of HTML MUST be nested in <?php */ ?>
    <div style="clear: both;"></div>
    <?php endif; ?>
</div>
