<?php

if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs ?>
    <div class="grid">
        <?= $this->sortBox ?>
        <?= $this->limiter ?>
        <?= $this->filterEditor ?>
    </div>
</div>
<?php endif ?>
<?= $this->partial(
    'partials/event-history.phtml',
    array('compact' => $this->compact, 'history' => $history, 'isOverview' => true, 'tableCssClass' => 'table-row-selectable')
) ?>

