<?php

$viewHelper = $this->getHelper('MonitoringState');
?>
<div class="controls">
<?= $this->tabs ?>
<?= $this->filterBox->render($this); ?>
<?= $this->sortControl->render($this); ?><br />
<?= $this->paginationControl($hosts, null, null, array('preserve' => $this->preserve)); ?>
<?= $this->selectionToolbar('multi', $this->href('monitoring/multi/host',array( 'host' => '*' ))); ?>
</div>
<div class="content">
<?php
if ($hosts->count() === 0) {
    echo '<p>No host found</p>';
    return;
}
?>

<table class="action multiselect">
    <tbody>
    <?php foreach($hosts as $host): ?>
      <?php $hostStateName = strtolower($this->util()->getHostStateName($host->host_state)); ?>
      <?php $hostLink = $this->href('monitoring/show/host', array('host' => $host->host_name)); ?>
      <!--<tr> -->
       <tr class="state <?= $hostStateName ?><?= $host->host_handled ? ' handled' : '' ?>">
        <!-- Color column -->
<!--        <td class="tacheader-status-<?= $hostStateName; ?>">
          <a style="visibility:hidden" href="<?= $hostLink; ?>"></a>
        </td>
-->
        <!-- Icons -->
<!--        <td>
          <?php if (!$host->host_handled && $host->host_state > 0): ?>
          <a href="#" title="Unhandled">
            <i class="icon-table icinga-icon-unhandled"></i>
          </a>
          <?php endif; ?>

          <?php if ($host->host_acknowledged && !$host->host_in_downtime): ?>
          <a href="#" title="Acknowledged">
            <i class="icon-table icinga-icon-acknowledgement"></i>
          </a>
          <?php endif; ?>

          <?php if ($host->host_is_flapping): ?>
          <a href="#" title="Flapping">
              <i class="icon-table icinga-icon-flapping"></i>
          </a>
          <?php endif; ?>

          <?php if (!$host->host_notifications_enabled): ?>
          <a href="#" title="Notifications Disabled">
              <i class="icon-table icinga-icon-notification-disabled"></i>
          </a>
          <?php endif; ?>

          <?php if ($host->host_in_downtime): ?>
          <a href="#" title="In Downtime">
              <i class="icon-table icinga-icon-in-downtime"></i>
          </a>
          <?php endif; ?>

          <?php if (!$host->host_active_checks_enabled): ?>
            <?php if (!$host->host_passive_checks_enabled): ?>
              <a href="#" title="Active And Passive Checks Disabled">
               <i class="icinga-icon-active-passive-checks-disabled"></i>
              </a>
            <?php else: ?>
              <a href="#" title="Active Checks Disabled">
                  <i class="icon-table icinga-icon-active-checks-disabled"></i>
              </a>
            <?php endif; ?>
          <?php endif; ?>

          <?php if (isset($host->host_last_comment) && $host->host_last_comment !== null): ?>
          <a href="#" title="Comments">
              <i class="icon-table icinga-icon-comment"></i>
          </a>
          <?php endif; ?>
        </td>
-->
        <!-- State -->
        <td class="state" title="<?= $viewHelper->getStateTitle($host, 'host'); ?>">
          <div>
            <?php if (isset($host->host_unhandled_service_count) && $host->host_unhandled_service_count > 0): ?>
              <span class="badge pull-right" title="<?= $host->host_unhandled_service_count; ?> Service Problems on Host">
              <a data-icinga-target="detail" href="<?= $this->href('monitoring/list/services', array('host' => $host->host_name, 'service_problem' => 1)); ?>">
                <?= $host->host_unhandled_service_count; ?>
              </a>
            </span>
            <?php endif; ?>

            <strong><?= ucfirst($viewHelper->monitoringState($host, 'host')); ?></strong><br />
            <div class="small-row">
            Since <?= $this->timeSince($host->host_last_state_change); ?>
            <?php if ($host->host_state > 0): ?>
              <br />
              <strong><?= ($host->host_state_type === '1') ? 'Hard' : 'Soft'; ?> </strong> <?= $host->host_current_check_attempt; ?>/<?= $host->host_max_check_attempts; ?>
            <?php endif; ?>
            </div>
          </div>
        </td>

        <!-- Host / Status / Output -->
        <td>
          <?php if ($host->host_icon_image) : ?>
            <div class="pull-left" style="margin-right: 2px;">
              <i class="inline-image" style="background-image: url(<?= $this->escape($this->resolveMacros($host->host_icon_image, $host)); ?>);"></i>
            </div>
          <?php endif; ?>
          <a href="<?= $this->href('monitoring/list/services', array('host' => $host->host_name)) ?>">
            <strong><?= $host->host_name ?></strong>
          </a>

          <div class="output-text">
            <?= $this->escape(substr(strip_tags($host->host_output), 0, 10000)); ?>
          </div>
        </td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>
</div>
