<?php
$viewHelper = $this->getHelper('MonitoringState');
?>
<div data-icinga-component="app/mainDetailGrid" data-icinga-grid-selection-type="multi">
  <table class="table table-condensed" style="font-size:9pt" >

    <tbody>

    <?php foreach($hosts as $host): ?>
    <?php $hostStateName = strtolower($this->util()->getHostStateName($host->host_state)); ?>
    <?php $hostLink = $this->href('monitoring/show/host', array('host' => $host->host_name)); ?>
    <tr <?= ($this->activeRowHref === $hostLink) ? 'class="active"' : ''; ?> >

    <!-- Color column -->
    <td class="tacheader-status-<?= $hostStateName; ?>">
      <a style="visibility:hidden" href="<?= $hostLink; ?>"></a>
    </td>

    <!-- Icons -->
    <td>
      <?php if (!$host->host_handled && $host->host_state > 0): ?>
      <a href="#" title="Unhandled">
        <i class="icon-table icinga-icon-unhandled"></i>
      </a>
      <?php endif; ?>

      <?php if ($host->host_acknowledged && !$host->host_in_downtime): ?>
      <a href="#" title="Acknowledged">
        <i class="icon-table icinga-icon-acknowledgement"></i>
      </a>
      <?php endif; ?>

      <?php if ($host->host_is_flapping): ?>
      <a href="#" title="Flapping">
        <i class="icon-table icinga-icon-flapping"></i>
      </a>
      <?php endif; ?>

      <?php if (!$host->host_notifications_enabled): ?>
      <a href="#" title="Notifications Disabled">
        <i class="icon-table icinga-icon-notification-disabled"></i>
      </a>
      <?php endif; ?>

      <?php if ($host->host_in_downtime): ?>
      <a href="#" title="In Downtime">
        <i class="icon-table icinga-icon-in-downtime"></i>
      </a>
      <?php endif; ?>

      <?php if (!$host->host_active_checks_enabled): ?>
      <?php if (!$host->host_passive_checks_enabled): ?>
      <a href="#" title="Active And Passive Checks Disabled">
        <i class="icinga-icon-active-passive-checks-disabled"></i>
      </a>
      <?php else: ?>
      <a href="#" title="Active Checks Disabled">
        <i class="icon-table icinga-icon-active-checks-disabled"></i>
      </a>
      <?php endif; ?>
      <?php endif; ?>

      <?php if ($host->host_last_comment !== null): ?>
      <a href="#" title="Comments">
        <i class="icon-table icinga-icon-comment"></i>
      </a>
      <?php endif; ?>
    </td>

    <!-- State -->
    <td title="<?= $viewHelper->getStateTitle($host, 'host'); ?>">
      <a href="<?= $this->href('monitoring/list/services', array('host' => $host->host_name)) ?>">
        <strong><?= $host->host_name ?></strong>
      </a>
    </td>
    <td>
      <div class="output-text">
        <?= $this->escape(substr(strip_tags($host->host_output), 0, 10000)); ?>
      </div>
    </td>


    </tr>
    <?php endforeach; ?>
    </tbody>
  </table>
</div>
