<?php
use Icinga\Module\Monitoring\Object\Host;

if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <?= $this->sortBox; ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content">
<?php

if (count($hostgroups) === 0) {
    echo $this->translate('No hostgroups found matching the filter') . '</div>';
    return;
}
?>
  <table class="groupview action" data-base-target="_next">
    <thead>
      <th><?= $this->translate('Last Problem'); ?></th>
      <th><?= $this->translate('Host Group'); ?></th>
      <th><?= $this->translate('Total Hosts'); ?></th>
      <th><?= $this->translate('Host States'); ?></th>
      <th><?= $this->translate('Total Services'); ?></th>
      <th><?= $this->translate('Service States'); ?></th>
    </thead>
    <tbody>
    <?php foreach ($hostgroups as $h):
        if ($h->hosts_down_unhandled) {
            $handled = false;
            $state = Host::STATE_DOWN;
            $lastStateChange = $h->hosts_down_last_state_change_unhandled;
        } elseif ($h->hosts_unreachable_unhandled) {
            $handled = false;
            $state = Host::STATE_UNREACHABLE;
            $lastStateChange = $h->hosts_unreachable_last_state_change_unhandled;
        } else {
            $handled = true;
            if ($h->hosts_down_handled) {
                $state = Host::STATE_DOWN;
                $lastStateChange = $h->hosts_down_last_state_change_handled;
            } elseif ($h->hosts_unreachable_handled) {
                $state = Host::STATE_UNREACHABLE;
                $lastStateChange = $h->hosts_unreachable_last_state_change_handled;
            } elseif ($h->hosts_up) {
                $state = Host::STATE_UP;
                $lastStateChange = $h->hosts_up_last_state_change;
            } else {
                $state = Host::STATE_PENDING;
                $lastStateChange = $h->hosts_pending_last_state_change;
            }
        }
    ?>
      <tr class="state <?= Host::getStateText($state) ?><?= $handled ? ' handled' : '' ?>" href="<?=
        $this->href('monitoring/list/hosts', array('hostgroup_name' => $h->hostgroup_name))
      ?>">
        <td class="state">
          <strong><?= Host::getStateText($state, true); ?></strong>
          <br>
          <?= $this->timeSince($lastStateChange, $this->compact); ?>
        </td>
        <td class="groupname">
          <?= $this->qlink(
            $h->hostgroup_alias,
            'monitoring/list/hosts',
            array('hostgroup_name' => $h->hostgroup_name),
            array('title' => sprintf($this->translate('List all hosts in the group "%s"'), $h->hostgroup_alias))
          ); ?>
        </td>
        <td class="total">
          <?= $this->qlink(
            $h->hosts_total,
            'monitoring/list/hosts',
            array('hostgroup_name' => $h->hostgroup_name),
            array('title' => sprintf(
                $this->translate('List all hosts in host group "%s"'),
                $h->hostgroup_alias
            ))
          ); ?>
        </td>
        <td>
        <?php if ($h->hosts_up): ?>
          <span class="state ok">
            <?= $this->qlink(
              $h->hosts_up,
              'monitoring/list/hosts',
              array(
                'host_state'        => 0,
                'hostgroup_name'    => $h->hostgroup_name,
                'sort'              => 'host_severity'
              ),
              array(
                'title' => sprintf(
                  $this->translatePlural(
                    'List %u host that is currently in state UP in the host group "%s"',
                    'List %u hosts which are currently in state UP in the host group "%s"',
                    $h->hosts_up
                  ),
                  $h->hosts_up,
                  $h->hostgroup_alias
                )
              )
            ); ?>
          </span>
        <?php endif ?>
        <?php if ($h->hosts_down_unhandled): ?>
          <span class="state critical">
            <?= $this->qlink(
              $h->hosts_down_unhandled,
              'monitoring/list/hosts',
              array(
                'host_state'        => 1,
                'host_acknowledged' => 0,
                'host_in_downtime'  => 0,
                'hostgroup_name'    => $h->hostgroup_name,
                'sort'              => 'host_severity'
              ),
              array(
                'title' => sprintf(
                  $this->translatePlural(
                    'List %u host that is currently in state DOWN in the host group "%s"',
                    'List %u hosts which are currently in state DOWN in the host group "%s"',
                    $h->hosts_down_unhandled
                  ),
                  $h->hosts_down_unhandled,
                  $h->hostgroup_alias
                )
              )
            ); ?>
        <?php endif ?>
          <?php if ($h->hosts_down_handled): ?>
            <span class="state critical handled">
              <?= $this->qlink(
                $h->hosts_down_handled,
                'monitoring/list/hosts',
                array(
                  'host_state'      => 1,
                  'host_handled'    => 1,
                  'hostgroup_name'  => $h->hostgroup_name,
                  'sort'            => 'host_severity'
                ),
                array(
                  'title' => sprintf(
                    $this->translatePlural(
                      'List %u host that is currently in state DOWN (Acknowledged) in the host group "%s"',
                      'List %u hosts which are currently in state DOWN (Acknowledged) in the host group "%s"',
                      $h->hosts_down_handled
                    ),
                    $h->hosts_down_handled,
                    $h->hostgroup_alias
                  )
                )
              ); ?>
            </span>
          <?php endif ?>
        <?php if ($h->hosts_down_unhandled): ?>
          </span>
        <?php endif ?>
        <?php if ($h->hosts_unreachable_unhandled): ?>
          <span class="state unknown">
            <?= $this->qlink(
              $h->hosts_unreachable_unhandled,
              'monitoring/list/hosts',
              array(
                'host_state'        => 2,
                'host_acknowledged' => 0,
                'host_in_downtime'  => 0,
                'hostgroup_name'    => $h->hostgroup_name,
                'sort'              => 'host_severity'
              ),
              array(
                'title' => sprintf(
                  $this->translatePlural(
                    'List %u host that is currently in state UNREACHABLE in the host group "%s"',
                    'List %u hosts which are currently in state UNREACHABLE in the host group "%s"',
                    $h->hosts_unreachable_unhandled
                  ),
                  $h->hosts_unreachable_unhandled,
                  $h->hostgroup_alias
                )
              )
            ); ?>
        <?php endif ?>
          <?php if ($h->hosts_unreachable_handled): ?>
            <span class="state unknown handled">
              <?= $this->qlink(
                $h->hosts_unreachable_handled,
                'monitoring/list/hosts',
                array(
                  'host_state'      => 2,
                  'host_handled'    => 1,
                  'hostgroup_name'  => $h->hostgroup_name,
                  'sort'            => 'host_severity'
                ),
                array(
                  'title' => sprintf(
                    $this->translatePlural(
                      'List %u host that is currently in state UNREACHABLE (Acknowledged) in the host group "%s"',
                      'List %u hosts which are currently in state UNREACHABLE (Acknowledged) in the host group "%s"',
                      $h->hosts_unreachable_handled
                    ),
                    $h->hosts_unreachable_handled,
                    $h->hostgroup_alias
                  )
                )
              ); ?>
            </span>
          <?php endif ?>
        <?php if ($h->hosts_unreachable_unhandled): ?>
          </span>
        <?php endif ?>
        <?php if ($h->hosts_pending): ?>
          <span class="state pending">
            <?= $this->qlink(
              $h->hosts_pending,
              'monitoring/list/hosts',
              array(
                'host_state'        => 99,
                'hostgroup_name'    => $h->hostgroup_name,
                'sort'              => 'host_severity'
              ),
              array(
                'title' => sprintf(
                  $this->translatePlural(
                    'List %u host that is currently in state PENDING in the host group "%s"',
                    'List %u hosts which are currently in state PENDING in the host group "%s"',
                    $h->hosts_pending
                  ),
                  $h->hosts_pending,
                  $h->hostgroup_alias
                )
              )
            ); ?>
          </span>
        <?php endif ?>
        </td>
        <td class="total">
          <?= $this->qlink(
            $h->services_total,
            'monitoring/list/services',
            array('hostgroup_name' => $h->hostgroup_name),
            array('title' => sprintf(
                $this->translate('List all services of all hosts in host group "%s"'),
                $h->hostgroup_alias
            ))
          ); ?>
        </td>
        <td>
        <?php if ($h->services_ok): ?>
          <span class="state ok">
            <?= $this->qlink(
              $h->services_ok,
              'monitoring/list/services',
              array(
                'service_state'     => 0,
                'hostgroup_name'    => $h->hostgroup_name,
                'sort'              => 'service_severity'
              ),
              array(
                'title' => sprintf(
                  $this->translatePlural(
                    'List %u service that is currently in state OK on hosts in the host group "%s"',
                    'List %u services which are currently in state OK on hosts in the host group "%s"',
                    $h->services_ok
                  ),
                  $h->services_ok,
                  $h->hostgroup_alias
                )
              )
            ); ?>
          </span>
        <?php endif ?>
        <?php if ($h->services_critical_unhandled): ?>
          <span class="state critical">
            <?= $this->qlink(
              $h->services_critical_unhandled,
              'monitoring/list/services',
              array(
                'service_state'         => 2,
                'service_acknowledged'  => 0,
                'service_in_downtime'   => 0,
                'host_problem'          => 0,
                'hostgroup_name'        => $h->hostgroup_name,
                'sort'                  => 'service_severity'
              ),
              array(
                'title' => sprintf(
                  $this->translatePlural(
                    'List %u service that is currently in state CRITICAL on hosts in the host group "%s"',
                    'List %u services which are currently in state CRITICAL on hosts in the host group "%s"',
                    $h->services_critical_unhandled
                  ),
                  $h->services_critical_unhandled,
                  $h->hostgroup_alias
                )
              )
            ); ?>
        <?php endif ?>
          <?php if ($h->services_critical_handled): ?>
            <span class="state critical handled">
              <?= $this->qlink(
                $h->services_critical_handled,
                'monitoring/list/services',
                array(
                  'service_state'     => 2,
                  'service_handled'   => 1,
                  'hostgroup_name'    => $h->hostgroup_name,
                  'sort'              => 'service_severity'
                ),
                array(
                  'title' => sprintf(
                    $this->translatePlural(
                      'List %u service that is currently in state CRITICAL (Acknowledged) on hosts in the host group "%s"',
                      'List %u services which are currently in state CRITICAL (Acknowledged) on hosts in the host group "%s"',
                      $h->services_critical_handled
                    ),
                    $h->services_critical_handled,
                    $h->hostgroup_alias
                  )
                )
              ); ?>
            </span>
          <?php endif ?>
        <?php if ($h->services_critical_unhandled): ?>
          </span>
        <?php endif ?>
        <?php if ($h->services_unknown_unhandled): ?>
          <span class="state unknown">
            <?= $this->qlink(
              $h->services_unknown_unhandled,
              'monitoring/list/services',
              array(
                'service_state'         => 3,
                'service_acknowledged'  => 0,
                'service_in_downtime'   => 0,
                'host_problem'          => 0,
                'hostgroup_name'        => $h->hostgroup_name,
                'sort'                  => 'service_severity'
              ),
              array(
                'title' => sprintf(
                  $this->translatePlural(
                    'List %u service that is currently in state UNKNOWN on hosts in the host group "%s"',
                    'List %u services which are currently in state UNKNOWN on hosts in the host group "%s"',
                    $h->services_unknown_unhandled
                  ),
                  $h->services_unknown_unhandled,
                  $h->hostgroup_alias
                )
              )
            ); ?>
        <?php endif ?>
          <?php if ($h->services_unknown_handled): ?>
            <span class="state unknown handled">
              <?= $this->qlink(
                $h->services_unknown_handled,
                'monitoring/list/services',
                array(
                  'service_state'     => 3,
                  'service_handled'   => 1,
                  'hostgroup_name'    => $h->hostgroup_name,
                  'sort'              => 'service_severity'
                ),
                array(
                  'title' => sprintf(
                    $this->translatePlural(
                      'List %u service that is currently in state UNKNOWN (Acknowledged) on hosts in the host group "%s"',
                      'List %u services which are currently in state UNKNOWN (Acknowledged) on hosts in the host group "%s"',
                      $h->services_unknown_handled
                    ),
                    $h->services_unknown_handled,
                    $h->hostgroup_alias
                  )
                )
              ); ?>
            </span>
          <?php endif ?>
        <?php if ($h->services_unknown_unhandled): ?>
          </span>
        <?php endif ?>
        <?php if ($h->services_warning_unhandled): ?>
          <span class="state warning">
            <?= $this->qlink(
              $h->services_warning_unhandled,
              'monitoring/list/services',
              array(
                'service_state'         => 1,
                'service_acknowledged'  => 0,
                'service_in_downtime'   => 0,
                'host_problem'          => 0,
                'hostgroup_name'        => $h->hostgroup_name,
                'sort'                  => 'service_severity'
              ),
              array(
                'title' => sprintf(
                  $this->translatePlural(
                    'List %u service that is currently in state WARNING on hosts in the host group "%s"',
                    'List %u services which are currently in state WARNING on hosts in the host group "%s"',
                    $h->services_warning_unhandled
                  ),
                  $h->services_warning_unhandled,
                  $h->hostgroup_alias
                )
              )
            ); ?>
        <?php endif ?>
          <?php if ($h->services_warning_handled): ?>
            <span class="state warning handled">
              <?= $this->qlink(
                $h->services_warning_handled,
                'monitoring/list/services',
                array(
                  'service_state'     => 1,
                  'service_handled'   => 1,
                  'hostgroup_name'    => $h->hostgroup_name,
                  'sort'              => 'service_severity'
                ),
                array(
                  'title' => sprintf(
                    $this->translatePlural(
                      'List %u service that is currently in state WARNING (Acknowledged) on hosts in the host group "%s"',
                      'List %u services which are currently in state WARNING (Acknowledged) on hosts in the host group "%s"',
                      $h->services_warning_handled
                    ),
                    $h->services_warning_handled,
                    $h->hostgroup_alias
                  )
                )
              ); ?>
            </span>
          <?php endif ?>
        <?php if ($h->services_warning_unhandled): ?>
          </span>
        <?php endif ?>
        <?php if ($h->services_pending): ?>
          <span class="state pending">
            <?= $this->qlink(
              $h->services_pending,
              'monitoring/list/services',
              array(
                'service_state'     => 99,
                'hostgroup_name'    => $h->hostgroup_name,
                'sort'              => 'service_severity'
              ),
              array(
                'title' => sprintf(
                  $this->translatePlural(
                    'List %u service that is currently in state PENDING on hosts in the host group "%s"',
                    'List %u services which are currently in state PENDING on hosts in the host group "%s"',
                    $h->services_pending
                  ),
                  $h->services_pending,
                  $h->hostgroup_alias
                )
              )
            ); ?>
          </span>
        <?php endif ?>
        </td>
      </tr>
    <?php endforeach ?>
    </tbody>
  </table>
</div>
