<?= $this->tabs->render($this); ?>

<?php
use Icinga\Web\Url;

$formatter = $this->getHelper('MonitoringProperties');
?>

<form method="get" action="<?=
    $this->href(
        'monitoring/list/notifications',
        $this->notifications->getAppliedFilter()->toParams()
    );
?>">
  Sort by <?=
    $this->formSelect(
      'sort',
      $this->sort,
      array(
        'class' => 'autosubmit'
      ),
      array(
        'notification_start_time' => 'Time'
      )
    );
  ?>
  <button class="btn btn-small"><i class="icon-refresh"></i></button>
</form>

<?php
$notifications = $this->notifications->paginate();
echo $this->paginationControl($notifications, null, null, array('preserve' => $this->preserve));
?>

<table class="statustable action table-hover">
  <thead>
  <tr>
    <th>Host</th>
    <th>Service</th>
    <th>Type</th>
    <th>Time</th>
    <th>Contact</th>
    <th>Notification command</th>
    <th>Information</th>
  </tr>
  </thead>
  <tbody>
  <?php foreach ($notifications as $notification): ?>
  <tr>
    <td>
      <?= $notification->host_name ?>
    </td>
    <td>
      <?= empty($notification->service_description) ? '' : $notification->service_description; ?>
    </td>
    <td><?= $formatter->getNotificationType($notification); ?>
    </td>
    <td>
      <?= $notification->notification_start_time ?>
    </td>
    <td>
      <?= $notification->notification_contact ?>
    </td>
    <td>
      <?= $notification->notification_command ?>
    </td>
    <td>
      <?= $this->escape(substr(strip_tags($notification->notification_information), 0, 10000)); ?>
    </td>
  </tr>
  <?php endforeach; ?>
  </tbody>
</table>
