<?= $this->tabs->render($this); ?>

<?php
  $formatter = $this->getHelper('MonitoringProperties');
?>
<div data-icinga-component="app/mainDetailGrid">
  <?= $this->sortControl->render($this); ?>

  <?= $this->paginationControl($notifications, null, null, array('preserve' => $this->preserve)); ?>
  <table class="table table-condensed" >
    <thead>
      <tr>
        <th>Host</th>
        <th>Service</th>
        <th>Type</th>
        <th>Time</th>
        <th>Contact</th>
        <th>Notification Command</th>
        <th>Information</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($notifications as $notification): ?>
      <?php
          if (empty($notification->service_description)) {
              $detailLink = $this->href('monitoring/show/host', array('host' => $notification->host_name));
          } else {
              $detailLink = $this->href('monitoring/show/host', array(
                      'host'    =>  $notification->host_name,
                      'service' =>  $notification->service_description,
                      'notification_id'    =>  $notification->notification_internal_id
                  )
              );
          }
      ?>
      <tr <?= ($this->activeRowHref === $detailLink) ? 'class="active"' : ''; ?>>
        <td>
        <a href="<?= $detailLink; ?>" style="visibility:hidden"></a>
        <a href="<?= $this->href('monitoring/show/host', array('host' => $notification->host_name)); ?>">
          <?= $notification->host_name ?>
        </a>
      </td>
      <td>
        <a href="<?= $this->href('monitoring/show/host', array(
                          'host'    =>  $notification->host_name,
                          'service' =>  $notification->service_description
                          )
                      ); ?>">
          <?= empty($notification->service_description) ? '' : $notification->service_description; ?>
          </a>
      </td>
      <td><?= $formatter->getNotificationType($notification); ?>
      </td>
      <td>
        <?= $notification->notification_start_time ?>
      </td>
      <td>
        <?= $notification->notification_contact ?>
      </td>
      <td>
        <?= $notification->notification_command ?>
      </td>
      <td>
        <?= $this->escape(substr(strip_tags($notification->notification_information), 0, 10000)); ?>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>

</div>