<div data-icinga-component="app/mainDetailGrid" data-icinga-grid-selection-type="single">
    <?= $this->sortControl->render($this); ?>
    <?= $this->paginationControl($servicegroups, null, null, array('preserve' => $this->preserve)); ?>
    <table>
        <tbody>
        <?php foreach($servicegroups as $servicegroup): ?>
            <tr>
                <td>
                    <a href="<?= $this->href('monitoring/list/services', array('servicegroups' => $servicegroup->servicegroup_name)); ?>">
                        <?= $servicegroup->servicegroup_name; ?>
                    </a>
                </td>
                <td>
                    <div>
                    <span><?= $servicegroup->cnt_hosts_up; ?></span>
                    <span><?= $servicegroup->cnt_hosts_unreachable; ?>/<?= $servicegroup->cnt_hosts_unreachable_unhandled; ?></span>
                    <span><?= $servicegroup->cnt_hosts_down; ?>/<?= $servicegroup->cnt_hosts_down_unhandled; ?></span>
                    <span><?= $servicegroup->cnt_hosts_pending; ?></span>
                    </div>
                </td>
                <td>
                    <div>
                        <span><?= $servicegroup->cnt_services_ok; ?></span>
                        <span><?= $servicegroup->cnt_services_unknown; ?>/<?= $servicegroup->cnt_services_unknown_unhandled; ?></span>
                        <span><?= $servicegroup->cnt_services_critical; ?>/<?= $servicegroup->cnt_services_critical_unhandled; ?></span>
                        <span><?= $servicegroup->cnt_services_warning; ?>/<?= $servicegroup->cnt_services_warning_unhandled; ?></span>
                        <span><?= $servicegroup->cnt_services_pending; ?></span>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?= $this->paginationControl($servicegroups, null, null, array('preserve' => $this->preserve)); ?>
</div>
