<?php
$viewHelper = $this->getHelper('MonitoringState');
?>

<div data-icinga-component="app/mainDetailGrid" data-icinga-grid-selection-type="multi">

  <table class="table table-condensed pull-left">
    <tbody>
    <?php foreach ($services as $service): ?>
    <?php
        $serviceLink = $this->href(
    'monitoring/show/service',
    array(
    'host' => $service->host_name,
    'service' => $service->service_description
    )
    );
    $hostLink = $this->href(
    'monitoring/show/host',
    array(
    'host' => $service->host_name,
    )
    );
    $serviceStateName = strtolower($this->util()->getServiceStateName($service->service_state));
    ?>
    <tr <?= ($this->activeRowHref === $serviceLink) ? 'class="active"' : ''; ?>>
    <!-- Color column -->
    <td class="tacheader-status-<?= $serviceStateName; ?>">
      <a style="visibility:hidden" href="<?= $serviceLink; ?>"></a>
    </td>
    <td>
      <a style="visibility:hidden" href="<?= $serviceLink; ?>"></a>
      <?php if (!$service->service_handled && $service->service_state > 0): ?>
      <a href="#" title="Unhandled">
        <i class="icon-table icinga-icon-unhandled"></i>
      </a>
      <?php endif; ?>

      <?php if ($service->service_acknowledged && !$service->service_in_downtime): ?>
      <a href="#" title="Acknowledged">
        <i class="icon-table icinga-icon-acknowledgement"></i>
      </a>
      <?php endif; ?>

      <?php if ($service->service_is_flapping): ?>
      <a href="#" title="Flapping">
        <i class="icon-table icinga-icon-flapping"></i>
      </a>
      <?php endif; ?>

      <?php if (!$service->service_notifications_enabled): ?>
      <a href="#" title="Notifications Disabled">
        <i class="icon-table icinga-icon-notification-disabled"></i>
      </a>
      <?php endif; ?>

      <?php if ($service->service_in_downtime): ?>
      <a href="#" title="In Downtime">
        <i class="icon-table icinga-icon-in-downtime"></i>
      </a>
      <?php endif; ?>

      <?php if (!$service->service_active_checks_enabled): ?>
      <?php if (!$service->service_passive_checks_enabled): ?>
      <a href="#" title="Active And Passive Checks Disabled">
        <i class="icon-table icinga-icon-active-passive-checks-disabled"></i>
      </a>
      <?php else: ?>
      <a href="#" title="Active Checks Disabled">
        <i class="icon-table icinga-icon-active-checks-disabled"></i>
      </a>
      <?php endif; ?>
      <?php endif; ?>

      <?php if ($service->service_last_comment !== null): ?>
      <a href="#" title="Comments">
        <i class="icon-table icinga-icon-comment"></i>
      </a>
      <?php endif; ?>
    </td>

    <td title="<?= $viewHelper->getStateTitle($service, 'service'); ?>">
      <strong><?= ucfirst($viewHelper->monitoringState($service, 'service')); ?></strong><br />

      <div class="small-row">
        Since <?= $this->timeSince($service->service_last_state_change); ?>
        <?php if ($service->service_state): ?>
        <br />
        <strong>Attempt:</strong>
        <?= $service->service_attempt; ?>
        (<?= ($service->service_state_type === '1') ? 'Hard' : 'Soft'; ?>)
        <?php endif; ?>
      </div>
</div>
</td>

<td title="<?= $viewHelper->getStateTitle($service, 'host'); ?>">
  <div class="output-text">
    <?= $this->escape(substr(strip_tags($service->service_output), 0, 10000)); ?>
  </div>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>

</div>
