<?php
use Icinga\Module\Monitoring\Object\Host;
use Icinga\Module\Monitoring\Object\Service;

$selfUrl = 'monitoring/list/services';

if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <div class="dontprint">
    <?= $this->render('list/components/selectioninfo.phtml'); ?>
    <?= $this->render('list/components/servicesummary.phtml'); ?>
  </div>
  <?= $this->sortBox; ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content">
<?php

if (count($services) === 0) {
    echo $this->translate('No services found matching the filter') . '</div>';
    return;
}
?>
<table data-base-target="<?= isset($baseTarget) ? $baseTarget : '_next'; ?>"
    class="action multiselect <?php if ($this->compact): ?> compact<?php endif ?>" style="table-layout: auto;"
    data-icinga-multiselect-url="<?= $this->href("monitoring/services/show") ?>"
    data-icinga-multiselect-data="service,host">
  <tbody>
<?php foreach ($services as $service):
    $serviceLink = $this->href(
      'monitoring/service/show',
      array(
        'host' => $service->host_name,
        'service' => $service->service_description
      )
    );
    $hostLink = $this->href(
      'monitoring/show/host',
      array(
        'host' => $service->host_name,
      )
    );
    $serviceStateName = Service::getStateText($service->service_state);
?>
    <tr class="state <?= $serviceStateName ?><?= $service->service_handled ? ' handled' : '' ?>">
      <td class="state">
        <strong><?= Service::getStateText($service->service_state, true); ?></strong>
        <?php if ((int) $service->service_state !== 99): ?>
          <br />
          <?= $this->timeSince($service->service_last_state_change, $this->compact) ?>
          <?php if ((int) $service->service_state > 0 && (int) $service->service_state_type === 0): ?>
            <br />
            <strong>Soft <?= $service->service_attempt ?></strong>
          <?php endif ?>
        <?php endif ?>
      </td>

      <td>
        <div class="sparkline-box"><?= $this->perfdata($service->service_perfdata, true, 5) ?> </div>
        <?= $this->iconImage()->service($service) ?>
        <?= implode(' ', $this->serviceFlags($service)); ?>
        <?= $this->qlink(
          $service->service_display_name,
          $serviceLink,
          null,
          array('title' => sprintf(
            $this->translate('Show detailed information for service %s on host %s'),
            $service->service_display_name,
            $service->host_display_name
          ))
        ); ?><?php if ($this->showHost): ?> on <?= $this->qlink(
          $service->host_display_name . ($service->host_state != 0 ? ' (' . Host::getStateText($service->host_state, true) . ')' : ''),
          $hostLink,
          null,
          array('title' => sprintf($this->translate('Show detailed information for host %s'), $service->host_display_name))
        ); ?><?php endif ?><br>
        <p class="pluginoutput"><?= $this->escape($this->ellipsis($service->service_output, 10000)); ?></p>
      </td>
<?php foreach($this->addColumns as $col): ?>
      <td><?= $this->escape($service->$col) ?></td>
<?php endforeach ?>
    </tr>
<?php endforeach ?>
  </tbody>
</table>
</div>
