<?php
use Icinga\Module\Monitoring\Object\Service;

if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <?= $this->sortBox; ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content" data-base-target="_next">
<?php

$hasHeader = false;
$pivotData = $this->pivot->toArray();
if (count($pivotData) === 0) {
    echo $this->translate('No services found matching the filter') . '</div>';
    return;
}

$hostFilter = '(host_name=' . implode('|host_name=', array_keys($pivotData)) . ')';
?>
  <table class="pivot servicestates">
<?php foreach ($pivotData as $host_name => $serviceStates): ?>
<?php if (!$hasHeader): ?>
    <thead>
      <tr>
        <th><?= $this->partial(
          'joystickPagination.phtml',
          'default',
          array(
            'xAxisPaginator' => $horizontalPaginator,
            'yAxisPaginator' => $verticalPaginator
          )
        ); ?></th>
        <th colspan="<?= count($serviceStates); ?>">
          <div>
<?php
$serviceDescriptions = array_keys($serviceStates);
$serviceFilter = '(service_description=' . implode('|service_description=', $serviceDescriptions) . ')';

foreach ($serviceDescriptions as $service_description): ?>
            <span>
              <?= $this->qlink(
                '<abbr>' . (strlen($service_description) > 18 ? substr($service_description, 0, 18) . '...' : $service_description) . '</abbr>',
                'monitoring/list/services?' . $hostFilter,
                array(
                  'service_description' => $service_description
                ),
                array(
                  'title' => sprintf($this->translate('List all services with the name "%s" on all reported hosts'), $service_description)
                ),
                false
              ); ?>
            </span>
<?php endforeach ?>
          </div>
        </th>
      </tr>
    </thead>
    <tbody>
<?php $hasHeader = true; ?>
<?php endif ?>
      <tr>
        <th>
          <?= $this->qlink(
            $host_name,
            'monitoring/show/services?' . $serviceFilter,
            array('host' => $host_name),
            array('title' => sprintf($this->translate('List all reported services on host %s'), $host_name))
          ); ?>
        </th>
<?php foreach (array_values($serviceStates) as $service): ?>
<?php if ($service !== null): ?>
        <td>
          <span class="sr-only" id="<?= $service->host_name . '_' . $service->service_description . '_desc'; ?>">
            <?= $this->escape($service->service_output); ?>
          </span>
          <?= $this->qlink(
            '',
            'monitoring/show/service',
            array(
              'host'      => $service->host_name,
              'service'   => $service->service_description
            ),
            array(
              'aria-describedby'    => $service->host_name . '_' . $service->service_description . '_desc',
              'class'               => 'state_' . Service::getStateText($service->service_state). ($service->service_handled ? ' handled' : ''),
              'title'               => $this->escape($service->service_output),
              'aria-label'          => sprintf(
                $this->translate('Show detailed information for service %s on host %s'),
                $service->service_description,
                $service->host_name
              )
            )
          ); ?>
        </td>
<?php else: ?>
        <td><span aria-hidden="true">&middot;</span></td>
<?php endif ?>
<?php endforeach ?>
      </tr>
<?php endforeach ?>
    </tbody>
  </table>
</div>
