<table class="action">
<tbody>
<?php

$helper = $this->getHelper('MonitoringState');

foreach ($services as $service):

    $serviceLink = $this->href(
        'monitoring/show/service',
        array(
            'host'    => $service->host_name,
            'service' => $service->service_description
        )
    );
    $hostLink = $this->href(
        'monitoring/show/host',
        array('host' => $service->host_name)
    );
    $serviceStateName = strtolower($this->util()->getServiceStateName($service->service_state));
?>
<!--    <tr <?= ($this->activeRowHref === $serviceLink) ? 'class="active"' : ''; ?>>-->
    <tr class="state <?= $serviceStateName ?><?= $service->service_handled ? ' handled' : '' ?>">

    <!-- Color column -->
<!--
    <td class="tacheader-status-<?= $serviceStateName; ?>">
      <a style="visibility:hidden" href="<?= $serviceLink; ?>"></a>
    </td>
    <td>
      <a style="visibility:hidden" href="<?= $serviceLink; ?>"></a>
      <?php if (!$service->service_handled && $service->service_state > 0): ?>
      <a href="#" title="Unhandled">
        <i class="icon-table icinga-icon-unhandled"></i>
      </a>
      <?php endif; ?>

      <?php if ($service->service_acknowledged && !$service->service_in_downtime): ?>
      <a href="#" title="Acknowledged">
        <i class="icon-table icinga-icon-acknowledgement"></i>
      </a>
      <?php endif; ?>

      <?php if ($service->service_is_flapping): ?>
      <a href="#" title="Flapping">
        <i class="icon-table icinga-icon-flapping"></i>
      </a>
      <?php endif; ?>

      <?php if (!$service->service_notifications_enabled): ?>
      <a href="#" title="Notifications Disabled">
        <i class="icon-table icinga-icon-notification-disabled"></i>
      </a>
      <?php endif; ?>

      <?php if ($service->service_in_downtime): ?>
      <a href="#" title="In Downtime">
        <i class="icon-table icinga-icon-in-downtime"></i>
      </a>
      <?php endif; ?>

      <?php if (!$service->service_active_checks_enabled): ?>
      <?php if (!$service->service_passive_checks_enabled): ?>
      <a href="#" title="Active And Passive Checks Disabled">
        <i class="icon-table icinga-icon-active-passive-checks-disabled"></i>
      </a>
      <?php else: ?>
      <a href="#" title="Active Checks Disabled">
        <i class="icon-table icinga-icon-active-checks-disabled"></i>
      </a>
      <?php endif; ?>
      <?php endif; ?>

      <?php if (isset($service->service_last_comment) && $service->service_last_comment !== null): ?>
      <a href="#" title="Comments">
        <i class="icon-table icinga-icon-comment"></i>
      </a>
      <?php endif; ?>
    </td>
-->
    <td class="state" title="<?= $helper->getStateTitle($service, 'service'); ?>">
<?= $this->timeSince($service->service_last_state_change); ?>
</div>
</td>
<td>
        <?= $this->perfdata($service->service_perfdata, true) ?>
<a href="<?= $serviceLink ?>"><?= $service->service_display_name ?></a> on <a href="<?= $hostLink ?>"><?= $service->host_name; ?></a><br />
  <div class="pluginoutput">
    <?= $this->escape(substr(strip_tags($service->service_output), 0, 10000)); ?>
  </div>

</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>

