<?php
use Icinga\Module\Monitoring\Object\Service;

if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <?= $this->sortBox; ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content" data-base-target="_next">
<?php
if (empty($pivotData)) {
    echo $this->translate('No services found matching the filter') . '</div>';
    return;
}
$hostFilter = '(host_name=' . implode('|host_name=', array_keys($pivotData)) . ')';
?>

<table class="service-grid-table">
    <thead>
        <tr>
            <th><?= $this->partial(
                'joystickPagination.phtml',
                'default',
                array(
                    'xAxisPaginator' => $horizontalPaginator,
                    'yAxisPaginator' => $verticalPaginator
                )
            ); ?></th>
        <?php foreach ($pivotHeader['cols'] as $serviceDescription => $serviceDisplayName): ?>
            <th class="rotate-45"><div><span><?= $this->qlink(
                $this->ellipsis($serviceDisplayName, 18),
                'monitoring/list/services?' . $hostFilter,
                array('service_description' => $serviceDescription),
                array('title' => sprintf(
                    $this->translate('List all services with the name "%s" on all reported hosts'),
                    $serviceDisplayName
                )),
                false
            ) ?></span></div></th>
        <?php endforeach ?>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($pivotHeader['rows'] as $hostName => $hostDisplayName): ?>
        <tr>
            <th><?php
                $services = $pivotData[$hostName];
                $serviceFilter = '(service_description=' . implode('|service_description=', array_keys($services)) . ')';
                echo $this->qlink(
                    $hostDisplayName,
                    'monitoring/list/services?' . $serviceFilter,
                    array('host_name' => $hostName),
                    array('title' => sprintf($this->translate('List all reported services on host %s'), $hostDisplayName))
                );
            ?></th>
        <?php foreach (array_keys($pivotHeader['cols']) as $serviceDescription): ?>
            <td>
            <?php
            $service = $pivotData[$hostName][$serviceDescription];
            if ($service === null): ?>
                <span aria-hidden="true">&middot;</span>
            <?php continue; endif ?>
                <?php $ariaDescribedById = $this->protectId($service->host_name . '_' . $service->service_description . '_desc') ?>
                <span class="sr-only" id="<?= $ariaDescribedById ?>">
                    <?= $this->escape($service->service_output) ?>
                </span>
              <?= $this->qlink(
                  '',
                  'monitoring/service/show',
                  array(
                      'host'    => $hostName,
                      'service' => $serviceDescription
                  ),
                array(
                    'aria-describedby'    => $ariaDescribedById,
                    'class'               => 'bg-state-' . Service::getStateText($service->service_state) . ($service->service_handled ? ' handled' : ''),
                    'title'               => $this->escape($service->service_output),
                    'aria-label'          => sprintf(
                        $this->translate('Show detailed information for service %s on host %s'),
                        $service->service_display_name,
                        $service->host_display_name
                    )
                )
            ); ?>
            </td>
        <?php endforeach ?>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
</div>
