<div class="controls">
<?= $this->tabs ?>
<h1>History - Critical Events</h1>
</div>
<div class="content" data-base-target="_next">
<?php

$grid->setColor('#FC0707');
$data = array();

if (count($summary) === 0) {
    echo t('No history entry matching the filter');
}
foreach ($summary as $entry) {
    $day = $entry->day;
    $value = $entry->cnt_critical;
    $caption =  $value . ' ' .
        t('critical events on ') . $this->dateFormat()->formatDate(strtotime($day));
    $data[$day] = array(
        'value'   => $value,
        'caption' => $caption,
        'url'     => $this->href(
            'monitoring/list/eventhistory',
            array(
                'timestamp<'  => strtotime($day . ' 23:59:59'),
                'timestamp>'  => strtotime($day . ' 00:00:00'),
                'object_type' => 'service',
                'state'       => '2',
                'type'        => '(hard_state|soft_state)'
            )
        )
    );
}
$grid->setData($data);
?>
<?= $grid ?>
</div>
