<?php

use Icinga\Web\Url;

$showText = $this->translate('%s: Show %s %u to %u out of %u', 'pagination.joystick');
$xAxisPages = $xAxisPaginator->getPages('all');
$yAxisPages = $yAxisPaginator->getPages('all');

$flipUrl = Url::fromRequest();
if ($flipUrl->getParam('flipped')) {
    $flipUrl->remove('flipped');
} else {
    $flipUrl->setParam('flipped');
}
if ($flipUrl->hasParam('page')) {
    $flipUrl->setParam('page', implode(',', array_reverse(explode(',', $flipUrl->getParam('page')))));
}
if ($flipUrl->hasParam('limit')) {
    $flipUrl->setParam('limit', implode(',', array_reverse(explode(',', $flipUrl->getParam('limit')))));
}

$totalYAxisPages = $yAxisPaginator->count();
$currentYAxisPage = $yAxisPaginator->getCurrentPageNumber();
$prevYAxisPage = $currentYAxisPage > 1 ? $currentYAxisPage - 1 : null;
$nextYAxisPage = $currentYAxisPage < $totalYAxisPages ? $currentYAxisPage + 1 : null;

$totalXAxisPages = $xAxisPaginator->count();
$currentXAxisPage = $xAxisPaginator->getCurrentPageNumber();
$prevXAxisPage = $currentXAxisPage > 1 ? $currentXAxisPage - 1 : null;
$nextXAxisPage = $currentXAxisPage < $totalXAxisPages ? $currentXAxisPage + 1 : null;

?>

<table class="joystick-pagination">
  <tbody>
    <tr>
      <td>&nbsp;</td>
      <td>
      <?php if ($prevYAxisPage): ?>
        <?= $this->qlink(
          '',
          Url::fromRequest(),
          [
            'page' => $currentXAxisPage . ',' . $prevYAxisPage
          ],
          [
            'icon'              => 'up-open',
            'data-base-target'  => '_self',
            'title'             => sprintf(
              $showText,
              $this->translate('Y-Axis', 'pagination.joystick'),
              $this->translate('hosts', 'pagination.joystick'),
              ($prevYAxisPage - 1) * $yAxisPages->itemCountPerPage + 1,
              $prevYAxisPage * $yAxisPages->itemCountPerPage,
              $yAxisPages->totalItemCount
            )
          ]
        ); ?>
      <?php else: ?>
        <?= $this->icon('up-open'); ?>
      <?php endif ?>
      </td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>
      <?php if ($prevXAxisPage): ?>
        <?= $this->qlink(
          '',
          Url::fromRequest(),
          [
            'page' => $prevXAxisPage . ',' . $currentYAxisPage
          ],
          [
            'icon'              => 'left-open',
            'data-base-target'  => '_self',
            'title'             => sprintf(
              $showText,
              $this->translate('X-Axis', 'pagination.joystick'),
              $this->translate('services', 'pagination.joystick'),
              ($prevXAxisPage - 1) * $xAxisPages->itemCountPerPage + 1,
              $prevXAxisPage * $xAxisPages->itemCountPerPage,
              $xAxisPages->totalItemCount
            )
          ]
        ); ?>
      <?php else: ?>
        <?= $this->icon('left-open'); ?>
      <?php endif ?>
      </td>
      <?php if ($this->flippable): ?>
      <td><?= $this->qlink(
        '',
        $flipUrl,
        null,
        [
          'icon'                => 'arrows-cw',
          'data-base-target'    => '_self',
          'title'               => $this->translate('Flip grid axes')
        ]
      ) ?></td>
      <?php else: ?>
      <td>&nbsp;</td>
      <?php endif ?>
      <td>
      <?php if ($nextXAxisPage): ?>
        <?= $this->qlink(
          '',
          Url::fromRequest(),
          [
            'page' => $nextXAxisPage . ',' . $currentYAxisPage
          ],
          [
            'icon'              => 'right-open',
            'data-base-target'  => '_self',
            'title'             => sprintf(
              $showText,
              $this->translate('X-Axis', 'pagination.joystick'),
              $this->translate('services', 'pagination.joystick'),
              $currentXAxisPage * $xAxisPages->itemCountPerPage + 1,
              $nextXAxisPage === $xAxisPages->last ? $xAxisPages->totalItemCount : $nextXAxisPage * $xAxisPages->itemCountPerPage,
              $xAxisPages->totalItemCount
            )
          ],
          false
        ); ?>
      <?php else: ?>
        <?= $this->icon('right-open'); ?>
      <?php endif ?>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>
      <?php if ($nextYAxisPage): ?>
        <?= $this->qlink(
          '',
          Url::fromRequest(),
          [
            'page' => $currentXAxisPage . ',' . $nextYAxisPage
          ],
          [
            'icon'              => 'down-open',
            'data-base-target'  => '_self',
            'title'             => sprintf(
              $showText,
              $this->translate('Y-Axis', 'pagination.joystick'),
              $this->translate('hosts', 'pagination.joystick'),
              $currentYAxisPage * $yAxisPages->itemCountPerPage + 1,
              $nextYAxisPage === $yAxisPages->last ? $yAxisPages->totalItemCount : $nextYAxisPage * $yAxisPages->itemCountPerPage,
              $yAxisPages->totalItemCount
            )
          ]
        ); ?>
      <?php else: ?>
        <?= $this->icon('down-open'); ?>
      <?php endif ?>
      </td>
      <td>&nbsp;</td>
    </tr>
  </tbody>
</table>
