<?php

if ($this->pageCount <= 1) return;

$fromto = $this->translate('%d to %d of %d');
$total = $this->totalItemCount;
$limit = $this->itemCountPerPage;
$title_prev = sprintf(
    $fromto,
    ($this->current - 2) * $limit + 1,
    ($this->current - 1) * $limit,
    $total
);

$title_next = sprintf(
    $fromto,
    ($this->current) * $limit + 1,
    ($this->current + 1) * $limit,
    $total
);

?><div class="pagination pagination-mini" style="margin:0px">
  <ul>
    <!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <li><a href="<?= $this->url()->setParam('page', $this->previous) ?>" title="<?= $title_prev ?>">« <?= $this->translate('Back') ?></a></li>
<?php else: ?>
    <li class="disabled"><span>« <?= $this->translate('Back') ?></span></li>
<?php endif ?>
    <!-- Numbered page links -->
<?php

foreach ($this->pagesInRange as $page):

    $start = ($page - 1) * $limit + 1;
    $end = $page * $limit;
    if ($end > $total) {
        $end = $total;
    }
    $title = sprintf($fromto, $start, $end, $total);
    $class = $page === $this->current ? ' class="active"' : '';

    if ($page === '...'): ?>
    <li class="disabled"><span>...</span></li>
<?php else: ?>
    <li<?= $class ?>><a href="<?= $this->url()->setParam('page', $page) ?>" title="<?= $title ?>"><?= $page ?></a></li>
<?php
    endif;
endforeach;
?>
<!-- Next page link -->
<? if (isset($this->next)): ?>
    <li><a href="<?= $this->url()->setParam('page', $this->next) ?>" title="<?= $title_next ?>"><?= t('Next') ?> »</a></li>
<? else: ?>
    <li class="disabled"><span><?= t('Next') ?> »</span></li>
<? endif ?>
  </ul>
</div>
