<?php

use Icinga\Chart\BubblePosition;
use Icinga\Chart\ProgressBar;
use Icinga\Web\Notification;

$pages = $wizard->getPages();
$finished = isset($success);
$configPages = array_slice($pages, 3, count($pages) - 4, true);
$currentPos = array_search($wizard->getCurrentPage(), $pages, true);
$progressBarOptions = [
    'class'  => 'line stick-left',
    'width'  => '95%',
    'height' => '50px'
];
list($configPagesLeft, $configPagesRight) = array_chunk($configPages, (int) (count($configPages) / 2), true);

$visitedPages = array_keys($wizard->getPageData());
$maxProgress = max(array_merge([0], array_keys(array_filter(
    $pages,
    function ($page) use ($visitedPages) {
        return in_array($page->getName(), $visitedPages);
    }
))));

?>
<div id="setup-content-wrapper" data-base-target="layout">
    <div class="setup-header">
        <?= $this->img('img/icinga-logo-big.png'); ?>
        <div class="progress-bar">
            <div class="step step-sm">
                <h1><?= $this->translate('Welcome', 'setup.progress'); ?></h1>
                <?php
                $progressBar = ProgressBar::withOptions($progressBarOptions)
                    ->useBubble(true)
                    ->markComplete($finished || $currentPos > 0 ? 1 : 0)
                    ->markVisited($maxProgress > 0 ? 1 : 0);

                echo $progressBar->render();
                ?>
            </div>
            <div class="step step-sm">
                <h1><?= $this->translate('Modules', 'setup.progress'); ?></h1>
                <?php
                $progressBar = ProgressBar::withOptions($progressBarOptions)
                    ->useBubble(true)
                    ->markComplete($finished || $currentPos > 0 ? 1 : 0)
                    ->markVisited($maxProgress > 0 ? 1 : 0);

                echo $progressBar->render();
                ?>

                <?php if (($maxProgress < $currentPos && $currentPos === 1) || ($maxProgress >= $currentPos && $maxProgress === 1)): ?>
                    <?= $this->restartForm ?>
                <?php endif ?>
            </div>
            <div class="step step-sm">
                <h1><?= $this->translate('Requirements', 'setup.progress'); ?></h1>
                <?php
                $progressBar = ProgressBar::withOptions($progressBarOptions)
                    ->useBubble(true)
                    ->markComplete($finished || $currentPos > 0 ? 1 : 0)
                    ->markVisited($maxProgress > 0 ? 1 : 0);

                echo $progressBar->render()
                ?>

                <?php if (($maxProgress < $currentPos && $currentPos === 2) || ($maxProgress >= $currentPos && $maxProgress === 2)): ?>
                    <?= $this->restartForm ?>
                <?php endif ?>
            </div>
            <div class="step step-lg">
                <?php
                $completePage = 0;
                $visitedPage = 0;

                $progressBar = ProgressBar::withOptions($progressBarOptions)
                    ->useBubble(true);
                ?>

                <h1><?= $this->translate('Configuration', 'setup.progress'); ?></h1>

                <?php
                foreach ($configPagesLeft as $pos => $page) {
                    $progressBar->addSection();
                    $completePage += $finished || $pos < $currentPos ? 1 : 0;
                    $visitedPage += $pos < $maxProgress ? 1 : 0;
                }

                foreach ($configPagesRight as $pos => $page) {
                    $progressBar->addSection();
                    $completePage += $finished || $pos < $currentPos ? 1 : 0;
                    $visitedPage += $pos < $maxProgress ? 1 : 0;
                }

                $progressBar->markComplete($completePage);

                echo $progressBar->render();

                if ($maxProgress > 2 || $currentPos > 2) {
                    echo $this->restartForm;
                }
                ?>
            </div>
            <div class="step step-sm">
                <h1><?= $this->translate('Finish', 'setup.progress'); ?></h1>
                <?php
                $progressBar = ProgressBar::withOptions([
                    'class'  => 'line stick-left',
                    'width'  => '55%',
                    'height' => '50px'
                ])->useBubble(true, BubblePosition::END)
                    ->markComplete($finished ? 1 : 0);

                echo $progressBar->render();
                ?>
            </div>
        </div>
    </div>
    <div class="setup-content">
        <?php if ($finished): ?>
            <?= $this->render('index/parts/finish.phtml'); ?>
        <?php else: ?>
            <?= $this->render('index/parts/wizard.phtml'); ?>
        <?php endif ?>
    </div>
</div>
<div id="footer">
    <ul role="alert" id="notifications"><?php
        $notifications = Notification::getInstance();
        if ($notifications->hasMessages()) {
            foreach ($notifications->popMessages() as $m) {
                echo '<li class="' . $m->type . '">' . $this->escape($m->message) . '</li>';
            }
        }
        ?></ul>
</div>
