<div class="controls" data-base-target="_main">
    <?= $tabs ?>
</div>
<div class="content">
    <h1 tabindex="-1" id="roles-index">
        <?= $this->translate('Roles') ?>
    </h1>
    <div class="skip-links skip-links-inline">
        <h2 class="sr-only"><?= $this->translate('Skip Links'); ?></h2>
        <ul>
            <li>
                <a tabindex="0" href="#roles-index-new">
                    <?= t('Skip To Create New Role'); ?>
                </a>
            </li>
        </ul>
    </div>
    <div>
        <?php /** @var \Icinga\Application\Config $roles */ if ($roles->isEmpty()): ?>
            <?= $this->translate('No roles found.') ?>
        <?php else: ?>
            <table class="avp action" data-base-target="_next">
                <thead>
                <tr>
                    <th><?= $this->translate('Name') ?></th>
<!--                    <th>--><?//= $this->translate('Permissions') ?><!--</th>-->
<!--                    <th>--><?//= $this->translate('Restrictions') ?><!--</th>-->
                    <th><?= $this->translate('Users') ?></th>
                    <th><?= $this->translate('Groups') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($roles as $name => $role): /** @var object $role */ ?>
                    <tr>
                        <td>
                            <?= $this->escape($name) ?>
                            <div class="hidden">
                                <a href="<?= $this->url('roles/update', array('role' => $name)) ?>"></a>
                            </div>
                        </td>
<!--                        <td>--><?//= $this->escape($role->permissions, 0, 50) ?><!--</td>-->
<!--                        <td>-->
<!--                            --><?php
//                            // TODO(el): $role->without(...) or $role->shift(...) would be nice!
//                            $restrictions = clone $role;
//                            unset($restrictions['users']);
//                            unset($restrictions['groups']);
//                            unset($restrictions['permissions']);
//                            ?>
<!--                            --><?php //if (! empty($restrictions)): ?>
<!--                            <table>-->
<!--                                <tbody>-->
<!--                                --><?php //foreach ($restrictions as $restrictionName => $restriction): ?>
<!--                                    <tr>-->
<!--                                        <th>--><?//= $this->escape($restrictionName) ?><!--</th>-->
<!--                                        <td>--><?//= $this->escape($restriction) ?><!--</td>-->
<!--                                    </tr>-->
<!--                                --><?php //endforeach ?>
<!--                                </tbody>-->
<!--                            </table>-->
<!--                            --><?php //endif ?>
<!--                        </td>-->
                        <td><?= $this->escape($role->users) ?></td>
                        <td><?= $this->escape($role->groups) ?></td>
                        <td>
                            <a href="<?= $this->url('roles/remove', array('role' => $name)) ?>"
                               title="<?= sprintf(
                                   $this->translate('Remove role %s'),
                                   $name
                               ) ?>">
                                <?= $this->icon('cancel') ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        <?php endif ?>
        <h2 tabindex="-1" id="roles-index-new" class="sr-only">
            <?= $this->translate('Create New Role'); ?>
        </h2>
        <a data-base-target="_next" href="<?= $this->href('roles/new') ?>">
            <?= $this->translate('New Role') ?>
        </a>
    </div>
</div>
