<?php
use Icinga\Module\Monitoring\Object\Host;
use Icinga\Module\Monitoring\Object\Service;

?>
<table class="objectstate">
    <tr class="state <?= Host::getStateText($object->host_state); ?><?= $object->host_handled ? ' handled' : ''; ?>">
        <td class="state">
            <strong><?= Host::getStateText($object->host_state, true); ?></strong><br>
            <?= $this->timeSince($object->host_last_state_change) ?>
        </td>
        <td>
          <?= $this->iconImage()->service($object) ?>
          <strong><?= $this->escape($object->host_display_name); ?></strong>
          <?php if ($object->host_display_name !== $object->host_name): ?>
            <small>(<?= $this->escape($object->host_name); ?>)</small>
          <?php endif ?>
          <br/>
          <?php if ($object->host_address6 && $object->host_address6 !== $object->host_name): ?>
            <span class="address padded" title="IPv6 address"><?= $this->escape($object->host_address6); ?></span>
          <?php endif ?>
          <?php if ($object->host_address && $object->host_address !== $object->host_name): ?>
            <span class="address padded" title="IPv4 address"><?= $this->escape($object->host_address); ?></span>
          <?php endif ?>
        </td>
    </tr>
    <tr class="state <?= Service::getStateText($object->service_state); ?><?= $object->service_handled ? ' handled' : ''; ?>">
        <td class="state">
            <strong><?= Service::getStateText($object->service_state, true); ?></strong><br>
            <?= $this->timeSince($object->service_last_state_change) ?>
        </td>
        <td>
            <?= $this->iconImage()->host($object) ?>
            <strong><?= $this->translate('Service'); ?>: <?= $this->escape($object->service_display_name); ?></strong>
            <?php if ($object->service_display_name !== $object->service_description): ?>
              <small>(<?= $this->escape($object->service_description); ?>)</small>
            <?php endif ?>
            <?= $this->render('partials/service/statusicons.phtml'); ?>
        </td>
    </tr>
</table>
