<?php
use Icinga\Module\Monitoring\Object\Service;
use Icinga\Web\Url;
?>

<?php
    $i = 0;
    $hidden = array();
    $hiddenRich = array();
?>
<?php if (($serviceCount = count($objects)) > 0): ?>
    <p>
    <table class="state statesummary">
    <thead>
    <tr>
        <th></th>
        <th></th>
        <th><?= $this->icon('service'); ?> <?= $this->translate('Service'); ?></th>
        <th><?= $this->icon('host'); ?> <?= $this->translate('Host'); ?></th>
        <th class="collapse"><?= $this->translate('Output'); ?></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($objects as $service): /** @var Service $service */ ?>
        <?php
        $i++;
        if ($i > 5) {
            $desc = $service->getHost()->getName() . ' on ' . $service->getName();
            $hidden[] = $desc;
            $hiddenRich[] = sprintf("<div class='color-box badge-%s'></div>%s", $service->getStateText($service->service_state) ,$desc);
            continue;
        }
        ?>

        <tr class="state <?= Service::getStateText($service->service_state); ?><?= $service->service_handled ? ' handled' : '' ?>">
            <td class="state"><?= Service::getStateText($service->service_state, true); ?><br /></td>
            <td>
                <?php if (!$service->service_handled && $service->service_state > 0): ?>
                    <?= $this->icon('attention-alt', $this->translate('Unhandled')) ?>
                <?php endif ?>

                <?php if ($service->service_acknowledged && !$service->service_in_downtime): ?>
                    <?= $this->icon('ok', $this->translate('Acknowledged') . (
                        $service->service_last_ack ? ': ' . $service->service_last_ack : ''
                        )) ?>
                <?php endif ?>

                <?php if ($service->service_is_flapping): ?>
                    <?= $this->icon('flapping', $this->translate('Flapping')) ?>
                <?php endif ?>

                <?php if (!$service->service_notifications_enabled): ?>
                    <?= $this->icon('bell-off-empty', $this->translate('Notifications Disabled')) ?>
                <?php endif ?>

                <?php if ($service->service_in_downtime): ?>
                    <?= $this->icon('plug', $this->translate('In Downtime')) ?>
                <?php endif ?>

                <?php if (isset($service->service_last_comment) && $service->service_last_comment !== null): ?>
                    <?= $this->icon('comment', $this->translate('Last Comment: ') . $service->service_last_comment) ?>
                <?php endif ?>
            </td>
            <td><?= $this->escape($service->getName()); ?></td>
            <td><?= $this->escape($service->getHost()->getName()); ?></b></td>
            <td><p class="pluginoutput collapse"><?= $this->escape($service->service_output) ?></p></td>
        </tr>
    <?php endforeach ?>

    <?php if (count($hidden)): ?>
        <tr>
        <td>
        <div class="selection-info" data-title-rich="<span align='left'><?= join('<br>', $hiddenRich) ?></span>"
              title="<?= join(', ', $hidden) ?>">
              <?= sprintf(t('%d more ...'), count($hidden)) ?>
        </div>
        </td>
        </tr>
    <?php endif ?>

    </tbody>
    </table>
    </p>
<?php endif ?>
