<?php
use Icinga\Module\Monitoring\Object\Service;

$i = 0;
?>
<?php if (($serviceCount = count($objects)) > 0): ?>
    <table class="action state statesummary">
    <tbody>
    <?php foreach ($objects as $service): /** @var Service $service */ ?>
        <?php
        if (++ $i > 5) {
            continue;
        }
        ?>
        <tr class="state <?= Service::getStateText($service->service_state); ?><?= $service->service_handled ? ' handled' : '' ?>">
            <td class="state"><?= Service::getStateText($service->service_state, true); ?><br /></td>
            <td>
            <?= implode(' ', $this->serviceFlags($service)) ?>
            <b>
               <?= $this->escape($service->getName()); ?>
               <?= $this->translate('on') ?>
               <?= $this->escape($service->getHost()->getName()); ?><br>
            </b>
            <?= $this->escape($service->service_output) ?>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
    </table>
    <div class="hbox-item">
        <?php
        echo $this->qlink(
            sprintf($this->translate('List all %d services ...'), $i),
            $listAllLink,
            null,
            array('data-base-target' => '_next')
        );
        ?>
    </div>
<?php endif ?>
