<?php

if (! $this->object->service_handled && $this->object->service_state > 0) {
    echo $this->icon('attention-alt', $this->translate('Unhandled'));
}

if ($this->object->service_acknowledged && !$this->object->service_in_downtime) {
    echo $this->icon('ok', $this->translate('Acknowledged'));
}

if (! $this->object->service_notifications_enabled) {
    echo $this->icon('bell-off-empty', $this->translate('Notifications Disabled'));
}

if ($this->object->service_in_downtime) {
    echo $this->icon('plug', $this->translate('In Downtime'));
}

if (! $this->object->service_active_checks_enabled) {
    if ($this->object->service_passive_checks_enabled) {
        echo $this->icon('eye-off', $this->translate('Active Checks Disabled'));
    } else {
        echo $this->icon('eye-off', $this->translate('Active And Passive Checks Disabled'));
    }
}
