<?php
$this->is_service = false;
?>

<div class="panel panel-default">
    <div class="panel panel-heading">
        {{HOST_ICON}}
        <h1> Hosts </h1>
    </div>

    <div class="panel panel-body">
        <?= $this->render('multi/components/summary.phtml'); ?>
    </div>
</div>

<?= $this->render('multi/components/downtimes.phtml'); ?>
<?= $this->render('multi/components/comments.phtml'); ?>
<?= $this->render('multi/components/configuration.phtml'); ?>
