<?php
$this->is_service = true;
$this->hostquery = implode($this->hostnames, ',');
$this->servicequery = implode($this->servicenames, ',');
$this->target = array(
	'host'	=> $this->hostquery,
	'service' => $this->servicequery
);
?>

<?= $this->tabs; ?>

<div class="controls">
    <h1> Summary for <?= count($objects) ?> services </h1>
</div>

<div class="content">
    <?= $this->render('multi/components/objectlist.phtml'); ?>
    <h3> <?=$this->icon('servicegroup.png')?> Service State </h3>

    <table class="avp newsection">
        <tbody>
        <?= $this->render('multi/components/summary.phtml'); ?>
        <?= $this->render('multi/components/comments.phtml'); ?>
        <?= $this->render('multi/components/downtimes.phtml'); ?>
        </tbody>
    </table>

    <h3> <?=$this->icon('configuration.png')?> Options </h3>
    <table class="avp newsection">
        <tbody>
        <?= $this->render('multi/components/configuration.phtml') ?>
        </tbody>
    </table>
</div>


<a
    rel="tooltip"
    title="Submit passive checkresults"
    href="<?= $this->href('monitoring/command/submitpassivecheckresult', $this->target); ?>"
    class="button btn-cta btn-common btn-small"
>
    <i class="icinga-icon-submit"></i>
</a>
