<div class="controls">
    <?= $tabs ?>
</div>
<div class="content" data-base-target="_next">
    <?= $this->qlink(
        $this->translate('Create A New User Group Backend') ,
        'usergroupbackend/create',
        null,
        array(
            'class'   => 'button action-link',
            'icon'    => 'plus',
            'title'   => $this->translate('Create a new user group backend')
        )
    ) ?>
<?php if (count($backendNames) > 0): ?>
    <table class="action-table listing-table">
    <thead>
    <tr>
        <th><?= $this->translate('Backend') ?></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($backendNames as $backendName => $config):
        $type = $config->get('backend');
        ?>
        <tr>
            <td>
                <?= $this->qlink(
                    $backendName,
                    'usergroupbackend/edit',
                    array('backend' => $backendName),
                    array(
                        'icon'  => $type === 'external' ? 'magic' : ($type === 'ldap' || $type === 'msldap' ? 'sitemap' : 'database'),
                        'title' => sprintf($this->translate('Edit user group backend %s'), $backendName)
                    )
                ); ?>
            </td>
            <td class="text-right"><?= $this->qlink(
                    null,
                    'usergroupbackend/remove',
                    array('backend' => $backendName),
                    array(
                        'class' => 'action-link',
                        'icon'  => 'cancel',
                        'title' => sprintf($this->translate('Remove user group backend %s'), $backendName)
                    )
            ) ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
    </table>
<?php endif ?>
</div>
