<div class="controls">
    <?= $this->tabs ?>
    <?= $this->qlink(
        $this->translate('Comment / Acknowledge') ,
        $this->url()->setPath('eventdb/comments/new'),
        null,
        array(
            'class'             => 'button-link',
            'data-base-target'  => '_self',
            'icon'              => 'comment',
            'title'             => $this->translate('Comment / Acknowledge')
        )
    ) ?>
</div>
