<div class="controls"></div>
    <?= /** @type \Icinga\Web\Widget\Tabs $tabs */ $tabs->showOnlyCloseButton() ?>
    <h1><?= $this->translate('Available documentations') ?></h1>
<div class="content">
    <ul>
        <li><a href="<?= $this->href('doc/icingaweb/toc') ?>">Icinga Web 2</a></li>
        <li><a href="<?= $this->href('doc/module/') ?>"><?= $this->translate('Module documentations') ?></a></li>
    </ul>
</div>
