<?php if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs; ?>
</div>
<?php endif;

$rv = $this->runtimeVariables()->create($this->runtimevariables);
$cp = $this->checkPerformance()->create($this->checkperformance);

?>

<div class="content processinfo">

<h4>Object summaries</h4>
<table class="table-bordered table">
    <thead>
    <tr>
        <td style="width: 300px;">&nbsp;</td>
        <td># overall / scheduled</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <strong>Hosts</strong>
        </td>
        <td>
            <?= $rv->total_hosts; ?>
            / <?= $rv->total_scheduled_hosts; ?>
        </td>
    </tr>

    <tr>
        <td>
            <strong>Services</strong>
        </td>
        <td>
            <?= $rv->total_services; ?>
            / <?= $rv->total_scheduled_services; ?>
        </td>
    </tr>

    <tr>
        <td>
            <strong>Average services per host</strong>
        </td>
        <td>
            <?= sprintf('%.2f', $rv->average_services_per_host); ?>
            / <?= sprintf('%.2f', $rv->average_scheduled_services_per_host); ?>
        </td>
    </tr>
    </tbody>
</table>

<h4>Active checks</h4>
<table class="table-bordered table">
    <thead>
    <tr>
        <td style="width: 300px;">&nbsp;</td>
        <td>#</td>
        <td>Latency</td>
        <td>Execution time</td>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <strong>Host Checks</strong>
            </td>
            <td><?= $cp->host_active_count; ?></td>
            <td><?= sprintf('%.3f', $cp->host_active_latency_avg); ?>s</td>
            <td><?= sprintf('%.3f', $cp->host_active_execution_avg); ?>s</td>
        </tr>
        <tr>
            <td>
                <strong>Service Checks</strong>
            </td>
            <td><?= $cp->service_active_count; ?></td>
            <td><?= sprintf('%.3f', $cp->service_active_latency_avg); ?>s</td>
            <td><?= sprintf('%.3f', $cp->service_active_execution_avg); ?>s</td>
        </tr>
    </tbody>
</table>

<h4>Passive checks</h4>
<table class="table-bordered table">
    <thead>
    <tr>
        <td style="width: 300px;">&nbsp;</td>
        <td>#</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <strong>Host Checks</strong>
        </td>
        <td><?= $cp->host_passive_count; ?></td>
    </tr>
    <tr>
        <td>
            <strong>Service Checks</strong>
        </td>
        <td><?= $cp->service_passive_count; ?></td>
    </tr>
    </tbody>
</table>


</div>
