<div class="nav navbar-nav topbar-host-status-summary">
    <span class="topbar-status-up">
        <a href="<?= $this->href('monitoring/list/hosts', array('host_severity' => 4)); ?>" title="Hosts Up">
            <?= $hostSummary->hosts_up ?>
        </a>
    </span>
    <span class="topbar-status-down">
        <a href="<?= $this->href('monitoring/list/hosts', array('host_severity' => 36)); ?>" title="Hosts Down Unhandled">
            <?= $hostSummary->hosts_down_unhandled ?>
        </a>/
        <a href="<?= $this->href('monitoring/list/hosts', array('host_severity' => array(33, 34))); ?>" title="Hosts Down Handled">
            <?= $hostSummary->hosts_down_handled ?>
        </a>
    </span>
    <span class="topbar-status-unreachable">
        <a href="<?= $this->href('monitoring/list/hosts', array('host_severity' => 68)); ?>" title="Hosts Unreachable Unhandled">
            <?= $hostSummary->hosts_unreachable_unhandled ?>
        </a>/
        <a href="<?= $this->href('monitoring/list/hosts', array('host_severity' => array(65, 66))); ?>" title="Hosts Unreachable Handled">
            <?= $hostSummary->hosts_unreachable_handled ?>
        </a>
    </span>
    <span class="topbar-status-pending">
        <a href="<?= $this->href('monitoring/list/hosts', array('host_severity' => 20)); ?>" title="Hosts Pending">
            <?= $hostSummary->hosts_pending ?>
        </a>
    </span>
</div>

<div class="nav navbar-nav topbar-service-status-summary">
    <span class="topbar-status-ok">
        <a href="<?= $this->href('monitoring/list/services', array('service_severity' => 4)); ?>" title="Services Ok">
            <?= $serviceSummary->services_ok ?>
        </a>
    </span>
    <span class="topbar-status-critical">
        <a href="<?= $this->href('monitoring/list/services', array('service_severity' => 132)); ?>" title="Services Critical Unhandled">
            <?= $serviceSummary->services_critical_unhandled ?>
        </a>/
        <a href="<?= $this->href('monitoring/list/services', array('service_severity' => array(129, 130))); ?>" title="Services Critical Handled">
            <?= $serviceSummary->services_critical_handled ?>
        </a>
    </span>
    <span class="topbar-status-warning">
        <a href="<?= $this->href('monitoring/list/services', array('service_severity' => 36)); ?>" title="Services Warning Unhandled">
            <?= $serviceSummary->services_warning_unhandled ?>
        </a>/
        <a href="<?= $this->href('monitoring/list/services', array('service_severity' => array(33, 34))); ?>" title="Services Warning Handled">
            <?= $serviceSummary->services_warning_handled ?>
        </a>
    </span>
    <span class="topbar-status-unknown">
        <a href="<?= $this->href('monitoring/list/services', array('service_severity' => 68)); ?>" title="Services Unknown Unhandled">
            <?= $serviceSummary->services_unknown_unhandled ?>
        </a>/
        <a href="<?= $this->href('monitoring/list/services', array('service_severity' => array(65, 66))); ?>" title="Services Unknown Handled">
            <?= $serviceSummary->services_unknown_handled ?>
        </a>
    </span>
    <span class="topbar-status-pending">
        <a href="<?= $this->href('monitoring/list/services', array('service_severity' => 20)); ?>" title="Services Pending">
            <?= $serviceSummary->services_pending ?>
        </a>
    </span>
</div>
