<?php if (Icinga\Authentication\Manager::getInstance()->isAuthenticated()): ?>
<div id="layout">
 <div id="header">
 <ul id="notifications"></ul>
 </div>
 <div id="inner-layout">
 <div id="sidebar">
  <?= $this->layout()->navigation ?>
  <?php echo $this->render('parts/navigation.phtml') ?>
 </div>
 <div id="main">
  <div id="col1" class="container">
   <?= $this->render('inline.phtml') ?>
  </div>
  <div id="col2" class="container">
   <ul class="tabs"></ul>
  </div>
  <div id="col3" class="container">
  </div>
 </div><!-- END of main -->
</div><!-- END of inner-layout -->
</div><!-- END of layout -->
<?php else: ?>
<?= $this->render('inline.phtml') ?>
<?php endif ?>

