<?php

use ipl\I18n\Locale;
use ipl\I18n\GettextTranslator;
use ipl\I18n\StaticTranslator;

/** @var GettextTranslator $translator */
$translator = StaticTranslator::$instance;

$lang = (new Locale())->parseLocale($translator->getLocale())->language;
$showFullscreen = $this->layout()->showFullscreen;
$innerLayoutScript = $this->layout()->innerLayout . '.phtml';

?><!DOCTYPE html>
<html class="no-js" lang="<?= $lang ?>">
<head>
    <meta charset="utf-8">
    <meta name="google" value="notranslate">
    <meta http-equiv="cleartype" content="on">
    <title><?= $this->title ? $this->escape($this->title) : $this->defaultTitle ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Icinga Web 2">
    <meta name="apple-mobile-web-app-title" content="Icinga">
    <link rel="mask-icon" href="<?= $this->baseUrl('img/website-icon.svg') ?>" color="#0096BF">
    <link type="image/png" rel="shortcut icon" href="<?= $this->baseUrl('img/favicon.png') ?>" />
    <link rel="apple-touch-icon" href="<?= $this->baseUrl('img/touch-icon.png') ?>">
</head>
<body id="body">
<div id="layout" class="default-layout<?php if ($showFullscreen): ?> fullscreen-layout<?php endif ?>">
    <?= $this->render($innerLayoutScript); ?>
</div>
</body>
</html>
