<?php

use Icinga\Web\JavaScript;

?><!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title><?= $this->title ? $this->escape($this->title) : 'Icinga Web' ?></title>
  <!-- TODO: viewport and scale settings make no sense for us, fix this -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="<?= $this->href('css/icinga.min.css') ?>" media="screen" type="text/css" />
  <? if (isset($_GET['iframe']) && $_GET['iframe'] === 'true'): ?>
  <base target="_parent"/>
  <? endif ?>
  <!-- Respond.js IE8 support of media queries -->
  <!--[if lt IE 9]>
  <script src="<?= $this->baseUrl('js/vendor/respond.min.js');?>"></script>
  <![endif]-->

</head>
<body id="body">
<pre id="responsive-debug"></pre>
<div id="layout" class="default-layout">
<?= $this->render('body.phtml') ?>
</div>
<script type="text/javascript" src="<?= $this->href('js/icinga.min.js') ?>"></script>
<script type="text/javascript">
var icinga = new Icinga({
  baseUrl: '<?= $this->href('/') ?>',
});
</script>
</body>
</html>
