<?php

use Icinga\Web\JavaScript;

if (array_key_exists('_dev', $_GET)) {
  $jsfile  = 'js/icinga.dev.js';
  $cssfile = 'css/icinga.css';
} else {
  $jsfile  = 'js/icinga.min.js';
  $cssfile = 'css/icinga.min.css';
}

$isIframe = isset($_GET['_render']) && $_GET['_render'] === 'iframe';

?><!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js<?= $isIframe ? ' iframe' : '' ?>"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
  <meta name="google" value="notranslate">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title><?= $this->title ? $this->escape($this->title) : 'Icinga Web' ?></title>
  <!-- TODO: viewport and scale settings make no sense for us, fix this -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="<?= $this->href($cssfile) ?>" media="screen" type="text/css" />
  <script type="text/javascript">
  (function() {
    var html = document.getElementsByTagName('html')[0];
    html.className = html.className.replace(/no-js/, 'js');
  }());
  </script>
  <? if ($isIframe): ?>
  <base target="_parent"/>
  <? endif ?>
  <!-- Respond.js IE8 support of media queries -->
  <!--[if lt IE 9]>
  <script src="<?= $this->baseUrl('js/vendor/respond.min.js');?>"></script>
  <![endif]-->

</head>
<body id="body">
<pre id="responsive-debug"></pre>
<div id="layout" class="default-layout">
<?= $this->render('body.phtml') ?>
</div>
<script type="text/javascript" src="<?= $this->href($jsfile) ?>"></script>
<script type="text/javascript">
var icinga = new Icinga({
  baseUrl: '<?= $this->href('/') ?>',
});
</script>
</body>
</html>
