<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title><?= $this->title ? $this->title : 'Icinga Web'; ?></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <!--      Bootstrap and components    -->
  <link rel="stylesheet" href="<?= $this->baseUrl('static/stylesheet') ?>" media="screen">

  <? if (isset($_GET['iframe']) && $_GET['iframe'] === 'true'): ?>
  <base target="_parent"/>
  <? endif ?>

  <script src="<?= $this->baseUrl('js/vendor/modernizr-2.6.2.min.js') ?>"></script>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="<?= $this->baseUrl('js/vendor/html5shiv.js');?>"></script>
  <script src="<?= $this->baseUrl('js/vendor/respond.min.js');?>"></script>

  <![endif]-->

</head>
<body class="login">

  <div class="logo-container">
    <div class="image-container">
      <div class="hidden-xs">
        <img src="<?= $this->baseUrl('img/logo_icinga_big.png') ?>" width="400px">
      </div>
      <div class="hidden-sm hidden-lg hidden-md">
        <img src="<?= $this->baseUrl('img/logo_icinga_big.png') ?>" width="200px">
      </div>
    </div>
  </div>
  <div class="form-container">
    <?= $this->layout()->content; ?>
    <div class="footer">
      <br/>
      Icinga Web 2 &copy; 2013 Icinga Team
    </div>
  </div>
</body>
</html>
