<?php

use Icinga\Data\Extensible;
use Icinga\Data\Updatable;
use Icinga\Data\Selectable;

$extensible = $this->hasPermission('config/authentication/groups/add') && $backend instanceof Extensible;

$editLink = null;
if ($this->hasPermission('config/authentication/groups/edit') && $backend instanceof Updatable) {
    $editLink = $this->qlink(
        null,
        'group/edit',
        array(
            'backend'   => $backend->getName(),
            'group'     => $group->group_name
        ),
        array(
            'title' => sprintf($this->translate('Edit group %s'), $group->group_name),
            'class' => 'group-edit',
            'icon'  => 'edit'
        )
    );
}

?>
<div class="controls">
 <?php if (! $this->compact): ?>
  <?= $tabs; ?>
 <?php endif ?>
  <h2 class="clearfix"><?= $this->escape($group->group_name) ?><span class="pull-right"><?= $editLink ?></span></h2>
  <table class="name-value-table">
    <tr>
      <th><?= $this->translate('Created at'); ?></th>
      <td><?= $group->created_at === null ? '-' : $this->formatDateTime($group->created_at); ?></td>
    </tr>
    <tr>
      <th><?= $this->translate('Last modified'); ?></th>
      <td><?= $group->last_modified === null ? '-' : $this->formatDateTime($group->last_modified); ?></td>
    </tr>
  </table>
  <h2><?= $this->translate('Members'); ?></h2>
<?php if (! $this->compact): ?>
  <?= $this->sortBox; ?>
<?php endif ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
<?php if (! $this->compact): ?>
  <?= $this->filterEditor; ?>
<?php endif ?>
</div>
<div class="content members" data-base-target="_next">
<?php if ($extensible): ?>
    <?= $this->qlink(
        $this->translate('Add User to Group') ,
        'group/addmember',
        null,
        array(
            'class'             => 'button-link',
            'data-base-target'  => '_next',
            'icon'              => 'plus',
            'title'             => $this->translate('Add user to group')
        )
    ) ?>
<?php endif ?>

<?php

$firstRow = true;
foreach ($members as $member): ?>
<?php if ($firstRow): ?>
  <?php $firstRow = false; ?>
  <table data-base-target="_next" class="action-table listing-table">
    <thead>
      <tr>
        <th class="member-name"><?= $this->translate('Username'); ?></th>
       <?php if (isset($removeForm)): ?>
        <th class="member-remove"><?= $this->translate('Remove'); ?></th>
       <?php endif ?>
      </tr>
    </thead>
    <tbody>
  <?php endif ?>
      <tr>
        <td class="member-name">
        <?php if (
          $this->hasPermission('config/authentication/users/show')
          && method_exists($backend, 'getUserBackend')
          && ($userBackend = $backend->getUserBackend()) !== null
          && $userBackend instanceof Selectable
        ): ?>
          <?= $this->qlink($member->user_name, 'user/show', array(
            'backend' => $userBackend->getName(),
            'user'    => $member->user_name
          ), array(
            'title'   => sprintf($this->translate('Show detailed information about %s'), $member->user_name)
          )); ?>
        <?php else: ?>
          <?= $this->escape($member->user_name); ?>
        <?php endif ?>
        </td>
       <?php if (isset($removeForm)): ?>
        <td class="icon-col" data-base-target="_self">
          <?php $removeForm->getElement('user_name')->setValue($member->user_name); echo $removeForm; ?>
        </td>
       <?php endif ?>
      </tr>
<?php endforeach ?>
<?php if ($members->hasResult()): ?>
    </tbody>
  </table>
<?php else: ?>
  <p><?= $this->translate('No group member found matching the filter'); ?></p>
<?php endif ?>
</div>
