<div class="content">
    <div>
        <h1><?= $this->translate('Roles') ?></h1>
        <?php /** @var \Icinga\Application\Config $roles */ if ($roles->isEmpty()): ?>
            <?= $this->translate('No roles found.') ?>
        <?php else: ?>
            <table class="action" data-base-target="_next">
                <thead>
                <tr>
                    <th><?= $this->translate('Name') ?></th>
                    <th><?= $this->translate('Permissions') ?></th>
                    <th><?= $this->translate('Users') ?></th>
                    <th><?= $this->translate('Groups') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($roles as $name => $role): /** @var object $role */ ?>
                    <tr>
                        <td>
                            <?= $this->escape($name) ?>
                            <div class="hidden">
                                <a href="<?= $this->url('security/update-role', array('role' => $name)) ?>"></a>
                            </div>
                        </td>
                        <td><?= $this->escape($role->permissions) ?></td>
                        <td><?= $this->escape($role->users) ?></td>
                        <td><?= $this->escape($role->groups) ?></td>
                        <td>
                            <a href="<?= $this->url('security/remove-role', array('role' => $name)) ?>">
                                <?= $this->translate('Remove role') ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        <?php endif ?>
        <a data-base-target="_next" href="<?= $this->href('security/new-role') ?>">
            <?= $this->translate('New Role') ?>
        </a>
    </div>
</div>
