<?php

use Icinga\Web\Wizard;

$form->getElement(Wizard::BTN_NEXT)->setAttrib(
    'class',
    $form->getElement(Wizard::BTN_NEXT)->getAttrib('class') . ' finish'
);

?>
<p><?= sprintf(
  $this->translate(
    'You\'ve configured %1$s successfully. You can review the changes supposed to be made before setting it up.'
    . ' Make sure that everything is correct (Feel free to navigate back to make any corrections!) so'
    . ' that you can start using %1$s right after it has successfully been set up.'
  ),
  $form->getSubjectTitle()
); ?></p>
<div class="summary">
<?php foreach ($form->getSummary() as $pageHtml): ?>
 <?php if ($pageHtml): ?>
  <div class="page">
    <?= $pageHtml; ?>
  </div>
 <?php endif ?>
<?php endforeach ?>
</div>
<form
 id="<?= $form->getName(); ?>"
 name="<?= $form->getName(); ?>"
 enctype="<?= $form->getEncType(); ?>"
 method="<?= $form->getMethod(); ?>"
 action="<?= $form->getAction(); ?>"
 data-progress-element="<?= Wizard::PROGRESS_ELEMENT; ?>"
 class="summary"
>
  <?= $form->getElement($form->getTokenElementName()); ?>
  <?= $form->getElement($form->getUidElementName()); ?>
  <?= $form->getDisplayGroup('buttons'); ?>
</form>