<?php

use Icinga\Web\Wizard;

$requirements = $form->getRequirements();
echo $requirements;

?>
<div class="buttons requirements-refresh">
  <?php $title = $this->translate('You may also need to restart the web-server for the changes to take effect!'); ?>
  <?= $this->qlink(
    $this->translate('Refresh'),
    null,
    null,
    array(
      'class'       => 'button-like',
      'title'       => $title,
      'aria-label'  => sprintf($this->translate('Refresh the page; %s'), $title)
    )
  ); ?>
</div>
<form id="<?= $form->getName(); ?>" name="<?= $form->getName(); ?>" enctype="<?= $form->getEncType(); ?>" method="<?= $form->getMethod(); ?>" action="<?= $form->getAction(); ?>">
  <?= $form->getElement($form->getTokenElementName()); ?>
  <?= $form->getElement($form->getUidElementName()); ?>
  <div class="buttons">
    <?= $form->getElement(Wizard::BTN_PREV); ?>
    <?php
      $btn = $form->getElement(Wizard::BTN_NEXT);
      if (! $requirements->fulfilled()) {
          $btn->setAttrib('disabled', 1);
      }
      echo $btn;
    ?>
  </div>
</form>