<div class="controls">
   
  <?php if (! $this->compact): ?>
    <?= $this->tabs; ?>
  <?php endif ?>

  <?= $this->render('partials/downtime/downtimes-header.phtml'); ?> 
</p>
</div>
<div class="content">
  <h3><?= $this->icon('reschedule') ?> <?= $this->translate('Commands') ?> </h3>
  <p>
    <?= sprintf(
            $this->translate('Issue commands to all %s selected downtimes.'),
            '<b>' . count($downtimes) . '</b>'
        )
    ?>
    <div>
    <?= $this->qlink(
        sprintf(
            $this->translate('Remove all %d scheduled downtimes'),
            count($downtimes)
        ),
        $removeAllLink,
        null,
        array(
            'icon' => 'trash',
            'title' => $this->translate('Remove all selected downtimes.')
        )
    ) ?>
    </div>
  </p>
</div>
