<div class="controls">
  <?php if (! isset($downtimes)): ?>
    <?= $this->translate('No scheduled downtimes matching the filter.') ?>
    </div>
    <?php return; ?>
  <?php endif; ?>
   
  <?php if (! $this->compact): ?>
    <?= $this->tabs; ?>
  <?php endif ?>
<p>
  <table class="action">
    <tbody>
    <?php $i = 0; foreach ($downtimes as $downtime):
        if (++ $i > 5) {
            continue;
        } ?>
        <tr class="state <?= $downtime->stateText ?>">
          <td class="state">
            <strong><?= $downtime->is_in_effect ? $this->translate('Expires') : $this->translate('Starts'); ?></strong>
            <br>
            <?=
                $this->dateTimeRenderer(
                    ($downtime->is_in_effect ? $downtime->end : $downtime->start),
                    true
                )->render(
                    $this->translate('on %s', 'datetime'),
                    $this->translate('at %s', 'time'),
                    $this->translate('in %s', 'timespan')
                );
            ?>
          </td>
          <td class="name oneline">
            <?php if ($downtime->isService): ?>
                <?= $this->icon('service', $this->translate('Service')) ?>
                <b><?= $downtime->service ?> on <?= $downtime->host_name ?>.</b>
            <?php else: ?>
                 <?= $this->icon('host', $this->translate('Host')) ?>
                <b><?= $downtime->host_name ?>.</b>
            <?php endif; ?>
                
            <?php if ($downtime->is_flexible): ?>
              <?php if ($downtime->is_in_effect): ?>
                <?= sprintf(
                  $this->isService
                    ? $this->translate('This flexible service downtime was started on %s at %s and lasts for %s until %s at %s.')
                    : $this->translate('This flexible host downtime was started on %s at %s and lasts for %s until %s at %s.'),
                  date('d.m.y', $downtime->start),
                  date('H:i', $downtime->start),
                  $this->format()->duration($downtime->duration),
                  date('d.m.y', $downtime->end),
                  date('H:i', $downtime->end)
                ); ?>
              <?php else: ?>
                <?= sprintf(
                  $this->isService
                    ? $this->translate('This flexible service downtime has been scheduled to start between %s - %s and to last for %s.')
                    : $this->translate('This flexible host downtime has been scheduled to start between %s - %s and to last for %s.'),
                  date('d.m.y H:i', $downtime->scheduled_start),
                  date('d.m.y H:i', $downtime->scheduled_end),
                  $this->format()->duration($downtime->duration)
                ); ?>
              <?php endif ?>
            <?php else: ?>
              <?php if ($downtime->is_in_effect): ?>
                <?= sprintf(
                  $this->isService
                    ? $this->translate('This fixed service downtime was started on %s at %s and expires on %s at %s.')
                    : $this->translate('This fixed host downtime was started on %s at %s and expires on %s at %s.'),
                  date('d.m.y', $downtime->start),
                  date('H:i', $downtime->start),
                  date('d.m.y', $downtime->end),
                  date('H:i', $downtime->end)
                ); ?>
              <?php else: ?>
                <?= sprintf(
                  $this->isService
                    ? $this->translate('This fixed service downtime has been scheduled to start on %s at %s and to end on %s at %s.')
                    : $this->translate('This fixed host downtime has been scheduled to start on %s at %s and to end on %s at %s.'),
                  date('d.m.y', $downtime->scheduled_start),
                  date('H:i', $downtime->scheduled_start),
                  date('d.m.y', $downtime->scheduled_end),
                  date('H:i', $downtime->scheduled_end)
                ); ?>
              <?php endif ?>
            <?php endif ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
  </table>
  <p> 
    <?= $this->qlink(
        sprintf($this->translate('List all %d downtimes …'), count($downtimes)),
        $listAllLink,
        null,
        array(
            'title' => $this->translate('List all'),
            'data-base-target' => "_next"
        )
    ) ?>
  </p>
</p>
</div>
<div class="content">
  <h3><?= $this->icon('reschedule') ?> <?= $this->translate('Commands') ?> </h3>
  <p>
    <?= sprintf(
            $this->translate('Issue commands to all %s selected downtimes.'),
            '<b>' . count($downtimes) . '</b>'
        )
    ?>
    <div>
    <?= $this->qlink(
        sprintf(
            $this->translate('Remove all %d scheduled downtimes'),
            count($downtimes)
        ),
        $removeAllLink,
        null,
        array(
            'icon' => 'trash',
            'title' => $this->translate('Remove all selected downtimes.')
        )
    ) ?>
    </div>
  </p>
</div>
