<?php
$contactHelper = $this->getHelper('ContactFlags');
?>
<div style="margin-top: 0.5em;">
    <?php foreach ($contacts as $contact): ?>
        <table style="border-spacing: 0.25em; border-collapse: separate;">
            <thead>
            <tr>
                <th colspan="2" style="text-align: left">
                    <?= $this->escape($contact->contact_name) ?><span style="font-weight: normal;"> (<?=
                        $this->escape($contact->contact_alias)
                        ?>)</span>
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><?= t('Email') ?></td>
                <td><?php printf(
                        '<a href="mailto:%1$s">%1$s</a>',
                        $this->escape($contact->contact_email)
                    ); ?></td>
            </tr>
            <?php if ($contact->contact_pager): ?>
                <tr>
                    <td><?= t('Pager') ?></td>
                    <td><?= $this->escape($contact->contact_pager) ?></td>
                </tr>
            <?php endif; ?>
            <tr>
                <td><?= t('Flags (service)') ?></td>
                <td><?= $this->escape($contactHelper->contactFlags($contact, 'service')) ?></td>
            </tr>
            <tr>
                <td><?= t('Flags (host)') ?></td>
                <td><?= $this->escape($contactHelper->contactFlags($contact, 'host')) ?></td>
            </tr>
            <tr>
                <td><?= t('Service notification period') ?></td>
                <td><?= $this->escape($contact->contact_notify_service_timeperiod) ?></td>
            </tr>
            <tr>
                <td><?= t('Host notification period') ?></td>
                <td><?= $this->escape($contact->contact_notify_host_timeperiod) ?></td>
            </tr>
            </tbody>
        </table>
        <?php
        return;
    endforeach;
    printf(
        '%s: `%s\'',
        t('No such contact'), $contact_name
    );
    ?>
</div>
