<div class="panel panel-default">
    <div class="panel-heading">
        <?php if ($this->object->host_icon_image): ?>
            <img src="<?= $this->object->host_icon_image; ?>" alt="Host image" />
        <?php else: ?>
            {{HOST_ICON}}
        <?php endif; ?>
        <h1>Host Status <?= $this->escape($this->object->host_name); ?></h1>
    </div>

    <div class="panel-body">
        <table>
            <tr>
                <?php if (!$object->host_handled && $object->host_state > 0): ?>
                <td>
                    <a href="#" title="Unhandled">
                        <i>{{UNHANDLED_ICON}}</i>
                    </a>
                    <a href="#" title="Acknowledge">
                        <i>{{ACKNOWLEDGE_COMMAND}}</i>
                    </a>
                </td>
                <?php endif; ?>
                <?php if ($object->service_acknowledged && !$object->service_in_downtime): ?>
                <td>
                    <a href="#" title="Acknowledged">
                        <i>{{ACKNOWLEDGED_ICON}}</i>
                    </a>
                </td>
                <?php else: ?>
                    <td>
                        Status
                    </td>
                <?php endif; ?>
                <td>
                    <?= $this->util()->getHostStateName($this->object->host_state); ?>
                    since <?= $this->timeSince($this->object->host_last_state_change); ?>
                </td>
                <td><a class="button" href="#">{{RECHECK_COMMAND_BUTTON}</a></td>
            </tr>
            <tr>
                <td>Last Check</td>
                <td><?= $object->last_check ?></td>
            </tr>
            <tr>
                <td>Next Check</td>
                <td><?= $object->next_check ?></td>
                <td><a href="#" class="button">{{RESCHEDULE_COMMAND_BUTTON}}</a></td>
            </tr>
            <?php if ($this->object->host_address && $this->object->host_address !== $this->object->host_name): ?>
            <tr>
                <td>Host Address</td>
                <td><?= $this->escape($this->object->host_address); ?></td>
            </tr>
            <?php endif; ?>
            <?php if (isset($this->object->host_alias) && $this->object->host_alias !== $this->object->host_name): ?>
            <tr>
                <td>Alias</td>
                <td><?= $this->object->host_alias; ?></td>
            <?php endif; ?>
            <?php if ($this->object->host_action_url || $this->object->host_notes_url): ?>
                <tr>
                    <td rowspan="2">
                        <?php if ($this->object->host_action_url): ?>
                            <a target="_new" href='<?= $this->object->host_notes_url ?>'>{{HOST_ACTIONS_ICON}}</a>
                        <?php endif; ?>
                        <?php if ($this->object->host_notes_url): ?>
                            <a target="_new" href='<?= $this->object->host_notes_url ?>'>{{HOST_NOTES_ICON}}</a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endif; ?>
            <tr>
                <td>Plugin Output</td>
                <td>
                    <?= $this->pluginOutput($this->object->output); ?>
                    <?= $this->pluginOutput($this->object->long_output); ?>
                </td>
                <td>
                    <a class="button" href="#">{{SUBMIT_PASSIVE_CHECK_RESULT_COMMAND}}</a>
                </td>
            </tr>
            <?php if ($this->object->perfdata): ?>
                <tr>
                    <td>Performance Data</td>
                    <td><?= $this->perfdata($this->object->perfdata); ?></td>
                </tr>
            <?php endif; ?>
            <tr>
                <td colspan="2">
                    <a href="<?= $this->href('monitoring/list/services', array('host' => $object->host_name)); ?>">
                        View Services For This Host
                    </a>
                </td>
                <td>
                    <a class="button" href="#">{{{RECHECK_ALL_SERVICES_COMMAND}}</a>
                </td>
            </tr>
        </table>
    </div>
</div>

<?= $this->render('show/components/downtime.phtml'); ?>

<?= $this->render('show/components/comments.phtml'); ?>

<?= $this->render('show/components/properties.phtml'); ?>

<?= $this->render('show/components/flags.phtml'); ?>

<?= $this->render('show/components/hostgroups.phtml'); ?>

<?= $this->render('show/components/eventHistory.phtml'); ?>

<?= $this->render('show/components/contacts.phtml'); ?>

<?= $this->render('show/components/customvars.phtml'); ?>

<?= $this->render('show/components/command.phtml'); ?>
