<?= $this->tabs->render($this); ?>

<div>
    <div class="row">
        <div class="col-md-8">
        <?php if ($this->object->host_icon_image): ?>
            <img src="<?= $this->object->host_icon_image; ?>" alt="Host image" />
        <?php else: ?>
            {{HOST_ICON}}
        <?php endif; ?>
        <h4>
            Host Status
            <a href="<?= $this->href('monitoring/list/services', array('host' => $object->host_name)); ?>">
                <?= $this->escape($this->object->host_name); ?>
            </a>
            <?php if ($this->object->host_address && $this->object->host_address !== $this->object->host_name): ?>
                (<?= $this->object->host_address; ?>)
            <?php endif; ?>
            <?php if (isset($this->object->host_alias) && $this->object->host_alias !== $this->object->host_name): ?>
                (<?= $this->object->host_alias; ?>)
            <?php endif; ?>
        </h4>
        </div>
        <div class="col-md-4">
            <?= $this->util()->getHostStateName($this->object->host_state); ?>
            since <?= $this->timeSince($this->object->host_last_state_change); ?>
        </div>
    </div>

    <div>
        <?= $this->pluginOutput($this->object->output); ?>
    </div>

    <a class="button" href="#">{{RECHECK_COMMAND}</a>

    <div>
        <?= $this->perfdata($this->object->perfdata); ?>
    </div>

    <div>
        <?= $this->pluginOutput($this->object->long_output); ?>
    </div>

    <?= $this->render('show/components/comments.phtml'); ?>

    <div>
        Check Statistics
        <dl class="dl-horizontal">
            <dt>Last Check</dt>
            <dd><?= $object->last_check; ?></dd>
            <dt>Next Check</dt>
            <dd><?= $object->next_check; ?> <a href="#" class="button">{{RESCHEDULE_COMMAND}}</a></dd>
        </dl>
    </div>

    <div>
        <table>
            <i class="successIcon"></i>
            <tr>
                <?php if (!$object->host_handled && $object->host_state > 0): ?>
                <td>
                    <a href="#" title="Unhandled">
                        <i>{{UNHANDLED_ICON}}</i>
                    </a>
                    <a href="#" title="Acknowledge">
                        <i>{{ACKNOWLEDGE_COMMAND}}</i>
                    </a>
                </td>
                <?php endif; ?>
                <?php if ($object->service_acknowledged && !$object->service_in_downtime): ?>
                <td>
                    <a href="#" title="Acknowledged">
                        <i>{{ACKNOWLEDGED_ICON}}</i>
                    </a>
                </td>
                <?php endif; ?>
            </tr>
            <tr>
                <td>Last Check</td>
                <td></td>
            </tr>
            <tr>
                <td>Next Check</td>
                <td></td>
                <td></td>
            </tr>

            <tr>
            <?php if ($this->object->host_action_url || $this->object->host_notes_url): ?>
                <tr>
                    <td rowspan="2">
                        <?php if ($this->object->host_action_url): ?>
                            <a target="_new" href='<?= $this->object->host_notes_url ?>'>{{HOST_ACTIONS_ICON}}</a>
                        <?php endif; ?>
                        <?php if ($this->object->host_notes_url): ?>
                            <a target="_new" href='<?= $this->object->host_notes_url ?>'>{{HOST_NOTES_ICON}}</a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($this->object->perfdata): ?>
                <tr>
                    <td>Performance Data</td>
                    <td><?= $this->perfdata($this->object->perfdata); ?></td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
</div>

<?= $this->render('show/components/downtime.phtml'); ?>

<?= $this->render('show/components/properties.phtml'); ?>

<?= $this->render('show/components/flags.phtml'); ?>

<?= $this->render('show/components/hostgroups.phtml'); ?>

<?= $this->render('show/components/eventHistory.phtml'); ?>

<?= $this->render('show/components/contacts.phtml'); ?>

<?= $this->render('show/components/customvars.phtml'); ?>

<?= $this->render('show/components/command.phtml'); ?>
