<?= $this->tabs->render($this); ?>

<?php if (isset($this->success)) : ?>
<div class="alert alert-success">
    <h4>Preferences updated sucessfully</h4>
</div>
<?php endif; ?>

<?php if (isset($this->exceptionMessage)): ?>
<div class="alert alert-danger">
    <h4>Could not update preferences due to an internal exception (<?= $this->exceptionMessage ?>)</h4>
</div>
<?php endif; ?>

<?= $this->form ?>