<?php
use Icinga\Module\Monitoring\Object\Host;
use Icinga\Module\Monitoring\Object\Service;
/** @var \Icinga\Module\Monitoring\Object\MonitoredObject $object */
?>
<table>
    <tr>
        <td class="state-col state-<?= Host::getStateText($object->host_state) ?><?= $object->host_handled ? ' handled' : '' ?>">
            <p>
                <?= Host::getStateText($object->host_state, true) ?>
                <br>
                <?= $this->timeSince($object->host_last_state_change) ?>
            </p>
        </td>
        <td>
            <p>
                <?= $this->iconImage()->service($object) ?>
                <span class="selectable"><?= $this->escape($object->host_display_name) ?></span>
            <?php if ($object->host_display_name !== $object->host_name): ?>
                <span class="selectable text-small">&#40;<?= $this->escape($object->host_name) ?>&#41;</span>
            <?php endif ?>
            <?php if ($object->host_address6 && $object->host_address6 !== $object->host_name): ?>
                <br>
                <span class="selectable text-small" title="<?= $this->translate('IPv6 address') ?>">
                <?= $this->escape($object->host_address6) ?>
            </span>
            <?php endif ?>
            <?php if ($object->host_address && $object->host_address !== $object->host_name): ?>
                <br>
                <span class="selectable text-small" title="<?= $this->translate('IPv4 address') ?>">
                <?= $this->escape($object->host_address) ?>
            </span>
            <?php endif ?>
            <?= $this->render('partials/host/statusicons.phtml') ?>
            </p>
        </td>
    </tr>
    <tr>
        <td class="state-col state-<?= Service::getStateText($object->service_state) ?><?= $object->service_handled ? ' handled' : '' ?>">
            <p>
                <?= Service::getStateText($object->service_state, true) ?>
                <br>
                <?= $this->timeSince($object->service_last_state_change) ?>
            </p>
        </td>
        <td>
            <p>
                <?= $this->iconImage()->host($object) ?>
                <?= $this->translate('Service') ?>&#58; <span class="selectable"><?= $this->escape($object->service_display_name) ?></span>
            <?php if ($object->service_display_name !== $object->service_description): ?>
                <span class="selectable text-small">&#40;<?= $this->escape($object->service_description) ?>&#41;</span>
            <?php endif ?>
                <?= $this->render('partials/service/statusicons.phtml') ?>
            </p>
        </td>
    </tr>
</table>
