<div class="controls">
<?= $this->tabs ?>
</div>
<div class="content">
<?php if (isset($this->objects) && !empty($this->objects) && isset($this->objects[0]->host_name)): ?>
<table class="objectlist">
  <thead>
    <tr>
      <th><?= $this->icon('host') ?> Host</th>
      <th><?= $this->icon('conf') ?> Service</th>
    </tr>
  </thead>
    <tbody>
<?php foreach ($this->objects as $object): ?>
      <tr>
        <td><?= $object->host_name; ?></td>
        <td><?= (isset($object->service_description) ? $object->service_description : '') ?></td>
      </tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php endif ?>
<?= $this->form ?>
</div>
