
<?php if (isset($this->objects) && !empty($this->objects) && isset($this->objects[0]->host_name)): ?>
<table class="table table-bordered table-striped table-condensed">
  <legend>Affected Objects</legend>
  <thead>
    <tr>
      <th>{{HOST_ICON}} Host Name</th>
      <th>{{SERVICE_ICON}} Service Name</th>
    </tr>
  </thead>
    <tbody>
<?php foreach ($this->objects as $object): ?>
      <tr>
        <td><?= $object->host_name; ?></td>
        <td><?= (isset($object->service_description) ? $object->service_description : ''); ?></td>
      </tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php endif; ?>

<?php if ($this->form): ?>
<div>
  <?= $this->form; ?>
  <div class="clearfix"></div>
</div>
<?php endif; ?>

