<?php if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <?= $this->sortBox; ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content">
    <?php if ($this->logData !== null): ?>
    <table class="action">
        <tbody>
            <?php foreach ($this->logData as $value): ?>
                <?php $datetime = new Datetime($value->datetime); ?>
                <tr class="state">
                    <td style="width: 6em; text-align: center">
                        <?= $this->escape($datetime->format('d.m. H:i')) ?><br />
                        <?= $this->escape($value->loglevel) ?>
                    </td>
                    <td>
                        <?= $this->escape($value->message) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</div>
