<?php if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <div class="grid dont-print">
        <div class="col-1-3 text-left">
            <?= $this->limiter ?>
        </div>
        <div class="col-1-3">
            <?= $this->paginator ?>
        </div>
        <div class="col-1-3 text-right">
            <?= $this->sortBox ?>
        </div>
    </div>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content">
    <?php if ($this->logData !== null): ?>
    <table class="action">
        <tbody>
            <?php foreach ($this->logData as $value): ?>
                <?php $datetime = new Datetime($value->datetime); ?>
                <tr class="state">
                    <td style="width: 6em; text-align: center">
                        <?= $this->escape($datetime->format('d.m. H:i')) ?><br />
                        <?= $this->escape($value->loglevel) ?>
                    </td>
                    <td>
                        <?= nl2br($this->escape($value->message), false) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</div>
