<?php
// {{{ICINGA_LICENSE_HEADER}}}
// {{{ICINGA_LICENSE_HEADER}}}

use Icinga\Module\Monitoring\Controller as MonitoringController;
use Icinga\Module\Monitoring\DataView\StatusSummary;

class Monitoring_TacticalController extends MonitoringController
{
    public function indexAction()
    {
        $this->view->statusSummary = StatusSummary::fromRequest(
            $this->_request,
            array(
                'hosts_up',
                'hosts_up_not_checked',
                'hosts_pending',
                'hosts_pending_not_checked',
                'hosts_down',
                'hosts_down_handled',
                'hosts_down_unhandled',
                'hosts_down_passive',
                'hosts_down_not_checked',
                'hosts_unreachable',
                'hosts_unreachable_handled',
                'hosts_unreachable_unhandled',
                'hosts_unreachable_passive',
                'hosts_unreachable_not_checked',

                'services_ok_on_up_hosts',
                'services_ok_not_checked_on_up_hosts',
                'services_pending_on_up_hosts',
                'services_pending_not_checked_on_up_hosts',
                'services_warning_on_up_hosts',
                'services_warning_unhandled_on_up_hosts',
                'services_warning_passive_on_up_hosts',
                'services_warning_not_checked_on_up_hosts',
                'services_critical_on_up_hosts',
                'services_critical_unhandled_on_up_hosts',
                'services_critical_passive_on_up_hosts',
                'services_critical_not_checked_on_up_hosts',
                'services_unknown_on_up_hosts',
                'services_unknown_unhandled_on_up_hosts',
                'services_unknown_passive_on_up_hosts',
                'services_unknown_not_checked_on_up_hosts',
                'services_ok_on_down_hosts',
                'services_ok_not_checked_on_down_hosts',
                'services_pending_on_down_hosts',
                'services_pending_not_checked_on_down_hosts',
                'services_warning_on_down_hosts',
                'services_warning_unhandled_on_down_hosts',
                'services_warning_passive_on_down_hosts',
                'services_warning_not_checked_on_down_hosts',
                'services_critical_on_down_hosts',
                'services_critical_unhandled_on_down_hosts',
                'services_critical_passive_on_down_hosts',
                'services_critical_not_checked_on_down_hosts',
                'services_unknown_on_down_hosts',
                'services_unknown_unhandled_on_down_hosts',
                'services_unknown_passive_on_down_hosts',
                'services_unknown_not_checked_on_down_hosts',
                'services_ok_on_unreachable_hosts',
                'services_ok_not_checked_on_unreachable_hosts',
                'services_pending_on_unreachable_hosts',
                'services_pending_not_checked_on_unreachable_hosts',
                'services_warning_on_unreachable_hosts',
                'services_warning_unhandled_on_unreachable_hosts',
                'services_warning_passive_on_unreachable_hosts',
                'services_warning_not_checked_on_unreachable_hosts',
                'services_critical_on_unreachable_hosts',
                'services_critical_unhandled_on_unreachable_hosts',
                'services_critical_passive_on_unreachable_hosts',
                'services_critical_not_checked_on_unreachable_hosts',
                'services_unknown_on_unreachable_hosts',
                'services_unknown_unhandled_on_unreachable_hosts',
                'services_unknown_passive_on_unreachable_hosts',
                'services_unknown_not_checked_on_unreachable_hosts',
                'services_ok_on_pending_hosts',
                'services_ok_not_checked_on_pending_hosts',
                'services_pending_on_pending_hosts',
                'services_pending_not_checked_on_pending_hosts',
                'services_warning_on_pending_hosts',
                'services_warning_unhandled_on_pending_hosts',
                'services_warning_passive_on_pending_hosts',
                'services_warning_not_checked_on_pending_hosts',
                'services_critical_on_pending_hosts',
                'services_critical_unhandled_on_pending_hosts',
                'services_critical_passive_on_pending_hosts',
                'services_critical_not_checked_on_pending_hosts',
                'services_unknown_on_pending_hosts',
                'services_unknown_unhandled_on_pending_hosts',
                'services_unknown_passive_on_pending_hosts',
                'services_unknown_not_checked_on_pending_hosts',

                'hosts_active',
                'hosts_passive',
                'hosts_not_checked',
                'services_active',
                'services_passive',
                'services_not_checked',
                'hosts_not_processing_event_handlers',
                'services_not_processing_event_handlers',
                'hosts_not_triggering_notifications',
                'services_not_triggering_notifications',
                'hosts_without_flap_detection',
                'services_without_flap_detection',
                'hosts_flapping',
                'services_flapping'
            )
        )->getQuery()->fetchRow();
    }
}
