<div id="setup-finish">
 <?php if ($success): ?>
  <h2 class="success"><?= $this->translate('Congratulations! Icinga Web 2 has been successfully set up.'); ?></h2>
 <?php else: ?>
  <h2 class="failure"><?= $this->translate('Sorry! Failed to set up Icinga Web 2 successfully.'); ?></h2>
 <?php endif ?>
  <div class="buttons pull-right">
  <?php if ($success): ?>
    <?= $this->qlink(
        $this->translate('Login to Icinga Web 2'),
        'authentication/login?renderLayout',
        null,
        array(
            'class' => 'button-link login',
            'title' => $this->translate('Show the login page of Icinga Web 2')
        )
    ); ?>
  <?php else: ?>
    <?= $this->qlink(
        $this->translate('Back'),
        null,
        null,
        array(
            'class' => 'button-link',
            'title' => $this->translate('Show previous wizard-page')
        )
    ); ?>
  <?php endif ?>
  </div>
  <pre class="log-output"><?= join("\n\n", array_map(function($a) {
    return join("\n", $a);
  }, $report)); ?></pre>
</div>
