<div class="content">
    <h1>Icinga Web 2</h1>
    <?php
    $versionInfo = array();
    foreach (array(
        'appVersion'    => $this->translate('Version: %s'),
        'gitCommitID'   => $this->translate('Git commit ID: %s'),
        'gitCommitDate' => $this->translate('Git commit date: %s')
    ) as $key => $label) {
        if (array_key_exists($key, $version) && null !== ($value = $version[$key])) {
            $versionInfo[] = sprintf($label, htmlspecialchars($value));
        }
    }

    ?>
    <p><?= implode('<br>', $versionInfo) ?></p>
    <p>Copyright &copy; 2013-2015&emsp;<a href="https://www.icinga.org"><?=
        $this->translate('The Icinga Project')
    ?></a><br><?= $this->translate('License: GNU GPL v2 or later') ?></p>
    <p><a href="https://dev.icinga.org/projects/icingaweb2"><?=
        $this->translate('Report a bug')
    ?></a>&emsp;<a href="https://www.icinga.org/services/support/"><?=
        $this->translate('Support')
    ?></a>&emsp;<a href="https://wiki.icinga.org/dashboard.action"><?=
        $this->translate('Icinga Wiki')
    ?></a>&emsp;<a href="http://docs.icinga.org/"><?=
        $this->translate('Icinga Documentation')
    ?></a><br><a href="https://twitter.com/icinga"><?=
        $this->translate('Icinga on Twitter')
    ?></a>&emsp;<a href="https://www.facebook.com/icinga"><?=
        $this->translate('Icinga on Facebook')
    ?></a></p>
    <h1><?= $this->translate('Loaded modules') ?></h1>
    <table class="action alternating" data-base-target="_next">
      <thead>
        <tr>
          <th><?= $this->translate('Name') ?></th>
          <th><?= $this->translate('Version') ?></th>
        </tr>
      </thead>
      <tbody>
      <?php
      foreach ($modules as $module) {
        $name = $module->getName();
      ?>
        <tr>
          <td><?= $hasPermission ? $this->qlink(
            $name,
            'config/module/',
            array('name' => $name),
            array('title' => sprintf($this->translate('Show the overview of the %s module'), $name))
          ) : $name ?></td>
          <td><?= $module->getVersion() ?></td>
        </tr>
      <?php } ?>
      </tbody>
    </table>
</div>
