<div class="controls">
<?= $this->tabs ?>
</div>

<div class="content">
<h1>Header h1</h1>
<h2>Header h2</h2>
<h3>Header h3</h3>
<h4>Header h4</h4>
<h5>Header h5</h5>
<h6>Header h6</h6>

<p>This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. A <a href="#">link pointing somewhere</a>. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph.</p>

<table class="avp">
<thead>
  <tr>
    <th>Table Head - th in thead</th>
    <td>td in thead<td>
  </tr>
</thead>
<tbody>
  <tr>
    <th>Tbody - th</th>
    <td>Tbody - td</td>
  </tr>
  <tr>
    <th>Tbody - th</th>
    <td>Tbody - td</td>
  </tr>
  <tr>
    <th>Tbody - th</th>
    <td>Tbody - td</td>
  </tr>
</tbody>
</table>
</div>
