<?php
use Icinga\Data\Extensible;
use Icinga\Data\Reducible;

if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs ?>
    <div class="grid dont-print">
        <div class="col-1-3 text-left">
            <?= $this->limiter ?>
        </div>
        <div class="col-1-3">
            <?= $this->paginator ?>
        </div>
        <div class="col-1-3 text-right">
            <?= $this->sortBox ?>
        </div>
    </div>
    <div>
        <?= $this->backendSelection ?>
        <?= $this->filterEditor ?>
    </div>
</div>
<?php endif ?>

<div class="content">
<?php if (! isset($backend)): ?>
    <p><?= $this->translate('No backend found which is able to list users.') ?></p>
</div>
<?php return; endif ?>
<?php if (! $users->hasResult()): ?>
    <p><?= $this->translate('No users found matching the filter.') ?></p>
</div>
<?php return; endif ?>
<?php
$extensible = $this->hasPermission('config/authentication/users/add') && $backend instanceof Extensible;
$reducible = $this->hasPermission('config/authentication/users/remove') && $backend instanceof Reducible;
?>
<?php if ($extensible): ?>
    <?= $this->qlink(
        $this->translate('Add a New User') ,
        'user/add',
        array('backend' => $backend->getName()),
        array(
            'class'             => 'button-link',
            'data-base-target'  => '_next',
            'icon'              => 'plus',
            'title'             => $this->translate('Create a new user')
        )
    ) ?>
<?php endif ?>
    <table class="action-table listing-table" data-base-target="_next">
    <thead>
        <tr>
            <th><?= $this->translate('Username') ?></th>
        <?php if ($reducible): ?>
            <th><?= $this->translate('Remove') ?></th>
        <?php endif ?>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user): ?>
        <tr>
            <td><?= $this->qlink(
                $user->user_name,
                'user/show',
                array(
                    'backend'   => $backend->getName(),
                    'user'      => $user->user_name
                ),
                array(
                    'title'     => sprintf($this->translate('Show detailed information about %s'), $user->user_name)
                )
            ) ?></td>
        <?php if ($reducible): ?>
            <td class="icon-col"><?= $this->qlink(
                null,
                'user/remove',
                array(
                    'backend'   => $backend->getName(),
                    'user'      => $user->user_name
                ),
                array(
                    'class' => 'action-link',
                    'icon'  => 'cancel',
                    'title' => sprintf($this->translate('Remove user %s'), $user->user_name)
                )
            ) ?></td>
            <?php endif ?>
        </tr>
    <?php endforeach ?>
    </tbody>
    </table>
</div>
