<?php 

use Icinga\Data\Updatable;

$editLink = null;
if ($backend instanceof Updatable) {
    $editLink = $this->qlink(
        null,
        'user/edit',
        array(
            'backend'   => $backend->getName(),
            'user'      => $user->user_name
        ),
        array(
            'title' => sprintf($this->translate('Edit user %s'), $user->user_name),
            'class' => 'user-edit',
            'icon'  => 'edit'
        )
    );
}

?>
<div class="controls">
  <?php if (! $this->compact): ?>
    <?= $tabs->showOnlyCloseButton(); ?>
  <?php endif ?>
  <div class="user-header">
    <p class="user-name"><strong><?= $this->escape($user->user_name); ?></strong></p> <?= $editLink; ?>
    <p class="user-state"><strong><?= $this->translate('State'); ?>:</strong> <?= $user->is_active ? $this->translate('Active') : $this->translate('Inactive'); ?></p>
    <p class="user-created"><strong><?= $this->translate('Created at'); ?>:</strong> <?= $user->created_at === null ? '-' : $this->formatDateTime($user->created_at); ?></p>
    <p class="user-modified"><strong><?= $this->translate('Last modified'); ?>:</strong> <?= $user->last_modified === null ? '-' : $this->formatDateTime($user->last_modified); ?></p>
  </div>
</div>
<div class="content" data-base-target="_next">
</div>