<?php

use Icinga\Web\Url;
use Icinga\Data\Filter\Filter;

$this->baseFilter = isset($this->baseFilter) ? $this->baseFilter : null;

// don't fetch rows until they are actually needed to improve dashlet performance
if (!$stats instanceof stdClass) {
    $stats = $stats->fetchRow();
}

$selfUrl = 'monitoring/list/hosts';
$currentUrl = Url::fromRequest()->getRelativeUrl();
?>
  <?= $this->qlink(
      sprintf($this->translatePlural('%u Host', '%u Hosts', $stats->hosts_total), $stats->hosts_total),
      $selfUrl,
      null,
      array('title' => sprintf(
          $this->translatePlural('List %u host', 'List all %u hosts', $stats->hosts_total),
          $stats->hosts_total
      ))
  ) ?>&#58;
  <span class="badges">
    <?php if ($stats->hosts_up): ?>
    <span class="state ok<?= $currentUrl === Url::fromPath($selfUrl, array('host_state' => 0))->getRelativeUrl() ? ' active' : ''; ?>">
        <?= $this->qlink(
                $stats->hosts_up,
                Url::urlAddFilterOptional(
                    $selfUrl,
                    Filter::where('host_state', 0),
                    $this->baseFilter
                ),
                null,
                array('title' => sprintf(
                    $this->translatePlural(
                        'List %u host that is currently in state UP',
                        'List %u hosts which are currently in state UP',
                        $stats->hosts_up
                    ),
                    $stats->hosts_up
                )
            )
        ); ?>
    </span>
    <?php endif; ?>

    <?php if ($stats->hosts_down_unhandled): ?>
    <span class="state critical<?= $currentUrl === Url::fromPath($selfUrl, array('host_state' => 1, 'host_unhandled' => 1))->getRelativeUrl() ? ' active' : ''; ?>">
        <?= $this->qlink(
            $stats->hosts_down_unhandled,
            Url::urlAddFilterOptional(
                $selfUrl,
                Filter::matchAll(Filter::where('host_state', 1), Filter::where('host_unhandled', 1)),
                $this->baseFilter
            ),
            null,
            array('title' => sprintf(
                $this->translatePlural(
                    'List %u host that is currently in state DOWN',
                    'List %u hosts which are currently in state DOWN',
                    $stats->hosts_down_unhandled
                ),
                $stats->hosts_down_unhandled
            ))
        ); ?>
    <?php endif; ?>

    <?php if ($stats->hosts_down_handled): ?>
    <span class="state handled critical<?= $currentUrl === Url::fromPath($selfUrl, array('host_state' => 1, 'host_unhandled' =>0))->getRelativeUrl() ? ' active' : ''; ?>">
        <?= $this->qlink(
            $stats->hosts_down_handled,
            Url::urlAddFilterOptional(
                $selfUrl,
                Filter::matchAll(Filter::where('host_state', 1), Filter::where('host_unhandled', 0)),
                $this->baseFilter
            ),
            null,
            array('title' => sprintf(
                $this->translatePlural(
                    'List %u host that is currently in state DOWN (Acknowledged)',
                    'List %u hosts which are currently in state DOWN (Acknowledged)',
                    $stats->hosts_down_handled
                ),
                $stats->hosts_down_handled
            ))
        ); ?>
    </span>
    <?php endif; ?>

    <?php if($stats->hosts_down): ?>
    </span>
    <?php endif; ?>

    <?php if($stats->hosts_unreachable_unhandled): ?>
    <span class="state unknown<?= $currentUrl === Url::fromPath($selfUrl, array('host_state' => 2, 'host_unhandled' => 1))->getRelativeUrl() ? ' active' : ''; ?>">
        <?= $this->qlink(
            $stats->hosts_unreachable_unhandled,
            Url::urlAddFilterOptional(
                $selfUrl,
                Filter::matchAll(Filter::where('host_state', 2), Filter::where('host_unhandled', 1)),
                $this->baseFilter
            ),
            null,
            array('title' => sprintf(
                $this->translatePlural(
                    'List %u host that is currently in state UNREACHABLE',
                    'List %u hosts which are currently in state UNREACHABLE',
                    $stats->hosts_unreachable_unhandled
                ),
                $stats->hosts_unreachable_unhandled
            ))
        ); ?>
    <?php endif; ?>

    <?php if($stats->hosts_unreachable_handled > 0): ?>
    <span class="state handled unknown<?= $currentUrl === Url::fromPath($selfUrl, array('host_state' => 2, 'host_unhandled' => 0))->getRelativeUrl() ? ' active' : '' ?>">
        <?= $this->qlink(
            $stats->hosts_unreachable_handled,
            Url::urlAddFilterOptional(
                $selfUrl,
                Filter::matchAll(Filter::where('host_state', 2), Filter::where('host_unhandled', 0)),
                $this->baseFilter
            ),
            null,
            array('title' => sprintf(
                $this->translatePlural(
                    'List %u host that is currently in state UNREACHABLE (Acknowledged)',
                    'List %u hosts which are currently in state UNREACHABLE (Acknowledged)',
                    $stats->hosts_unreachable_handled
                ),
                $stats->hosts_unreachable_handled
            ))
        ); ?>
    </span>
    <?php endif; ?>

    <?php if($stats->hosts_unreachable): ?>
    </span>
    <?php endif; ?>

    <?php if($stats->hosts_pending): ?>
    <span class="state pending<?= $currentUrl === Url::fromPath($selfUrl, array('host_state' => 99))->getRelativeUrl() ? ' active' : ''; ?>">
        <?= $this->qlink(
            $stats->hosts_pending,
            Url::urlAddFilterOptional(
                $selfUrl,
                Filter::where('host_state', 99),
                $this->baseFilter
            ),
            null,
            array('title' => sprintf(
                $this->translatePlural(
                    'List %u host that is currently in state PENDING',
                    'List %u hosts which are currently in state PENDING',
                    $stats->hosts_pending
                ),
                $stats->hosts_pending
            ))
        ); ?>
    </span>
    <?php endif; ?>
  </span>
