<?php

use Icinga\Module\Monitoring\Web\Widget\StateBadges;

/* @var $hostGroup \Icinga\Module\Monitoring\DataView\Hostgroupsummary */

$stateBadges = new StateBadges();
$stateBadges
    ->setUrl('monitoring/list/services')
    ->setBaseFilter($this->filterEditor->getFilter())
    ->add(
        StateBadges::STATE_OK,
        $hostGroup->services_ok,
        array(
            'service_state'     => 0,
            'hostgroup_name'    => $hostGroup->hostgroup_name,
            'sort'              => 'service_severity'
        ),
        'List %u service that is currently in state OK on hosts in the host group "%s"',
        'List %u services which are currently in state OK on hosts in the host group "%s"',
        array($hostGroup->services_ok, $hostGroup->hostgroup_alias)
    )
    ->add(
        StateBadges::STATE_CRITICAL,
        $hostGroup->services_critical_unhandled,
        array(
            'service_state'         => 2,
            'service_acknowledged'  => 0,
            'service_in_downtime'   => 0,
            'host_problem'          => 0,
            'hostgroup_name'        => $hostGroup->hostgroup_name,
            'sort'                  => 'service_severity'
        ),
        'List %u service that is currently in state CRITICAL on hosts in the host group "%s"',
        'List %u services which are currently in state CRITICAL on hosts in the host group "%s"',
        array($hostGroup->services_critical_unhandled, $hostGroup->hostgroup_alias)
    )
    ->add(
        StateBadges::STATE_CRITICAL_HANDLED,
        $hostGroup->services_critical_handled,
        array(
            'service_state'     => 2,
            'service_handled'   => 1,
            'hostgroup_name'    => $hostGroup->hostgroup_name,
            'sort'              => 'service_severity'
        ),
        'List %u service that is currently in state CRITICAL (Acknowledged) on hosts in the host group "%s"',
        'List %u services which are currently in state CRITICAL (Acknowledged) on hosts in the host group "%s"',
        array($hostGroup->services_critical_handled, $hostGroup->hostgroup_alias)
    )
    ->add(
        StateBadges::STATE_UNKNOWN,
        $hostGroup->services_unknown_unhandled,
        array(
            'service_state'         => 3,
            'service_acknowledged'  => 0,
            'service_in_downtime'   => 0,
            'host_problem'          => 0,
            'hostgroup_name'        => $hostGroup->hostgroup_name,
            'sort'                  => 'service_severity'
        ),
        'List %u service that is currently in state UNKNOWN on hosts in the host group "%s"',
        'List %u services which are currently in state UNKNOWN on hosts in the host group "%s"',
        array($hostGroup->services_unknown_unhandled, $hostGroup->hostgroup_alias)
    )
    ->add(
        StateBadges::STATE_UNKNOWN_HANDLED,
        $hostGroup->services_unknown_handled,
        array(
            'service_state'     => 3,
            'service_handled'   => 1,
            'hostgroup_name'    => $hostGroup->hostgroup_name,
            'sort'              => 'service_severity'
        ),
        'List %u service that is currently in state UNKNOWN (Acknowledged) on hosts in the host group "%s"',
        'List %u services which are currently in state UNKNOWN (Acknowledged) on hosts in the host group "%s"',
        array($hostGroup->services_unknown_handled, $hostGroup->hostgroup_alias)

    )
    ->add(
        StateBadges::STATE_WARNING,
        $hostGroup->services_warning_unhandled,
        array(
            'service_state'         => 1,
            'service_acknowledged'  => 0,
            'service_in_downtime'   => 0,
            'host_problem'          => 0,
            'hostgroup_name'        => $hostGroup->hostgroup_name,
            'sort'                  => 'service_severity'
        ),
        'List %u service that is currently in state WARNING on hosts in the host group "%s"',
        'List %u services which are currently in state WARNING on hosts in the host group "%s"',
        array($hostGroup->services_warning_unhandled, $hostGroup->hostgroup_alias)
    )
    ->add(
        StateBadges::STATE_WARNING_HANDLED,
        $hostGroup->services_warning_handled,
        array(
            'service_state'     => 1,
            'service_handled'   => 1,
            'hostgroup_name'    => $hostGroup->hostgroup_name,
            'sort'              => 'service_severity'
        ),
        'List %u service that is currently in state WARNING (Acknowledged) on hosts in the host group "%s"',
        'List %u services which are currently in state WARNING (Acknowledged) on hosts in the host group "%s"',
        array($hostGroup->services_warning_handled, $hostGroup->hostgroup_alias)
    )
    ->add(
        StateBadges::STATE_PENDING,
        $hostGroup->services_pending,
        array(
            'service_state'     => 99,
            'hostgroup_name'    => $hostGroup->hostgroup_name,
            'sort'              => 'service_severity'
        ),
        'List %u service that is currently in state PENDING on hosts in the host group "%s"',
        'List %u services which are currently in state PENDING on hosts in the host group "%s"',
        array($hostGroup->services_pending, $hostGroup->hostgroup_alias)
    );

echo $stateBadges->render();
