<?php echo ($this->sub) ? '<ul>' : '<ul class="nav nav-stacked" role="navigation" id="icinganavigation">' ?>
    <?php foreach ($this->items as $item): ?>
        <li class="<?php echo ($this->sub) ? 'submenu ' : '' ; echo $item->getIconClass(); echo ($this->href($this->url) === $this->href($item->getUrl())) ? ' active' : ''; ?>">
            <?php if($item->getUrl()): ?>
                <a href="<?= $this->href($item->getUrl()); ?>">
            <?php endif; ?>
                <?= ($item->getIcon()) ? $this->img($item->getIcon(), array('height' => '16px', 'width' => '16px')) : ''; ?> <?= $item->getTitle();?>
            <?php if($item->getUrl()): ?>
                </a>
            <?php endif; ?>
            <?php if($item->hasChildren()) :
                echo $this->partial('parts/menu.phtml', array('items' => $item->getChildren(), 'sub' => true, 'url' => $this->url));
            endif; ?>
        </li>
    <?php endforeach; ?>
</ul>