<?php

use Icinga\Web\Url;
use Icinga\Web\Menu;
use Icinga\Web\MenuRenderer;

// Don't render a menu for unauthenticated users unless menu is auth aware
if (! $this->auth()->isAuthenticated()) {
    return;
}

?>
<div class="skip-links">
    <h1 class="sr-only"><?= t('Accessibility Skip Links'); ?></h1>
    <ul>
        <li>
            <a tabindex="0" href="#main"><?= t('Skip to Content'); ?></a>
        </li>
        <li>
            <?= $this->layout()->autoRefreshForm ?>
        </li>
    </ul>
</div>
<div  id="menu" data-last-update="-1" data-base-target="_main" class="container"
      data-icinga-url="<?= $this->href('layout/menu') ?>"  data-icinga-refresh="15">
    <?= $this->partial(
        'layout/menu.phtml',
        'default',
        array(
            'menuRenderer' => new MenuRenderer(
                Menu::load(),
                Url::fromRequest()->without('renderLayout')->getRelativeUrl()
            )
        )
    ) ?>
</div>
