<?php if ($docHtml === null): ?>
  <p>No documentation available.</p>
<?php else: ?>
  <div class="toc">
    <?= $this->partial(
      'layout/menu.phtml',
        'default',
        array(
          'items'   => $docToc->getChildren(),
          'sub'     => false,
          'url'     => ''
        )
      );
    ?>
    </div>
    <div class="doc">
      <?= $docHtml ?>
    </div>
<?php endif ?>
