<div class="controls">
<?= $this->tabs ?>
</div>

<div class="content" data-base-target="_next">
<?php

if (isset($this->messageBox)) {
    // TODO: Get rid of such boxes -> notifications?
    echo $this->messageBox->render();
}
?>

<p>
  <a href="<?= $this->href('/config/createAuthenticationBackend', array('type' => 'ldap')) ?>"><?= $this->icon('create.png'); ?> Create A New LDAP Authentication Backend</a>
  <br />
  <a href="<?= $this->href('/config/createAuthenticationBackend', array('type' => 'db'))   ?>"><?= $this->icon('create.png'); ?> Create A New DB Authentication Backend</a>
</p>

<table class="action">
 <thead>
  <th>Resource</th>
  <th style="width: 5em">Remove</th>
  <th style="width: 5em">Order</th>
 </thead>
 <tbody>
  <?php foreach ($this->backends as $backend): ?>
    <tr>
      <td class="action">
        <a href="<?= $this->href('config/editAuthenticationBackend', array('auth_backend' => $backend->name)) ?>">
          <?= $this->icon('edit.png') ?> <?= $this->escape($backend->name); ?>
        </a>
      </td>
      <td>
        <a href="<?= $this->href('config/removeAuthenticationBackend', array('auth_backend' => $backend->name)) ?>">
          <?= $this->icon('remove.png', 'Remove') ?>
        </a>
      </td>
      <td>
        <?= $backend->reorderForm; ?>
      </td>
    </tr>
  <?php endforeach; ?>
  </table>
</div>
