<?php
use Icinga\Web\Url;
$createLdapBackend = $this->href('/config/createAuthenticationBackend', array('type' => 'ldap'));
$createDbBackend = $this->href('/config/createAuthenticationBackend', array('type' => 'db'));
?>
<div>
<?= $this->tabs->render($this); ?>
</div>

<div>
<?php if (isset($this->messageBox)): ?>
  <?= $this->messageBox->render() ?>
<?php endif ?>

<div>
  <div>
    Create Authentication Provider
  </div>
  <div>
    <a href="<?= $createLdapBackend ?>"><i class="icinga-icon-create"></i> Create A New LDAP Authentication Backend</a><br/>
    <a href="<?= $createDbBackend ?>"><i class="icinga-icon-create"></i> Create A New DB Authentication Backend</a>
  </div>
</div>

<?php foreach ($this->backends as $backend): ?>
<div>
  <div>
    Backend <?= $this->escape($backend->name); ?>
    <br/>
    <?= $backend->reorderForm; ?>
  </div>
  <div>
    <a href="<?= $this->href('config/editAuthenticationBackend', array('auth_backend' => $backend->name));?>">
        <i class="icinga-icon-edit"></i> Edit This Authentication Provider
    </a>
    <br/>
    <?php if (count($this->backends) > 1): ?>
    <a href="<?= $this->href('config/removeAuthenticationBackend', array('auth_backend' => $backend->name));?>">
        <i class="icinga-icon-remove"></i> Remove This Authentication Provider
    </a>
    <br/>
    <?php endif; ?>
  </div>
</div>
<?php endforeach; ?>
</div>
