<div class="controls">
<?= $this->tabs->render($this); ?>
</div>

<div class="content">
<?php $errors = $this->form->getErrorMessages(); ?>

<?php if (isset($this->messageBox)): ?>
  <?= $this->messageBox->render() ?>
<?php endif ?>

<?php if ($this->successMessage): ?>
<div>
  <i class="icinga-icon-success"></i>
  <strong><?= $this->escape($this->successMessage); ?></strong>
</div>
<?php endif; ?>

<?php if (!empty($errors)) : ?>
<div>
  <h4>Errors occured when trying to save the project.</h4>
  <p>
      The following errors occured when trying to save the configuration:
  </p>
  <ul>
    <?php foreach($errors as $error): ?>
    <li><?= $this->escape($error) ?></li>
    <?php endforeach; ?>
  </ul>
</div>

<?php endif; ?>
<?= $this->form ?>
</div>

