<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->translate('Installed Modules') ?></h1>
<?= $this->paginationControl($modules) ?>
</div>

<div class="content">
<table class="action" data-base-target="_next">
  <tbody>
  <?php foreach ($modules as $module): ?>
    <tr>
      <td>
      <?php if ($module->enabled): ?>
      <?= $this->icon('thumbs-up', $this->translate('Module is enabled')) ?>
      <?php else: ?>
      <?= $this->icon('thumbs-down', $this->translate('Module is disabled')) ?>
      <?php endif ?>
        <a href="<?= $this->url(
            'config/module/',
            array('name' => $module->name)
        ) ?>"><?= $this->escape($module->name); ?></a> (<?=
            $module->enabled ? ($module->loaded ? $this->translate('enabled') : $this->translate('failed')) : $this->translate('disabled')
        ?>)
      </td>
    </tr>
  <?php endforeach ?>
  </tbody>
</table>
</div>
