<?php if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <?= $this->sortBox; ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content">
  <table class="action" data-base-target="_next">
    <tbody>
    <?php foreach ($modules as $module): ?>
      <tr>
        <td>
          <?php if ($module->enabled && $module->loaded) {
            echo $this->icon('thumbs-up', sprintf($this->translate('Module %s is enabled'), $module->name));
          } elseif (! $module->enabled) {
            echo $this->icon('thumbs-down', sprintf($this->translate('Module %s is disabled'), $module->name));
          } else { // ! $module->loaded
            echo $this->icon('thumbs-down', sprintf($this->translate('Module %s has failed to load'), $module->name));
          }

          echo $this->qlink(
            $module->name,
            'config/module/',
            array('name' => $module->name),
            array('title' => sprintf($this->translate('Show the overview of the %s module'), $module->name))
          ); ?>
        </td>
      </tr>
    <?php endforeach ?>
    </tbody>
  </table>
</div>
