<?php if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <div class="grid dont-print">
    <div class="col-1-3 text-left">
      <?= $this->limiter ?>
    </div>
    <div class="col-1-3">
      <?= $this->paginator ?>
    </div>
    <div class="col-1-3 text-right">
      <?= $this->sortBox ?>
    </div>
  </div>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content">
  <table class="action-table listing-table" data-base-target="_next">
    <thead>
    <tr>
      <th><?= $this->translate('Module') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($modules as $module): ?>
      <tr>
        <td>
          <?php if ($module->enabled && $module->loaded) {
            echo $this->icon('thumbs-up', sprintf($this->translate('Module %s is enabled'), $module->name));
          } elseif (! $module->enabled) {
            echo $this->icon('block', sprintf($this->translate('Module %s is disabled'), $module->name));
          } else { // ! $module->loaded
            echo $this->icon('block', sprintf($this->translate('Module %s has failed to load'), $module->name));
          }

          echo $this->qlink(
            $module->name,
            'config/module/',
            array('name' => $module->name),
            array('title' => sprintf($this->translate('Show the overview of the %s module'), $module->name), 'class' => 'rowaction')
          ); ?>
        </td>
      </tr>
    <?php endforeach ?>
    </tbody>
  </table>
</div>
