<?php
use Icinga\Web\Url;
$createResource = $this->href('/config/createresource');
?>
<div class="controls">
    <?= $this->tabs->render($this); ?>
</div>

<div class="content">
    <?php if (isset($this->messageBox)): ?>
        <?= $this->messageBox->render() ?>
    <?php endif ?>

    <h1>Create Resource</h1>
    <p><a href="<?= $createResource ?>"><?= $this->img('img/icons/create.png', array('title' => 'Create A New Resource'));
                                                                                              ?> Create A New Resource</a></p>

    <table class="configTable">
        <?php foreach ($this->resources as $name => $resource): ?>
            <tr>
                <td class="configTable">
                    <div>
                        <b>Resource:</b>&ensp;<?= $this->escape($name); ?>
                    </div>
                    <div>
                        <a href="<?= $this->href('config/editresource', array('resource' => $name));?>">
                            <?= $this->img('img/icons/edit.png', array('title' => 'Edit')); ?> Edit</a>&emsp;
                        <?php if (count($this->resources) > 1): ?>
                            <a href="<?= $this->href('config/removeresource', array('resource' => $name));?>">
                                <?= $this->img('img/icons/remove.png', array('title' => 'Remove')); ?> Remove</a>&emsp;
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

