<?php use Icinga\Data\Filter\Filter; ?>

<div class="controls separated">
  <?php if (! $this->compact): ?>
    <?= $this->tabs; ?>
  <?php endif ?>
    <?= $this->render('partials/host/object-header.phtml') ?>
    <h3 class="tinystatesummary" <?= $this->compact ? ' data-base-target="col1"' : ''; ?>>
        <?php
        $this->stats = $object->stats;
        $this->baseFilter = Filter::where('host', $object->host_name);
        echo $this->render('list/components/servicesummary.phtml');
        ?>
    </h3>
</div>

<?= $this->render('partials/object/detail-content.phtml') ?>
