<?php if (!$this->compact): ?>
<div class="controls">
    <?= $this->tabs ?>
</div>
<?php endif ?>
<div class="content tactical">
    <div class="boxview" data-base-target="col2">
        <?= $this->render('tactical/components/problem_hosts.phtml'); ?>
        <?= $this->render('tactical/components/ok_hosts.phtml'); ?>
        <br />
        <?= $this->render('tactical/components/hostservicechecks.phtml'); ?>
        <?= $this->render('tactical/components/monitoringfeatures.phtml'); ?>
    </div>
</div>
