name: Docker image

on:
  release:
    types:
      - published
  schedule:
    # for main, every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  docker-release:
    if: github.event_name == 'release'
    concurrency: docker-release
    runs-on: ubuntu-24.04

    steps:
      - name: Docker image
        uses: Icinga/docker-icingaweb2@master
        with:
          dockerhub-token: '${{ secrets.DOCKER_HUB_PERSONAL_TOKEN }}'

  docker:
    if: github.event_name != 'release'
    runs-on: ubuntu-24.04

    steps:
      - name: Docker image
        uses: Icinga/docker-icingaweb2@master
        with:
          dockerhub-token: '${{ secrets.DOCKER_HUB_PERSONAL_TOKEN }}'
