name: Docker image

on:
  pull_request: {}
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Docker image
        uses: Icinga/docker-icingaweb2@master
        env:
          INPUT_TOKEN: '${{ github.token }}'
          DOCKER_HUB_PASSWORD: '${{ secrets.DOCKER_HUB_PERSONAL_TOKEN }}'
