name: Docker image

on:
  release:
    types:
      - published
  push: {}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Docker image
        uses: Icinga/docker-icingaweb2@Simplify
        with:
          dockerhub-token: '${{ secrets.DOCKER_HUB_PERSONAL_TOKEN }}'
