name: Docker image

on:
  release:
    types:
      - published
  schedule:
    # for master, every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Docker image
        uses: Icinga/docker-icingaweb2@master
        with:
          dockerhub-token: '${{ secrets.DOCKER_HUB_PERSONAL_TOKEN }}'
